### ISSUE TITLE
Intermittent Collection was modified; enumeration operation may not execute. on Mapper.Map call

### ISSUE THREAD

**Issue by pculver** [AutoMapper/AutoMapper#1010]
I am getting an intermittent exception when calling Mapper.Map\<OrderExtendedDigestDto>(OrderDto).  All of my configuration is done at startup time of the application via Profile classes so I don't know why this would happen. 

The mapping setup looks like

            // Digest DTO
            CreateMap<OrderDto, OrderDigestDto>()
                .ForMember(digest => digest.OrderTemplateId, conf => conf.MapFrom(full => full.CoreTemplate.Id));

            CreateMap<OrderDto, OrderExtendedDigestDto>()
                .IncludeBase<OrderDto, OrderDigestDto>();

The exception is:

```
Collection was modified; enumeration operation may not execute.

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.TypeMap.ApplyInheritedTypeMap(TypeMap inheritedTypeMap)
   at AutoMapper.TypeMap.Seal()
   at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
```

Any thoughts?  I didn't get this error in version 3.3.1.  I am now using 4.1.1 from nuget.

**Comment by pculver** [comment]
Just saw this in documentation.  

`Mapper.Configuration.Seal(); // this is REQUIRED in AutoMapper 4.0 to make inheritance work`

which I do not do.  Would this be the root of my issue?

**Comment by lbargaoanu** [comment]
Probably. Seal is part of the configuration. I would guess multiple threads were on that stack trace, hence the issue.

**Comment by pculver** [comment]
There were multiple threads.   Should I use `Mapper.Configuration.Seal()` after making a number of calls to `Mapper.Configuration.AddProfile()` or should I use `Mapper.Initialize()`?

**Comment by lbargaoanu** [comment]
Mapper.Initialize is the new way. Seal is more for backward compatibility.
