### ISSUE TITLE
CreateMap call not thread-safe and throws NullReferenceException

### ISSUE THREAD

**Issue by Tra5is** [AutoMapper/AutoMapper#1018]
We're getting the following exception:

	--NullReferenceException
	at AutoMapper.TypeMapFactory.<>c__DisplayClass3_0.b__0(IMemberConfiguration _)
	at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
	at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, IProfileConfiguration options, MemberList memberList)
	at AutoMapper.ConfigurationStore.<>c__DisplayClass80_0.b__0(TypePair tp)
	at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
	at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination](String profileName, MemberList memberList)

They're extremely difficult to reproduce, but they do happen about 1 per week on our build machine. 

After some digging this seems to be part of the problem:
ConfigurationStore.cs Line 316

According to MSDN: If you call GetOrAdd simultaneously on different threads, addValueFactory may be called multiple times, but its key/value pair might not be added to the dictionary for every call. 

My presumption is that the MapDestinationPropertyToSource enumeration is updated by multiple threads and when that this happens in a specific way the iterator returns null items to one of the threads. 

To prove this I've created a small test project that runs CreateMap on mutiple threads, and changed TypeMapFactory to throw an exception when an item from MemberConfigurations is null. After a few runs of the test app the exception is thrown. 

        private bool MapDestinationPropertyToSource(IProfileConfiguration options, TypeDetails sourceTypeInfo, Type destType, string destMemberInfo, LinkedList<IValueResolver> members)
        {
            return options.MemberConfigurations.Any(_ =>
            {
                if (null == _) throw new ApplicationException("Null item in the list!!!");
                return _.MapDestinationPropertyToSource(options, sourceTypeInfo, destType, destMemberInfo, members);
            });
        }

I'm also only able to reproduce this when mapping large types (30+ properties) that use inheritance.  I don't have time to investigate far enough to provide a solution, but hopefully this helps point someone in the right direction!  

(I noticed that another closed issue looks remarkably similar: Issue #109 way back in 2011!)

**Comment by Tra5is** [comment]
A debug stack might provide a bit more info:
at AutoMapper.TypeMapFactory.<>c__DisplayClass3_0.<MapDestinationPropertyToSource>b__0(IMemberConfiguration _) in D:\Source\AutoMapper\src\AutoMapper\TypeMapFactory.cs:line 70
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.TypeMapFactory.MapDestinationPropertyToSource(IProfileConfiguration options, TypeDetails sourceTypeInfo, Type destType, String destMemberInfo, LinkedList`1 members) in D:\Source\AutoMapper\src\AutoMapper\TypeMapFactory.cs:line 70
   at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, IProfileConfiguration options, MemberList memberList) in D:\Source\AutoMapper\src\AutoMapper\TypeMapFactory.cs:line 46
   at AutoMapper.ConfigurationStore.<>c__DisplayClass72_0.<CreateTypeMap>b__0(TypePair tp) in D:\Source\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 320
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.ConfigurationStore.CreateTypeMap(Type source, Type destination, String profileName, MemberList memberList) in D:\Source\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 316
   at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination](String profileName, MemberList memberList) in D:\Source\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 241
   at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination](String profileName) in D:\Source\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 235
   at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination]() in D:\Source\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 225
   at AutoMapper.Mapper.CreateMap[TSource,TDestination]() in D:\Source\AutoMapper\src\AutoMapper\Mapper.cs:line 251
   at AutoMapperExceptionTester.Program.<>c.<Main>b__0_0(Int32 i) in D:\Source\Research\AutoMapperExceptionTester\AutoMapperExceptionTester\Program.cs:line 18
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )

**Comment by lbargaoanu** [comment]
You should only call CreateMap on app initialization.

**Comment by Tra5is** [comment]
Yeah, in our case we're doing a bunch of CreateMap calls during app initialization. We have several modules, each with their own maps from data-contract  types to internal types. These classes which encapsulate the mapping configuration are loaded by the hosting exe (during app initialization) and run concurrently on different threads.

**Comment by lbargaoanu** [comment]
Well don't :) You should call CreateMap on a single thread and Seal at the end, or even better, Mapper.Initialize.

**Comment by Tra5is** [comment]
With Mapper being a globally accessible singleton I wouldn't expect there
to be issues that arise from accessing it from multiple threads.

**Comment by lbargaoanu** [comment]
That ship has sailed :)

**Comment by jbogard** [comment]
The opposite is most likely true for statics. Global state accessed and
mutated by multiple threads guarantees issues.

**Comment by lbargaoanu** [comment]
I think @Tra5is meant that if you expose statics, they should be thread safe. And he's right. But as we see it now, there is the init phase, and from that point on (Initialize or Seal), you can call Map on any thread.

**Comment by Tra5is** [comment]
Thanks Lucian, that's what I was getting at. I just wonder if the
init phase could be made to be thread-safe too.

**Comment by lbargaoanu** [comment]
But why? Performance? If that's the case, how many entities and how long it takes single threaded. Maybe we can work on that.

**Comment by Tra5is** [comment]
To avoid completely unpredictable fatal runtime exceptions. To avoid imposing unnecessary design constraints. I could go on...

**Comment by lbargaoanu** [comment]
Don't :)

**Comment by jbogard** [comment]
CreateMap and other config likely will never be type safe. This is similar
to other configuration models like MVC, WebAPI, EF etc. Just do all your
config once, I wrap mine in a Lazy so that it only happens once. Yes you'll
get weird errors if you don't, sometimes but at least it's consistent with
other config-at-start time models.
