### ISSUE TITLE
Seemingly Random Null Reference Exceptions

### ISSUE THREAD

**Issue by sds88** [AutoMapper/AutoMapper#1134]
Our app normally runs fine with auto mapper, but occasionally there will be short periods of time where it will blow up with null reference exceptions similar to the following:
```
[NullReferenceException: Object reference not set to an instance of an object.]
at AutoMapper.TypeMap.<>c__DisplayClass101_0.<ApplyInheritedTypeMap>b__1(PropertyMap m)
at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
at AutoMapper.TypeMap.ApplyInheritedTypeMap(TypeMap inheritedTypeMap)
at AutoMapper.TypeMap.Seal()
at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)

[AutoMapperMappingException: Mapping types: TitleMetadata -> MediaResponse Frontend_Api.Models.TitleMetadata -> Frontend_Api.Models.MediaResponse Destination path: MediaResponse[][0] Source value: Frontend_Api.Models.TitleMetadata]
```

I can't tell from these stack traces what is actually going wrong.  These are what my maps look like for the `TitleMetadata -> MediaResponse` conversion:
```
 Mapper.CreateMap<TitleMetadata, MediaBaseResponse>()
                .ForMember(m => m.Id, opt => opt.MapFrom(src => src.Metadata.TitleId))
                .ForMember(m => m.FirstCreatorName, opt => opt.MapFrom(src => src.Metadata.ContentCreators != null && src.Metadata.ContentCreators.Length > 0 ? src.Metadata.ContentCreators.OrderBy(c => c.Rank).First().Name : ""))
                .ForMember(m => m.FirstCreatorId, opt => opt.MapFrom(src => src.Metadata.ContentCreators != null && src.Metadata.ContentCreators.Length > 0 ? src.Metadata.ContentCreators.OrderBy(c => c.Rank).First().Id : -1))
                .ForMember(m => m.Type, opt => opt.MapFrom(src => ToMediaType(src.Metadata.FormatClassification)))
                .ForMember(m => m.Covers, opt => opt.MapFrom(src => src.Metadata.ImageList))
                .ForMember(m => m.Title, opt => opt.MapFrom(src => src.Metadata.Title))
                .Include<TitleMetadata, MediaResponse>()
                .Include<TitleMetadata, BookshelfResponse>()
                .Include<TitleMetadata, PatronHoldsResponse>();

            Mapper.CreateMap<TitleMetadata, MediaResponse>()
                .ForMember(m => m.IsAvailable, opt => opt.MapFrom(src => src.Availability != null && src.Availability.Sum(a => a.AvailableCopies) > 0))
                .ForMember(m => m.IsPreReleaseTitle, opt => opt.MapFrom(src => src.Metadata.Formats == null || !src.Metadata.Formats.Any() || src.Metadata.Formats.Min(f => f.OnSaleDate) > DateTime.UtcNow.Date))
                .ForMember(m => m.EstimatedReleaseDate, opt => opt.MapFrom(src => (src.Metadata.Formats == null || !src.Metadata.Formats.Any()) ? (DateTime?) null : src.Metadata.Formats.Min(f => f.OnSaleDate)))
                .ForMember(m => m.Links, opt => opt.MapFrom(src => src.Metadata.ExcerptLinks))
                .ForMember(m => m.AvailableCopies, opt => opt.MapFrom(src => src.Availability == null ? 0 : src.Availability.Sum(a => a.AvailableCopies)))
                .ForMember(m => m.OwnedCopies, opt => opt.MapFrom(src => src.Availability == null ? 0 : src.Availability.Sum(a => a.PurchasedCopies)))
                .ForMember(m => m.HoldsCount, opt => opt.MapFrom(src => src.Availability == null ? 0 : src.Availability.Sum(a => a.HoldsCount)))
                .ForMember(m => m.Description, opt => opt.MapFrom(src => TruncateDescription(src.Metadata.ShortDescription ?? src.Metadata.FullDescription)))
                .ForMember(m => m.Subtitle, opt => opt.MapFrom(src => src.Metadata.Subtitle))
                .ForMember(m => m.Series, opt => opt.MapFrom(src => src.Metadata.Series))
                .ForMember(m => m.Publisher, opt => opt.MapFrom(src => ToPublisher(src.Metadata.Publisher, src.Metadata.PublisherId)))
                .Include<TitleMetadata, MediaDetailsResponse>()
                .Include<TitleMetadata, WishlistResponse>()
                .AfterMap((left, right) =>
                {
                    // bottom out availability at zero
                    if (right.AvailableCopies < 0)
                        right.AvailableCopies = 0;
                });
```

The only thing I can see that would possibly cause a null reference error is if the `Metadata` object on `TitleMetadata` is null, but if that was the case the app would have crashed at a much sooner point before any automapper code was executed.

**Comment by jbogard** [comment]
Which version of AutoMapper are you on?

This should go away with 4.2, where Mapper.CreateMap is deprecated.

**Comment by sds88** [comment]
We're on 4.1.1, we'll give it a shot with 4.2, thanks.

**Comment by vanthoainguyen** [comment]
4.2.1 got the same problem

**Comment by jbogard** [comment]
Try 5.1 then

**Comment by vanthoainguyen** [comment]
It would be very good if you can tell us what's caused that issue? I also used inherited mapping and I can really afford to see it happen again on production until I know what really caused the issue. It's really hard to reproduce this bug.

**Comment by jbogard** [comment]
Gremlins are my guess here.

The entire configuration API was gutted and re-written in 5.0. Part of the issue here was that configuration was mutable at any time, you could call `Mapper.CreateMap` anytime, anywhere.

I could never reproduce this bug, nor could I ever get anyone that saw it to reliably reproduce it. I haven't seen it since 5.0, though.
