### ISSUE TITLE
Constructor mapping doesn't honor `ResolveUsing`

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper#1209]
The following program works fine:

```c#
class Program
{
    static void Main(string[] args)
    {
        var mapper = new MapperConfiguration(configure =>
        {
            configure.CreateMap<FooSrc, FooDest>()
                .ForMember(f => f.Bar, cfg => cfg.ResolveUsing(f =>
                {
                    // just to do something non-trivial
                    var baz = string.Join("", f.Bar.Reverse());
                    return new Bar { Baz = baz };
                }));
        }).CreateMapper();

        var foo = new FooSrc
        {
            Bar = "This is a test"
        };

        Console.WriteLine(mapper.Map<FooDest>(foo).Bar.Baz);
    }
}

class FooSrc
{
    public string Bar { get; set; }
}

class FooDest
{
    public Bar Bar { get; set; }
}

class Bar
{
    public string Baz { get; set; }
}
```

However, if I change the `FooDest` class to have constructor-initialized get-only properties, i.e.

```c#
class FooDest
{
    public FooDest(Bar bar)
    {
        Bar = bar;
    }

    public Bar Bar { get; }
}
```

I get an exception at map-time:

```txt
Unhandled Exception: AutoMapper.AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
String -> Bar
System.String -> ConsoleApplication5.Bar

Destination path:
FooDest

Source value:
This is a test
   at AutoMapper.MappingEngine.Map(ResolutionContext context)
   at AutoMapper.ConstructorMap.ResolveValue(ResolutionContext context)
   at AutoMapper.MappingEngine.CreateObject(ResolutionContext context)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.NewObjectPropertyMapMappingStrategy.GetMappedObject(ResolutionContext context)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context)
   at AutoMapper.MappingEngine.Map(ResolutionContext context)
   at AutoMapper.Mapper.MapCore(Object source, Type sourceType, Type destinationType, MappingOperationOptions options)
   at AutoMapper.Mapper.AutoMapper.IMapper.Map(Object source, Type sourceType, Type destinationType, Action`1 opts)
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source, Action`1 opts)
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at ConsoleApplication5.Program.Main(String[] args) in C:\Users\TLY01\Documents\Visual Studio 2015\Projects\ConsoleApplication5\ConsoleApplication5\
Program.cs:line 31
```

Mapping to the constructor arguments work fine if I don't use `ResolveUsing` (i.e. for cases that can be covered by convention), but it seems that the constructor mapping introduced in 4.2 didn't take this possibility into account. This is on the latest CI build from MyGet.

---

My actual use case is the following mapping. Maybe there's another way to solve this problem?

```c#
.ForMember(result => result.PartTyp, cfg => cfg.ResolveUsing(db =>
{
    var identitetsbeteckning = new IdentitetsbeteckningParser(DateTime.Now).ParseFromString(db.Identitetsbeteckning);
    return identitetsbeteckning.IsFysiskPerson
        ? db.PartTyp == "PRIV"
            ? Models.PartTyp.Privatperson
            : Models.PartTyp.EnskildFirma
        : Models.PartTyp.JuridiskPerson;
}));
```

**Comment by jbogard** [comment]
ResolveUsing is for properties/fields (aka members). You're trying to target a constructor parameter. There's separate config for that:

```
CreateMap<Foo, Bar>()
.ForCtorParam("bar", opt => opt.MapFrom(src => /* magic here */));
```

I don't try to map up member mappings to constructor parameters. I mean, I could, but it would be a bit awkward because the two only match up based on either a fuzzy name match or peering inside your constructor IL and seeing "oh, the bar parameter sets the Bar property".

**Comment by tlycken** [comment]
Ah, great! I guess I just need to read the docs more carefully. Thanks a lot for the quick reply!

**Comment by tlycken** [comment]
Ah, hum. `MapFrom` won't get me all the way there, though - what I'm doing is too complex to work as an `Expression<Func<FooSrc, Bar>>`... I guess I'll take a stab at a PR for enabling in `ResolveUsing` here too.
