### ISSUE TITLE
AutoMapper 5.0.0-beta-1 with ASP.NET Core RC2 throws System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by iberodev** [AutoMapper/AutoMapper#1297]
I am getting an exception since I migrated to ASP.NET Core RC2 and upgraded to AutoMapper 5.0.0-beta-1. This worked fine before, that is the strange part.

The scenario is something like this (simplified):
I have these entities:
```
 public class Consignment
 {
        public int Id { get; set; }
        public List<Package> Packages { get; set; }
        public List<TransportEquipment> TransportEquipment { get; set; }
}

public class TransportEquipment
{
        public int Id { get; set; }
        public int ConsignmentId { get; set; }
        public Consignment Consignment { get; set; }
}

public class Package
 {
        public int Id { get; set; }
        public int ConsignmentId { get; set; }
        public Consignment Consignment { get; set; }
}
```

And these service models

```
public class Consignment 
{
        public int Id { get; set; }
        public List<PackageSummary> PackageSummaries { get; set; }
        public List<TransportEquipmentSummary> TransportEquipmentSummaries { get; set; }
}

public class PackageSummary
{
        public int Id { get; set; }
}

public class TransportEquipmentSummary
{
        public int Id { get; set; }
}

```

And I am trying to map a ConsignmentEntity to a Consignment service model so I have this type configurator
```

public class ConsignmentEntityToConsignmentAutoMapperTypeConfigurator : IAutoMapperTypeConfigurator
    {
        public void Configure(IMapperConfiguration mapperConfiguration)
        {
            mapperConfiguration.CreateMap<Data.Models.Consignment, Consignment>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(c => c.Id))
                .ForMember(dest => dest.TransportEquipmentSummaries, opt => opt.MapFrom(c => c.TransportEquipment != null ?
                    c.TransportEquipment : Enumerable.Empty<Data.Models.TransportEquipment>().ToList()))
                .ForMember(dest => dest.PackageSummaries, opt => opt.MapFrom(c => c.Packages != null ?
                    c.Packages : Enumerable.Empty<Data.Models.Package>().ToList()))
        }
    }
```

And these other mappings for the nested lists
```
public class PackageEntityToPackageSummaryAutoMapperTypeConfigurator : IAutoMapperTypeConfigurator
{
        public void Configure(IMapperConfiguration mapperConfiguration)
        {
            mapperConfiguration.CreateMap<Data.Models.Package, PackageSummary>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(p => p.Id))
        }
}

public class TransportEquipmentEntityToTransportEquipmentSummaryAutoMapperTypeConfigurator : IAutoMapperTypeConfigurator
{
        public void Configure(IMapperConfiguration mapperConfiguration)
        {
            mapperConfiguration.CreateMap<Data.Models.TransportEquipment, TransportEquipmentSummary>()
                .ForMember(dest => dest.Id, opt => opt.MapFrom(t => t.Id))
        }
}
```

And the exception is 

```
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added. Key: MyModels.TransportEquipment Single[TransportEquipment](System.Collections.Generic.IEnumerable`1[MyModels.TransportEquipment])
>    at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
>    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
>    at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](List`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>    at AutoMapper.Configuration.Conventions.SourceToDestinationNameMapperAttributesMember.<>c__DisplayClass1_0.<GetMatchingMemberInfo>b__0(TypeDetails ti)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at AutoMapper.Configuration.Conventions.SourceToDestinationNameMapperAttributesMember.GetMatchingMemberInfo(IGetTypeInfoMembers getTypeInfoMembers, TypeDetails typeInfo, Type destType, Type destMemberType, String nameToSearch)
>    at AutoMapper.Configuration.Conventions.ParentSourceToDestinationNameMapper.GetMatchingMemberInfo(TypeDetails typeInfo, Type destType, Type destMemberType, String nameToSearch)
>    at AutoMapper.Configuration.Conventions.DefaultMember.MapDestinationPropertyToSource(IProfileConfiguration options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers, IMemberConfiguration parent)
>    at AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(IProfileConfiguration options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers)
>    at AutoMapper.Configuration.Conventions.NameSplitMember.MapDestinationPropertyToSource(IProfileConfiguration options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers, IMemberConfiguration parent)
>    at AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(IProfileConfiguration options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers)
>    at AutoMapper.TypeMapFactory.<>c__DisplayClass1_0.<MapDestinationPropertyToSource>b__0(IMemberConfiguration _)
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, IProfileConfiguration options, MemberList memberList)
>    at AutoMapper.Profile.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration config)
>    at AutoMapper.Profile.AutoMapper.IProfileConfiguration.Register(TypeMapRegistry typeMapRegistry)
>    at AutoMapper.MapperConfiguration.Seal()
>    at AutoMapper.MapperConfiguration..ctor(Action`1 configure, IEnumerable`1 mappers)
>    at AutoMapper.Mapper.Initialize(Action`1 config)
>    at MyMvc.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, MyContextSeedData seeder, IEnumerable`1 autoMapperTypeConfigurations) in C:\gitrepos\MyApi\src\MyMvc\Startup.cs:line 258
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.AspNetCore.Hosting.Startup.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```
**What does it mean this exception? What duplicate key?** I am trying to find out why it does not like the Mapping for the TransportEquipment list and why the Packages is all good despite being both similar in structure.

Has anybody tried something similar with the latest version? Is it a bug? Maybe something to do with a circular reference due to the fact that both my Package and TransportEquipment have a reference to a Consignmnet? (Although I don't see how, because the destination mapping is something quite simple)

**Comment by realavaloro** [comment]
If in my Consignment entity class I rename
`public List<TransportEquipment> TransportEquipment { get; set; }` with `public List<TransportEquipment> TransportEquipmentWhatever { get; set; }` 
the problem disappears. 
This is strange.

**Comment by jbogard** [comment]
How are you calling into IAutoTypeMapConfigurator?

**Comment by xyting** [comment]
I have the some problem with following code
```C#
 public class Account {
        public int  UserId { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public string IDCard { get; set; }
        public AccountKind Kind { get; set; }
        public decimal UnUsedAmount { get; set; }
        public List<Outlay> Outlay { get; set; 
}

public class AccountModel {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public string IDCard { get; set; }
        public AccountKind Kind { get; set; }
        public decimal UnUsedAmount { get; set; }
        public decimal OutlayAmount { get; set; }
}

public class FinanceProfile : Profile {
        public FinanceProfile() {
            CreateMap<HedgedHistory, HedgedHistoryModel>();
            CreateMap<RevenueExpenditurModel, RevenueExpenditurModel>();          
            CreateMap<Income, IncomeModel>();
            CreateMap<Outlay, OutlayModel>();
            CreateMap<Account, AccountModel>()
                .ForMember(am => am.OutlayAmount, opt => opt.MapFrom(a => a.Outlay.Sum(o => o.Amount)));
        }
}

An exception of type 'System.ArgumentException' occurred in mscorlib.ni.dll but was not handled in user code

Additional information: An item with the same key has already been added. Key: Finance.Domains.Outlay Single[Outlay](System.Collections.Generic.IEnumerable`1
```
