### ISSUE TITLE
Strange exception if trying to map unmapped type.

### ISSUE THREAD

**Issue by Tasteful** [AutoMapper/AutoMapper#1366]
I'm upgrading my project to use the 5.0.0-beta version of AutoMapper and got exception that for me is not telling correct information. Better if I got an "Type not mapped exception".

```
Result Message:	Expression of type 'System.Object' cannot be used for constructor parameter of type 'System.Exception'

Result StackTrace:	
at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at AutoMapper.MapperConfiguration.MapperFuncs.GenerateObjectMapperExpression(MapRequest mapRequest, IObjectMapper mapperToUse, MapperConfiguration mapperConfiguration)
   at AutoMapper.MapperConfiguration.MapperFuncs..ctor(MapRequest mapRequest, IObjectMapper mapperToUse, MapperConfiguration mapperConfiguration)
   at AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.MapperConfiguration.GetUntypedMapperFunc(MapRequest mapRequest)
   at AutoMapper.Mapper.AutoMapper.IMapper.Map(Object source, Type sourceType, Type destinationType)
   at AutoMapper.Mapper.Map(Object source, Type sourceType, Type destinationType)
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by Tasteful** [comment]
@lbargaoanu added testcase as PR #1367

**Comment by lbargaoanu** [comment]
Thanks.

**Comment by lbargaoanu** [comment]
Your point remains, but for testing you usually call AssertConfigurationIsValid, which hopefully reports the missing map.

**Comment by Tasteful** [comment]
In this case the AssertConfigurationIsValid is not helping because the mapping for the entity Source/Dest does not exists at all that will result in a valid configuration exists.

**Comment by lbargaoanu** [comment]
Yes, obviously :)
