### ISSUE TITLE
Can't configure mapping where source and destination have byte[] properties

### ISSUE THREAD

**Issue by wojciech-wieronski** [AutoMapper/AutoMapper#1393]
Tested with: Version 4.2.1 and 5.0.0

Getting the following exception when configuring a mapping where both source and destination have a byte[] (SQL Server Timestamp, Used for RowVersioning):

{"Value cannot be null.\r\nParameter name: property"}

   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at AutoMapper.Mappers.PrimitiveArrayMapper.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap pm, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass5_0.<CreateAssignmentFunc>b__1(PropertyMap pm)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam, Expression destinationFunc)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildMapperFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry)
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal(IMapperConfigurationExpression configuration)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at Allocations.WebAPI.Infrastructure.DI.DefaultModule.Load(ContainerBuilder builder)
   at Autofac.Module.Configure(IComponentRegistry componentRegistry)
   at Autofac.ContainerBuilder.Build(IComponentRegistry componentRegistry, Boolean excludeDefaultModules)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Allocations.WebAPI.Startup.ConfigureServices(IServiceCollection services)

When adding an explicit ignore on the property mappings other than the RowVersion work as expected.

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by bsheldrick** [comment]
I'm getting the same error in 5.0.0 but works in 5.0.0-beta-1.  However, I don't have any `byte[]` properties. 

```
var mappings = new MapperConfiguration(config =>
{				
	config.AddProfile(new SomeProfile());
	config.AddProfile(new AnotherProfile());				
});
```
This is happening after upgrading to .NET Core 1.0

**Comment by jbogard** [comment]
@bsheldrick what's the exception you're getting?

**Comment by bsheldrick** [comment]
@jbogard here is the exception I get.  
```
at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at AutoMapper.Mappers.PrimitiveArrayMapper.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap pm, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass5_0.<CreateAssignmentFunc>b__1(PropertyMap pm)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam, Expression destinationFunc)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildMapperFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry)
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal(IMapperConfigurationExpression configuration)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
Result Message:	
Value cannot be null.
Parameter name: property

```

**Comment by jbogard** [comment]
Ah OK, is it possible to have a source/destination type? Trying to reproduce but unable :(

**Comment by TylerCarlson1** [comment]
I would guess the problem is [here](https://github.com/AutoMapper/AutoMapper/blob/267941d6f95505752e3f051604b61c4054507cfe/src/AutoMapper/Mappers/PrimitiveArrayMapper.cs#L45)

**Comment by bsheldrick** [comment]
@jbogard I think @TylerCarlson1 is onto something.  

My mappings don't have `byte[]` but they do have `string[]`.  I have conducted a simple test to reproduce the exception.

```
public class TestSource
{
	public string Name { get; set; }
	public string[] Things { get; set; }
}

public class TestDestination
{
	public string Name { get; set; }
	public string[] Things { get; set; }
}

public class TestProfile : Profile
{
	public TestProfile()
	{
		CreateMap<TestSource, TestDestination>();
	}
}
```

And then create the mappings:
```
var mappings = new MapperConfiguration(config =>
{
	config.AddProfile<TestProfile>();
});
```

This will fail when creating the mappings.  

I then tested by commenting out the `string[] Things` property in both source and destination classes and there is no exception.

I am running this inside an XUnit test on the latest version of .NET Core 1.0.
