### ISSUE TITLE
Can't map between List<ExpandoObject>s

### ISSUE THREAD

**Issue by mikeycooper** [AutoMapper/AutoMapper#1418]
When I try to create a map in 5.0.0 between two objects which contain properties of type List<ExpandoObject>, I receive an IndexOutOfBounds exception on the mapper Initialize: Index was outside the bounds of the array.

If I change the properties to dynamic, no exception is received.

**Comment by jbogard** [comment]
Stack trace?

**Comment by mikeycooper** [comment]
at AutoMapper.Mappers.CollectionMapperExtensions.MapKeyPairValueExpr(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Type sourceType, Type destType, ParameterExpression itemParam, Expression contextParam)
   at AutoMapper.Mappers.CollectionMapperExtensions.MapCollectionExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression, Func`2 conditionalExpression, Type ifInterfaceType, MapItem mapItem)
   at AutoMapper.Mappers.DictionaryMapper.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Mappers.CollectionMapperExtensions.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression itemParam, Expression contextParam, TypePair typePair)
   at AutoMapper.Mappers.CollectionMapperExtensions.MapItemExpr(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Type sourceType, Type destType, ParameterExpression itemParam, Expression contextParam)
   at AutoMapper.Mappers.CollectionMapperExtensions.MapCollectionExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression, Func`2 conditionalExpression, Type ifInterfaceType, MapItem mapItem)
   at AutoMapper.Mappers.CollectionMapper.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap pm, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass5_0.<CreateAssignmentFunc>b__1(PropertyMap pm)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam, Expression destinationFunc)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildMapperFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry)
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal(IMapperConfigurationExpression configuration)
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at BitLever.WebUi.App_Start.MapperConfig.ConfigureMappings() in C:\VsoRepos\bitlever\src\BitLever\BitLever.WebUi\App_Start\MapperConfig.cs:line 13
   at BitLever.WebUi.MvcApplication.Application_Start() in C:\VsoRepos\bitlever\src\BitLever\BitLever.WebUi\Global.asax.cs:line 36

**Comment by TylerCarlson1** [comment]
example?  I think I got an idea of what it is but I need an failing test to prove it works.

**Comment by TylerCarlson1** [comment]
I think I figured it out.  It had to do with mapping ExpandoObject to ExpandoObject trying to map it as a Dictionary instead of a dynamic object.
