### ISSUE TITLE
AutoMapper throws error, if byte-Array is a property of class

### ISSUE THREAD

**Issue by glatzert** [AutoMapper/AutoMapper#1442]
In a .NET Core project, using AutoMapper 5.0, the configuration will fail, if it contains a property of type `byte[]`.

The failing method is
```C#
// Demonstration purpose classes only
AutoMapper.Mapper.Initialize(cfg => cfg.CreateMap<ImageInput, Image>());

//With ImageInput and Image being something like
public class ImageInput {
  public byte[] Data {get;set;}
}
```

The error message is:
```
-		$exception	{System.ArgumentNullException: Value cannot be null.
Parameter name: property
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at AutoMapper.Mappers.PrimitiveArrayMapper.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap pm, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass5_0.<CreateAssignmentFunc>b__1(PropertyMap pm)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam, Expression destinationFunc)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildMapperFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry)
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal(IMapperConfigurationExpression configuration)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at ZDV.JGUDirectory.WebService.Startup.ConfigureServices(IServiceCollection services) in C:\...\Startup.cs:line 47}	System.ArgumentNullException

```

**Comment by lbargaoanu** [comment]
This was fixed. Try the MyGet build.

**Comment by lbargaoanu** [comment]
This can be closed.

**Comment by glatzert** [comment]
Just validated it, with the myGet feed.
Works fine. Thanks 👍
