### ISSUE TITLE
UseAsDataSource The binary operator Equal is not defined for the types 'System.Int64' and 'System.String'.

### ISSUE THREAD

**Issue by iamthemovie** [AutoMapper/AutoMapper#1461]
I'm trying to map my DTO's to a Table Model and return a projected Queryable.

I have the following classes:

A Table Class

```cs
    internal class OrganizationTable : EntityTableBase
    {
        // From EntityTableBase (here for clarity)
        public long Id { get; set; }

        public string Name { get; set; }

        public string DisplayName { get; set; }
    }
```

A DTO Class

```cs
    public class Organization : IEntity
    {
        /// <inheritdoc/>
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the Organization Name.
        /// </summary>
        public string Name { get; set; }
    }
```

The mappings work fine when calling Mapper.Map<>() but when I do the following:

```cs
var organziation =
    orgs.DbContext
           .Organization.UseAsDataSource().For<Organization>().Where(o => o.Id == "0").ToList();
```

I get the this exception:

````
An exception of type 'System.InvalidOperationException' occurred in System.Core.dll but was not handled in user code

Additional information: The binary operator Equal is not defined for the types 'System.Int64' and 'System.String'.
```

Am I doing something wrong? I have tried explicitly adding a string to Int64 converter but I get the same error.

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by iamthemovie** [comment]
Nope, same issue.

Stack trace below:

```
   at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
   at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right, Boolean liftToNull, MethodInfo method, LambdaExpression conversion)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambdaExpression[T](Expression`1 expression)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambda[T](Expression`1 expression)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.<>c__23`1.<VisitAllParametersExpression>b__23_1(Expression e, ExpressionVisitor v)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitAllParametersExpression[T](Expression`1 expression)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitLambda[T](Expression`1 expression)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.GetConvertedMethodCall(MethodCallExpression node)
   at AutoMapper.Mappers.ExpressionMapper.MappingVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.QueryableExtensions.Impl.SourceInjectedQueryProvider`2.ConvertDestinationExpressionToSourceExpression(Expression expression)
   at AutoMapper.QueryableExtensions.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression)
   at AutoMapper.QueryableExtensions.Impl.SourceInjectedQuery`2.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

Am I doing something wrong or should this work? Sorry!

**Comment by lbargaoanu** [comment]
ProjectTo works for me, I suppose for you too :) @TylerCarlson1 should be able to help you from here.

**Comment by TylerCarlson1** [comment]
Try `.Where(o => o.Id.Equals((object)"0"))` and hopefully it can be translated by the ORM.
Problem is Id is string in DTO but long in table, so when translate the expression string goes to long, but the constant doesn't get translated.

Most scenarios you would assume both properties were same type or int, long, short or something close, not string and long.

**Comment by iamthemovie** [comment]
It doesn't crash here but it doesn't return the record based on that query.

The reason we have string as our identifier is due to our data access layer abstraction.

Is there anyway to make the conversion/translation through this type of API call?

**Comment by TylerCarlson1** [comment]
Maybe try `.Where(o => o.Id.ToString() == "0")`

Or make another ID property that maps to Id but make it long and use that.
```
public class Organization : IEntity
    {
        /// <inheritdoc/>
        public string Id { get; set; }
        private long ID { 
              get { return long.Parse(Id);}
              set{ Id = value.ToString();}
        }

        /// <summary>
        /// Gets or sets the Organization Name.
        /// </summary>
        public string Name { get; set; }
    }
```

Currently there's no way to translate the `"0"`, so you have to get creative with maps so that they both use the same type.

**Comment by iamthemovie** [comment]
``.Where(o => o.Id.ToString() == "0")`` works.

Do you think adding support in so the expressions take into consideration basic mappings is possible? 

string -> int
int -> string
string -> long
long -> string

Even if something like:

```cs
// Configure AutoMapper
    Mapper.Initialize(cfg => 
      cfg.CreateMap<DTO, Table>()
        .ForMember(table => table.Id, opt => opt.MapFrom(src => Convert.ToInt64(src.Id)))
```

**Comment by jbogard** [comment]
We could have these mappings pass through the built-in mappers, which
covers this case, but the issue is LINQ providers may not support it. Even
if we added the ability to build out the expression correctly, it doesn't
help if for example EF doesn't support it.

That's why we built a separate pipeline for building the LINQ IQueryable
and OData-ish expressions, they just support a small subset of what's
actually possible in in-memory LINQ. And you only get to find out about
this at runtime :)

**Comment by TylerCarlson1** [comment]
I think it's possible to do this, but to do it correctly would be a big change.  Because you have to account for all possible scenarios, as well if LINQ provider will support it or not.

**Comment by jbogard** [comment]
Blarg

**Comment by TylerCarlson1** [comment]
@jbogard Yes yes fun fun. :)

**Comment by iamthemovie** [comment]
Anyone feel like doing it for a cookie? :)

**Comment by TylerCarlson1** [comment]
I would say close this issue and make a new issue to request feature for translation of int -> string for comparisons in UseAsDataSource() / IQueryable Mapper.

**Comment by iamthemovie** [comment]
Okay thank you! :+1:
