### ISSUE TITLE
Configuration definition raises ArgumentNullReference in 5.0.2

### ISSUE THREAD

**Issue by dsosunov** [AutoMapper/AutoMapper#1487]
In 5.0.2 the following configuration definition raises ArgumentNullReference exception

```
public interface IRes : IValueResolver<Src, Dst, int>
    {
    }

    public class Res : IRes
    {
        public int Resolve(Src source, Dst destination, int destMember, ResolutionContext context)
        {
            return 1000;
        }
    }

 var cfg = new MapperConfiguration(
                x =>
                    {
                        x.CreateMap<Src, Dst>().ForMember(d => d.Links, opt => opt.ResolveUsing<IRes>());
                    });
```

-- Message --
Value cannot be null.
Parameter name: method

--- Call Stack -- 
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression[] arguments)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildValueResolverFunc(PropertyMap propertyMap, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, Expression destValueExpr, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap pm, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam, Expression destinationFunc, ParameterExpression destination, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildMapperFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry)
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal(IConfiguration configuration)
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at ConsoleApplication11.Program.Main(String[] args) in C:\Users\Dmitriy\Documents\Visual Studio 2015\Projects\ConsoleApplication11\ConsoleApplication11\Program.cs:line 48
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by lbargaoanu** [comment]
And you types are...

**Comment by lbargaoanu** [comment]
And you should have the concrete type there, not the interface.

**Comment by lbargaoanu** [comment]
There is another issue with the extra interface. I made a PR for that one. You can work around it by not having the extra interface :) Or just wait for the PR.

**Comment by lbargaoanu** [comment]
@jbogard We allow interfaces here for ConstructServicesUsing?

**Comment by dsosunov** [comment]
In 4.2.1 it works

**Comment by dsosunov** [comment]
We use this feature since 3.x releases and I was broken in 5.0

**Comment by jbogard** [comment]
How is that resolver supposed to be constructed? You only pass the interface.

**Comment by dsosunov** [comment]
We use IUnityContainer with hierarchical lifetime manager.

The full scenario is:
a. create a child container per request
b. perform mapping by
mapper.Map<TFrom, TTo>(opt=>opt.ConstructServicesUsing(x=>child.Resolve(x));

ISomeResolver : IValueResolver<X,Y>

we use ISomeResolver to define in DI that IValueResolver<X,Y> has multiple implementations.
