### ISSUE TITLE
CreateMap with ForMember on nullable datetime throws exception on return type

### ISSUE THREAD

**Issue by Moonstick** [AutoMapper/AutoMapper#1525]
I'm trying to map as:

```
cfg.CreateMap<Alert, AlertViewModel>().ForMember(dest => dest.LastTriggered, opt => opt.MapFrom(src => src.TriggeredAlerts.Any() ? src.TriggeredAlerts.Max(x => x.TimeTriggered) : (DateTime?)null))
```

LastTriggered is DateTime?
TimeTriggered is DateTime

When mapping an object, an exception is encountered:

```
System.ArgumentException : Expression of type 'System.Nullable`1[System.DateTime]' cannot be used for return type 'System.DateTime'
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression`1.Update(Expression body, IEnumerable`1 parameters)
   at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at AutoMapper.ExpressionExtensions.IfNotNull(Expression expression, Type destinationType)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildValueResolverFunc(PropertyMap propertyMap, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, Expression destValueExpr, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap pm, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam, Expression destinationFunc, ParameterExpression destination, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildMapperFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry)
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal(IConfiguration configuration)
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
```

If I change TimeTriggered to DateTime? then the error goes away.

**Comment by jbogard** [comment]
Can you try the MyGet build?

**Comment by Moonstick** [comment]
Thanks, that looks like it's working - is there a release due any time soon?

**Comment by jbogard** [comment]
Maybe sooner than later because of #1526

**Comment by ellsworthpcx** [comment]
Hitting this problem also and it's an "LKB"... Meanwhile, if there is a way to introduce a resolver with the new 5.0X structures using profiles, that would be workable.  Two of the mapped tables I am using have nullable dates. The ideal thing would be to be able to add a resolver as a "dotitem" to a profile, by the way, possibly simply introducing a null string in the middle, seeing as the ultimate resolution will be to a JSON object anyway.  Thoughts welcome prior to the myget to nuget release...

**Comment by jbogard** [comment]
LKB?

**Comment by ellsworthpcx** [comment]
last known bug....

**Comment by jbogard** [comment]
Can you create another issue for what you're looking to do? I'm having a hard time following without code, sorry.
