### ISSUE TITLE
Invalid constructor mappings throw exceptions at seal-time

### ISSUE THREAD

**Issue by tlycken** [AutoMapper/AutoMapper#1528]
Given the following classes and mapping configuration, I get an `InvalidOperationException` (see stack trace below the code). If I comment out the constructor completely, I instead get a `NullReferenceException` (see second stack trace). Since the constructor parameters are specified with strings and not strongly typed, it would be nice if the configuration process was a little more lenient and could report these problems with better error messages.

```c#
[Fact]
public void ThrowSomeStuffAround()
{
    new MapperConfiguration(c =>
    {
        c.CreateMap<Source, DestinationA>()
            .ForCtorParam("bar", cfg => cfg.MapFrom(src => src.Foo));
    }).AssertConfigurationIsValid();
}

public class Source
{
    public string Foo { get; set; }
}

public class DestinationA
{
    public DestinationA(string barf)
    {
        Foo = barf;
    }

    public string Foo { get; }
}
```

`InvalidOperationException`, thrown when no matching constructor parameter is found:

```
System.InvalidOperationException : Sequence contains no matching element
Stack Trace:
     at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
     at AutoMapper.CtorParamConfigurationExpression`1.Configure(TypeMap typeMap)
     at AutoMapper.Configuration.MappingExpression`2.Configure(IProfileConfiguration profile, TypeMap typeMap)
     at AutoMapper.Profile.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration config)
     at AutoMapper.Profile.AutoMapper.IProfileConfiguration.Register(TypeMapRegistry typeMapRegistry)
     at AutoMapper.MapperConfiguration.Seal(IConfiguration configuration)
     at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
     at AutoMapper.MapperConfiguration..ctor(Action`1 configure, IEnumerable`1 mappers)
     at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
```

`NullReferenceException`, thrown when no constructor is found:

```
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
     at AutoMapper.CtorParamConfigurationExpression`1.Configure(TypeMap typeMap)
     at AutoMapper.Configuration.MappingExpression`2.Configure(IProfileConfiguration profile, TypeMap typeMap)
     at AutoMapper.Profile.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration config)
     at AutoMapper.Profile.AutoMapper.IProfileConfiguration.Register(TypeMapRegistry typeMapRegistry)
     at AutoMapper.MapperConfiguration.Seal(IConfiguration configuration)
     at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
     at AutoMapper.MapperConfiguration..ctor(Action`1 configure, IEnumerable`1 mappers)
     at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
```

I stumbled upon this because I wanted to create an extension on `IMappingExpression<TSrc, TDest>` called `Rename`, which would simply register both `ForMember` and `ForCtorParam` (assuming that the ctor param is named like the destination property but in camelCase), which of course blows up when using that extension method on types with no constructor.

**Comment by lbargaoanu** [comment]
PR?

**Comment by tlycken** [comment]
What do you mean - a PR with the tests, or a PR with the fix?

I'm not sure I know how to fix this...

**Comment by lbargaoanu** [comment]
A PR with the fix. It seems that all you want is a better error message. That should be easy enough, you already know the location to check.

**Comment by tlycken** [comment]
I would prefer if no error was thrown at all, but if it led to invalid mappings it was discovered upon mapping validation. I'll take a stab at it, but unless it turns out to be really easy (so easy I can manage it while waiting for builds at work today) I'm afraid it's not going to happen until August at the earliest.

**Comment by tlycken** [comment]
Turns out it wasn't so hard after all :)

**Comment by lbargaoanu** [comment]
:+1:

**Comment by jbogard** [comment]
From the other one, this should throw an AutoMapperConfigurationException. I can't build up the configuration if it's misconfigured, but InvalidOperation is noooooot the right one to do.
