### ISSUE TITLE
Duplicate type name within an assembly error when mapping to Lists of interface types

### ISSUE THREAD

**Issue by ruirrib** [AutoMapper/AutoMapper#1562]
Hi,

I am getting "Duplicate type name withing an assembly" errors in multiple situations when mapping to lists of interface types. The curious thing is that for each of the errors (I use these such mappings quite a bit in my DAL), the error occurs only on first invocation of the methods where the mappings are performed. Any subsequent calls to the same methods execute without issues.

Here is a stack trace for such an error:
```
 at System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
	   at System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType)
	   at System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
	   at System.Reflection.Emit.ModuleBuilder.DefineTypeNoLock(String name, TypeAttributes attr, Type parent, Type[] interfaces, PackingSize packingSize, Int32 typesize)
	   at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent, Type[] interfaces)
	   at AutoMapper.Execution.ProxyGenerator.CreateProxyType(Type interfaceType)
	   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
	   at AutoMapper.Execution.ProxyGenerator.GetProxyType(Type interfaceType)
	   at lambda_method(Closure , CompanyDTO , ICompany , ResolutionContext )
	   at AutoMapper.ResolutionContext.Map[TSource,TDestination](TSource source, TDestination destination)
	   at lambda_method(Closure , List`1 , List`1 , ResolutionContext )

```

**Comment by lbargaoanu** [comment]
A repro would help. Make a gist that we can execute and see fail.

**Comment by ruirrib** [comment]
That won't be too simple. This is a private project not on github.  I will try to see if I can reproduce the situation in a smaller custom project, built just for that purpose.

**Comment by ruirrib** [comment]
This is turning out to be harder than I expected. I have created a specific project and added just the types and mappings I am using, but that has not been enough to recreate the error.

Would it be a possibility to put my current code in a private repository here on GitHub and then give access to such repository, for the purpose of seeing the mapping code fail?

**Comment by jbogard** [comment]
Yep! If GH doesn't let you do this, BitBucket has private repos for free.

**Comment by jbogard** [comment]
Or, if you like, contact me offline and you can send me a private dropbox/box/whatever link to a zipped up repo

**Comment by ruirrib** [comment]
That's great, thank you very much. I need to juggle my time between the project with the problem (personal project) and other projects, but I will be sure to do it in the next couple days.

Thanks again.

**Comment by jbogard** [comment]
No worries, I know it can be time consuming and difficult to create a repro that doesn't have client stuff in it

**Comment by brianperera** [comment]
@jbogard were you able to get this issue resolved? I'm facing the same issue.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
