### ISSUE TITLE
Using NullSubstitute with different source/destination types throws ArgumentException

### ISSUE THREAD

**Issue by amyhickman** [AutoMapper/AutoMapper#1578]
Updating to the latest Automapper 5.0.2.0 is now causing an ArgumentException to be thrown during mapping configuration.
```
   at System.Linq.Expressions.Expression.ValidateCoalesceArgTypes(Type left, Type right)
   at System.Linq.Expressions.Expression.Coalesce(Expression left, Expression right, LambdaExpression conversion)
   at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right, Boolean liftToNull, MethodInfo method, LambdaExpression conversion)
   at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildValueResolverFunc(PropertyMap propertyMap, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, Expression destValueExpr, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap pm, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry registry, ParameterExpression srcParam, ParameterExpression destParam, ParameterExpression ctxtParam, Expression destinationFunc, ParameterExpression destination, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.BuildMapperFunc(TypeMap typeMap, IConfigurationProvider configurationProvider, TypeMapRegistry typeMapRegistry)
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal(IConfiguration configuration)
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at Sandbox.Program.Main() in c:\Users\rhd5559\Documents\Visual Studio 2013\Projects\Sandbox\Sandbox\Program.cs:line 38
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
A complete working example follows:
```
    public class Foo
    {
        public int Id { get; set; }
        public Bar Bar { get; set; }
    }

    public class Bar
    {
        public string Name { get; set; }
    }


    public class FooDto
    {
        public int Id { get; set; }
        public BarDto Bar { get; set; }
    }

    public class BarDto
    {
        public string Name { get; set; }
    }


    public class Program
    {
        public static void Main()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Bar, BarDto>();
                cfg.CreateMap<Foo, FooDto>()
                    .ForMember(dest => dest.Bar, opts => opts.NullSubstitute(new BarDto()));
            });

            var foo = new Foo()
            {
                Id = 5,
                Bar = null
            };

            var dto = Mapper.Map<FooDto>(foo);
            Debug.WriteLine(dto.Bar != null);
        }

    }
```

**Comment by lbargaoanu** [comment]
The way I see it both the test and the AM implementation are wrong :) I think when the source for Bar is null, it should map from the null substitute instead. @jbogard will weigh in.

**Comment by lbargaoanu** [comment]
Apparently [not](https://github.com/AutoMapper/AutoMapper/wiki/Null-substitution). Then I guess this needs more work.

**Comment by lbargaoanu** [comment]
But I'm not sure it makes much sense with the destination type. Now you have a singleton. That could be used for something like the null object pattern, but otherwise is bad practice.

**Comment by lbargaoanu** [comment]
@jbogard Should we change the docs then? Because they are misleading I would say. And as the null replacement is object, you can really pass anything. It's true that probably this is not used usually with classes.

**Comment by jbogard** [comment]
This is a breaking change, that I'm going to fix to be a null sub for the *destination* type. That way it's a coalesce around the entire operation, not pre-map. That's how it used to work anyway.

**Comment by jbogard** [comment]
Ah never mind. It would be pretty hard to make the null substitute be an overall null coalesce as opposed to just be a null substitute for the source type. Since the dest type can be non-nullable, it makes more sense to apply a substitute based on the source type, not dest type.

**Comment by lbargaoanu** [comment]
Somewhat tricky, but I say the source makes more sense.

**Comment by jbogard** [comment]
I tried to make it work with the dest type - it's pretty confusing as you have to check in multiple places and return that null substitute value. I like wrapping the resolved value, then doing a map, then setting.
