### ISSUE TITLE
5.0.2 wont install

### ISSUE THREAD

**Issue by solidcloudio** [AutoMapper/AutoMapper#1582]
Trying to install with 4.5.2 based project.

Install failed. Rolling back...
Package 'AutoMapper.5.0.2 : ' does not exist in project 'ConsoleApplication1'
Package 'AutoMapper.5.0.2 : ' does not exist in folder 'c:\users\xxx\documents\visual studio 2015\Projects\ConsoleApplication1\packages'
NuGet.Protocol.Core.Types.NuGetProtocolException: An error occurred while downloading package 'AutoMapper.5.0.2 : ' from source 'https://www.nuget.org/api/v2/'. ---> NuGet.Protocol.Core.Types.NuGetProtocolException: An error occurred while downloading package 'AutoMapper.5.0.2 : ' from source 'https://www.nuget.org/api/v2/'. ---> System.InvalidOperationException: 'AutoMapper' already has a dependency defined for 'NETStandard.Library'.
   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
   at NuGet.Manifest.Validate(Manifest manifest)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath)
   at NuGet.LocalPackageRepository.OpenPackage(String path)
   at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
   at NuGet.LocalPackageRepository.<>c__DisplayClass13.<FindPackage>b__f(String path)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NuGet.LocalPackageRepository.FindPackage(Func`2 openPackage, String packageId, SemanticVersion version)
   at NuGet.LocalPackageRepository.FindPackage(String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, SemanticVersion version, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean allowUnlisted)
   at NuGet.Protocol.Core.v2.DownloadResourceV2.DownloadToMachineCache(IPackageCacheRepository cacheRepository, PackageIdentity package, DataServicePackageRepository repository, Uri downloadUri, CancellationToken token)
   at NuGet.Protocol.Core.v2.DownloadResourceV2.DownloadFromUrl(SourcePackageDependencyInfo package, DataServicePackageRepository repository, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.Core.v2.DownloadResourceV2.DownloadFromUrl(SourcePackageDependencyInfo package, DataServicePackageRepository repository, CancellationToken token)
   at NuGet.Protocol.Core.v2.DownloadResourceV2.<>c__DisplayClass3_0.<GetDownloadResourceResultAsync>b__0()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.Core.v2.DownloadResourceV2.<>c__DisplayClass3_0.<GetDownloadResourceResultAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========

**Comment by solidcloudio** [comment]
Looks like installing the latest VSIX for 3.4.4 2015 works..
