### ISSUE TITLE
Unable to install via Nuget

### ISSUE THREAD

**Issue by jrandecker** [AutoMapper/AutoMapper#1603]
Installing Automapper via Nuget does not appear to work.  I keep getting this error from Nuget:

NuGet.Protocol.Core.Types.NuGetProtocolException: An error occurred while downloading package 'AutoMapper.5.0.2 : ' from source 'https://www.nuget.org/api/v2/'. ---> NuGet.Protocol.Core.Types.NuGetProtocolException: An error occurred while downloading package 'AutoMapper.5.0.2 : ' from source 'https://www.nuget.org/api/v2/'. ---> System.InvalidOperationException: 'AutoMapper' already has a dependency defined for 'NETStandard.Library'.
   at NuGet.Manifest.ValidateDependencySets(IPackageMetadata metadata)
   at NuGet.Manifest.Validate(Manifest manifest)
   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)
   at NuGet.LocalPackage.ReadManifest(Stream manifestStream)
   at NuGet.OptimizedZipPackage.EnsureManifest()
   at NuGet.OptimizedZipPackage..ctor(IFileSystem fileSystem, String packagePath)
   at NuGet.LocalPackageRepository.OpenPackage(String path)
   at NuGet.LocalPackageRepository.GetPackage(Func`2 openPackage, String path)
   at NuGet.LocalPackageRepository.<>c__DisplayClass13.<FindPackage>b__f(String path)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at NuGet.LocalPackageRepository.FindPackage(Func`2 openPackage, String packageId, SemanticVersion version)
   at NuGet.LocalPackageRepository.FindPackage(String packageId, SemanticVersion version)
   at NuGet.PackageRepositoryExtensions.FindPackage(IPackageRepository repository, String packageId, SemanticVersion version, IPackageConstraintProvider constraintProvider, Boolean allowPrereleaseVersions, Boolean allowUnlisted)
   at NuGet.Protocol.Core.v2.DownloadResourceV2.DownloadToMachineCache(IPackageCacheRepository cacheRepository, PackageIdentity package, DataServicePackageRepository repository, Uri downloadUri, CancellationToken token)
   at NuGet.Protocol.Core.v2.DownloadResourceV2.DownloadFromUrl(SourcePackageDependencyInfo package, DataServicePackageRepository repository, CancellationToken token)
   --- End of inner exception stack trace ---
   at NuGet.Protocol.Core.v2.DownloadResourceV2.DownloadFromUrl(SourcePackageDependencyInfo package, DataServicePackageRepository repository, CancellationToken token)
   at NuGet.Protocol.Core.v2.DownloadResourceV2.<>c__DisplayClass3_0.<GetDownloadResourceResultAsync>b__0()
   --- End of inner exception stack trace ---
   at NuGet.Protocol.Core.v2.DownloadResourceV2.<>c__DisplayClass3_0.<GetDownloadResourceResultAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========

**Comment by jbogard** [comment]
You probably have an old NuGet version.

**Comment by jrandecker** [comment]
That was the problem.  Thanks.
