### ISSUE TITLE
Dictionary mappings no longer handle non-empty dictionary destinations in 5.1.1

### ISSUE THREAD

**Issue by tillig** [AutoMapper/AutoMapper#1645]
Two objects have dictionary properties. When a source object is mapped onto a destination object, the dictionary values should be replaced. Unfortunately, it seems that `Insert` is being called on the destination object dictionary without clearing it first, which results in an exception. That's (apparently) how the 4.x codeline works; maybe this is just a breaking change in 5.x?

Repro:

```csharp
public class Source
{
  public IDictionary<string, string> Values { get; private set; } = new Dictionary<string, string>();
}

public class Destination
{
  public IDictionary<string, object> Values { get; private set; } = new Dictionary<string, object>();
}

[Fact]
public void DictionaryTest()
{
  var source = new Source();
  source.Values["first"] = "1";
  source.Values["second"] = "2";

  var dest = new Destination();
  dest.Values["first"] = "one";

  var mapper = new MapperConfiguration(cfg => cfg.CreateMap<Source, Destination>()).CreateMapper();
  mapper.Map(source, dest);

  Assert.Equal("1", dest.Values["first"]);
  Assert.Equal("2", dest.Values["second"]);
}
```

The `mapper.Map` line fails in 5.1.1 with "An item with the same key has already been added." That's because the "first" key already exists in the destination dictionary, which should be cleared(?) first.

I've found a workaround by making a generic merging dictionary mapper...

```csharp
public class DictionaryConverter<TSourceKey, TSourceValue, TDestKey, TDestValue> :
  ITypeConverter<IDictionary<TSourceKey, TSourceValue>, IDictionary<TDestKey, TDestValue>>
{
  public IDictionary<TDestKey, TDestValue> Convert(IDictionary<TSourceKey, TSourceValue> source, IDictionary<TDestKey, TDestValue> destination, ResolutionContext context)
  {
    if (source == null)
    {
      return null;
    }

    var valuesToMerge = new Dictionary<TDestKey, TDestValue>();
    foreach (var sourceKey in source.Keys)
    {
      var destKey = context.Mapper.Map<TDestKey>(sourceKey);
      var destValue = context.Mapper.Map<TDestValue>(source[sourceKey]);
      valuesToMerge[destKey] = destValue;
    }

    if (destination != null)
    {
      destination.Clear();
    }

    return valuesToMerge;
  }
}
```

I can then register it as an open generic:

```csharp
var mapper = new MapperConfiguration(cfg =>
{
  cfg.CreateMap(typeof(IDictionary<,>), typeof(IDictionary<,>))
     .ConvertUsing(typeof(MergingDictionaryConverter<,,,>));
  cfg.CreateMap<Source, Destination>();
}).CreateMapper();
```

But doing this sort of hoop-jumping makes me feel like I'm missing something obvious. Maybe I was just taking advantage of an inadvertent/incorrect behavior before? Or am I actually missing something? (Or is this a bug?)

**Comment by TylerCarlson1** [comment]
In 5.x there was a conversion to mappings to expressions.  In this conversion the path of dictionary mapping was changed to work like a collection of KeyValuePairs, so that the logic could be shared with the other collection type mappings, which there are several.  In 4.x each type based on collection had their own unique code base to do the mappings.

There is suppose to be a clear call but maybe for some reason it isn't working.  If you try to MyGet build it might work correctly.  Maybe setting UseDestinationValue=true might work as well.

As far as I know there shouldn't be any type of merging of data.  Usually what happens is makes a new object of type or clears out existing list then adds new items in.  It shouldn't merge values, but this looks like a bug.

**Comment by tillig** [comment]
OK, working through this a bit more I think the bug is that if the source dictionary has a key _and_ the destination dictionary has that same key then the destination should allow the source to overwrite it. Instead I'm getting the "key exists" error, which is wrong.

I'm going to update the initial post above to help disambiguate what's going on.

**Comment by tillig** [comment]
Updated to be more accurate. Thanks for the hint, @TylerCarlson1.

**Comment by lbargaoanu** [comment]
Duplicate of #1630. The issue can be closed.

**Comment by tillig** [comment]
Oh, yep, looks like it.

**Comment by sandrock** [comment]
I still encounter the bug with 5.1.1. The workaround does not work for me.

Here is some context. The unit test is not relevant but it shows the error.

```
class Knowledge
{
    public Dictionary<string, KnowledgeFeature> Features { get; set; }
}

class KnowledgeModel
{
    public IDictionary<string, KnowledgeFeatureModel> Features { get; set; }
}

public Knowledge ToEntity(KnowledgeModel model, Knowledge entity)
{
    return mapper.Map<KnowledgeModel, Knowledge>(model, entity);
}

[TestMethod]
public void OverwriteByNull()
{
    // verify that properties are set to null when mapped back (to null) into the original entity (where it's not null)

    // the data layer gets the entity and returns a domain object
    Knowledge entity0 = GetKnowledgeEntity(); // returns a knowledge with 1 feature
    var target = new ModelAutoMapper();
    KnowledgeModel model0 = target.ToModel(entity0);

    // the domain layer changes a property to null
    model0.Contact.FirstName = null;

    // the data layer is in charge of getting the original object and setting the changed values
    Knowledge entity1 = target.ToEntity(model0, entity0); // this is the DAL operation // CRASH
    Assert.IsNull(entity1.Contact.FirstName);
}
```

No workaround:

```
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
KnowledgeModel -> Knowledge

Type Map configuration:
KnowledgeModel -> Knowledge

Property:
Features ---> System.ArgumentException: An item with the same key has already been added.
Result StackTrace:	
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.Add(KeyValuePair`2 keyValuePair)
   at lambda_method(Closure , KnowledgeModel , Knowledge , ResolutionContext )
 --- End of inner exception stack trace ---
    at lambda_method(Closure , KnowledgeModel , Knowledge , ResolutionContext )
   at ModelAutoMapper.ToEntity(KnowledgeModel model, Knowledge entity) in ModelAutoMapper.cs:line 35
   at KnowledgesRepositoryTests.OverwriteByNull() in KnowledgesRepositoryTests.cs:line 87
```

With workaround:

```
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
KnowledgeModel -> Knowledge

Type Map configuration:
KnowledgeModel -> Knowledge

Property:
Features ---> System.InvalidCastException: Unable to cast object of type 'DictionaryConverter`4[KnowledgeFeatureModel,System.String,KnowledgeFeature]' to type 'AutoMapper.ITypeConverter`2[System.Collections.Generic.IDictionary`2[System.String,KnowledgeFeatureModel],System.Collections.Generic.Dictionary`2[System.String,KnowledgeFeature]]'.
Result StackTrace:	
at lambda_method(Closure , KnowledgeModel , Knowledge , ResolutionContext )
 --- End of inner exception stack trace ---
    at lambda_method(Closure , KnowledgeModel , Knowledge , ResolutionContext )
   at ModelAutoMapper.ToEntity(KnowledgeModel model, Knowledge entity) in ModelAutoMapper.cs:line 35
   at KnowledgesRepositoryTests.OverwriteByNull() in KnowledgesRepositoryTests.cs:line 94
```

Reverting to AutoMapper 4.2.1 is our temporary solution.
