### ISSUE TITLE
ArgumentException when mapping NULL navigation property in EF7 with ProjectTo<T>

### ISSUE THREAD

**Issue by ajbeaven** [AutoMapper/AutoMapper#1670]
I'm having issues with mapping NULL navigation properties EF7. I think it's specifically related to something that EF is doing as the following code works fine if I manually create a list in memory.

```
public class Foo
{
    [Key]
    public int Id { get; set; }
    public Bar Bar { get; set; }
}

public class Bar
{
    [Key]
    public int Id { get; set; }
}


public class FooDto
{
    public int Id { get; set; }
    public BarDto Bar { get; set; }
}

public class BarDto
{
    public int Id { get; set; }
}

public class TestDbContext : DbContext
{
    public DbSet<Foo> Foos { get; set; }
    public DbSet<Bar> Bars { get; set; }

    public TestDbContext(DbContextOptions<TestDbContext> options)
        : base(options)
    {
    }
}

public class Program
{
    public static void Main()
    {
        // init automapper
        Mapper.Initialize(cfg =>
        {
            cfg.CreateMap<Bar, BarDto>();
            cfg.CreateMap<Foo, FooDto>();
        });

        // create database
        var optionsBuilder = new DbContextOptionsBuilder<TestDbContext>();
        optionsBuilder.UseInMemoryDatabase("TestDb");

        using (var context = new TestDbContext(optionsBuilder.Options))
        {
            context.Foos.Add(new Foo());

            context.SaveChanges();

            var loadedLines = context.Foos.Include(f => f.Bar).ToList().AsQueryable();

            var works = loadedLines.ProjectTo<FooDto>().ToList();
            var doesntWork = context.Foos.Include(f => f.Bar).ProjectTo<FooDto>().ToList();
        }
    }
}
```

The test uses the following nuget packages:
**Microsoft.EntityFrameworkCore**
**Microsoft.EntityFrameworkCore.InMemory**

---

_Error_
ArgumentException: Argument types do not match

_Stacktrace_

```
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at System.Linq.Expressions.MemberAssignment.Update(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
```

**Comment by lbargaoanu** [comment]
Test it with EF6. If it behaves the same way, we can fix it. EF7 needs more time.

**Comment by ajbeaven** [comment]
Works fine in EF6. 

You suspect this is a bug in EF7? [This issue](https://github.com/aspnet/EntityFramework/issues/4589) refers to adding support for optional navigations but it seems to have been fixed a few months ago.

**Comment by lbargaoanu** [comment]
It might be, being an EF stack and all.

**Comment by ericvb** [comment]
This problem is indeed corrected in future builds of EF7 or lets talk now about EF Core.
Take a nightly build on https://dotnet.myget.org/gallery/aspnetcore-ci-dev and retest it.
