### ISSUE TITLE
[EntityFrameworkCore] Exception when mapping from EF entity and using Include 

### ISSUE THREAD

**Issue by DavizOWNS** [AutoMapper/AutoMapper#1698]
I have config like this

```
var config = new MapperConfiguration(cfg =>
{
    ...
    cfg.CreateMap<Models.DB.Product, Models.API.ProductDto>()
                     .ForMember(x => x.Rooms, opts => opts.MapFrom(prod => prod.ProductRooms.Select(r => r.RoomID)));
});
```

and when i try to map like this

` _context.Products.AsNoTracking().Include(x => x.ProductRooms).ProjectTo<ProductDto>(_mapper.ConfigurationProvider).ToList();`

or like this

` _context.Products.AsNoTracking().Include(x => x.ProductRooms).UseAsDataSource(_mapper).For<ProductDto>().ToList();`

I get exception 
```
AutoMapper.AutoMapperMappingException: Unable to create a map expression from ProductRooms.RoomID (System.Collections.Generic.IEnumerable`1[System.Int32]) to ProductDto.Rooms (System.Collections.Generic.List`1[System.Int32])

Mapping types:
Product -> ProductDto
ProductsAPI.Models.DB.Product -> ProductsAPI.Models.API.ProductDto

Type Map configuration:
Product -> ProductDto
ProductsAPI.Models.DB.Product -> ProductsAPI.Models.API.ProductDto

Property:
Rooms
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, ConcurrentDictionary`2 typePairCount)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Expression`1[] membersToExpand)
   at ProductsAPI.DAL.ProductRepository.Get() in D:\VisualStudioWorkspace\ProductsAPI\src\ProductsAPI\DAL\ProductRepository.cs:line 27
   at ProductsAPI.Controllers.ProductsController.Get() in D:\VisualStudioWorkspace\ProductsAPI\src\ProductsAPI\Controllers\ProductsController.cs:line 29
   at lambda_method(Closure , Object , Object[] )
```

But this works
```
var prods = _context.Products.AsNoTracking().Include(x => x.ProductRooms).ToList();
return _mapper.Map<List<Product>, List<ProductDto>>(prods);
```

**Comment by lbargaoanu** [comment]
Try ExplicitExpansion instead of Include.

**Comment by DavizOWNS** [comment]
What is ExplicitExpansion ? Can you give me example ?

**Comment by jbogard** [comment]
Both AsNoTracking and Include are not needed. EF figures out what to include or not based on the Select expression AutoMapper creates. Finally, do a ToList inside your MapFrom. The destination type is a List and you're just trying to map an enumerable. Those don't match.

**Comment by DavizOWNS** [comment]
Thanks. Totally forgot about .ToList. It works now.
