### ISSUE TITLE
Expression of type 'System.Object' cannot be used for assignment to type 'System.String'

### ISSUE THREAD

**Issue by adam-resdiary** [AutoMapper/AutoMapper#1770]
I'm having a problem when upgrading from AutoMapper version 3.2.1 to 5.1.1 on a mapping that maps between an ISet<string> to a THashSet<string> object.

We use thrift in our project, and unfortunately the current version we're using doesn't have support for the built in ISet<T>. Because of that we've got a custom mapping that maps between an ISet<T> and a THashSet<T>.

When we do this, it's causing the following exception when configuring the mapper:

```
System.ArgumentException : Expression of type 'System.Object' cannot be used for assignment to type 'System.String'
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at AutoMapper.ExpressionExtensions.ForEach(Expression collection, ParameterExpression loopVar, Expression loopContent)
   at AutoMapper.Mappers.CollectionMapperExtensions.MapCollectionExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression, Func`2 conditionalExpression, Type ifInterfaceType, MapItem mapItem)
   at AutoMapper.Mappers.CollectionMapper.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Execution.TypeMapPlanBuilder.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, TypePair typePair, Expression sourceParameter, Expression contextParameter, PropertyMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.MapExpression(TypePair typePair, Expression sourceParameter, PropertyMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal(IConfiguration configuration)
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at RD.Api.Tests.Unit.Infrastructure.AutoMapperTests.TestAllMappingConfigurationsAreValid() in C:\Users\AdamConnelly\github.com\adam-resdiary\ResDiary-API\Tests\RD.Api.Tests\Unit\Infrastructure\AutoMapperTests.cs:line 28
```

I've managed to narrow this down to the following code that seems to reproduce the issue:

```csharp
[TestFixture]
public class MapperTests
{
    [Test]
    public void TestAllMappingConfigurationsAreValid()
    {
        // Exception is thrown by the following line:
        var mapperConfig =
            new MapperConfiguration(
                cfg => cfg.CreateMap<MapFrom, MapTo>().ForMember(dst => dst.Set, o => o.MapFrom(src => MapSet(src.Set))));
    }

    public class MapFrom
    {
        public ISet<string> Set { get; set; }
    }

    public class MapTo
    {
        public THashSet<string> Set { get; set; }
    }

    private static THashSet<string> MapSet(ISet<string> src)
    {
        return null;
    }
}
```

In our actual code we're using a Mapper.Initialize() call, but creating a new MapperConfiguration seems to recreate the issue.

I think I can work around this for now by switching to a customer TypeConverter, and using ConvertUsing, which is probably more correct for what we're trying to do anyway.

**Comment by TylerCarlson1** [comment]
What does THashSet class look like?  Does it inherit from `IEnumerable` or `IEnumerable<T>`

**Comment by lbargaoanu** [comment]
Try the MyGet build.

**Comment by adam-resdiary** [comment]
@TylerCarlson1 Here it is: https://github.com/apache/thrift/blob/master/lib/csharp/src/Collections/THashSet.cs

@lbargaoanu what's the difference between the NuGet and the MyGet build? Is the MyGet build a prerelease version or something?

**Comment by jbogard** [comment]
MyGet is the master branch. NuGet is where I put a tag on one of the master
branch commits. That's the sole difference.

**Comment by adam-resdiary** [comment]
Ok - so I've tried the MyGet version, and it seems to have been fixed, so I think this issue can be closed. Any idea when the fix will be released?

I'm also experiencing https://github.com/AutoMapper/AutoMapper/issues/1764, and I've had to work around it by using an AfterMap for the one place I've found it happening so far. It makes me slightly nervous though that there could be other places where we don't have test coverage that are now broken. 

Long story short - any idea if that issue is also resolved in the MyGet build?

Also, I get that you guys are busy, and probably don't have time to check up on every single issue that gets raised, but saying "Try the MyGet build" is a bit off putting. I'm personally not used to using MyGet, so it wasn't totally obvious to me that I should do that before reporting an issue, and how to go about doing it.

Is it worth adding something to the main README explaining the relationship between the NuGet and MyGet packages, asking folk to try the MyGet build before reporting an issue, and giving a quick explanation of how to do that? I can write something up and put up a PR if you want - I just don't really know how your development and release process works enough that I might not be able to describe it that well.

**Comment by lbargaoanu** [comment]
I think we could link from the ReadMe to a page from the wiki.

**Comment by adam-resdiary** [comment]
Sounds good. Cheers!

**Comment by lbargaoanu** [comment]
:) What I mean is that page doesn't exist and if you want to write it, you're welcome to do so.

**Comment by adam-resdiary** [comment]
haha - I was wondering about that. Ok, I'll try to put something together.

**Comment by adam-resdiary** [comment]
@lbargaoanu Before I just go ahead and create a page on the wiki, does the following sound ok? If you're ok with it I'll add the page. I take it there's no way to do a PR for wiki pages?

AutoMapper uses MyGet to publish development builds based on the master branch. This means that the MyGet build sometimes contains fixes that are not available in the current NuGet package. Please try the latest MyGet build before reporting issues, in case your issue has already been fixed but not released.

The AutoMapper MyGet gallery is available at http://myget.org/gallery/automapperdev.

# Installing the Package
If you want to install the latest MyGet package into a project, you can use the following command:

```
Install-Package AutoMapper -Version 5.2.0-alpha-01235 -Source https://www.myget.org/F/automapperdev/api/v3/index.json
```

`5.2.0-alpha-01235` should be replaced with the version number of the latest package, which can be found on the MyGet gallery.

**Comment by lbargaoanu** [comment]
Sounds good to me :) You should be able to simply add a wiki page, no PR needed.

**Comment by adam-resdiary** [comment]
Yeah - I just didn't want to put a load of misinformation on it.

**Comment by lbargaoanu** [comment]
Updated the page to exclude the version. Presumably you usually want the latest version.

**Comment by adam-resdiary** [comment]
Yes - that's correct. I just wasn't thinking straight.

**Comment by lbargaoanu** [comment]
No worries. It should be useful.
