### ISSUE TITLE
Property '...' is not defined for type '...'

### ISSUE THREAD

**Issue by jwwelbor** [AutoMapper/AutoMapper#1776]
I'm upgrading from a working version 3 to 5 with a ridiculous number of maps defined, so I won't bother to post them here.

I've moved my staticy configs into profiles, and then included them like this.

```
public static MapperConfiguration Configure()
        {
            var mappings = new MapperConfiguration(config =>
            {
                config.AddProfile<MapperConfigDomain>();
                config.AddProfile<MapperConfigModels>();
                config.AddProfile<MapperConfigDTO>();
                config.AddProfile<MapperConfigExternalServices>();
            });


            return mappings;
        }
```
Then moved all of the random CreateMap calls that had been leaked all over into the expected locations.

I'm finally in a compiling state.

But when I try to load the configuration to run a unit test I get

 **{"Property _xxx_ is not defined for type _yyy_"}**

Now, the problem is, that it absolutely exists.  At first I thought it was because of a nullable type, but then I completely commented that out as a test and it went on to complain about a bool.  

The properties are named exactly the same and are there across all objects.  Have any of you encountered this?  It does seem like maybe it has something to do with mappings from an interface to a concrete?

Did something change with how this works?

For example..
```
            CreateMap<ApplicationVehicleModel, ApplicationVehicle>().ReverseMap();


            CreateMap<IApplicationVehicleModel, ApplicationVehicle>()
                    .ForMember(dest => dest.Id, opt => opt.Ignore()).ReverseMap();


            CreateMap<ApplicationVehicleModel, VehicleViewModel>().ReverseMap();


            CreateMap<ApplicationVehicle, VehicleViewModel>().ReverseMap();


            CreateMap<IVehicleModel, Vehicle>()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.ClientId, opt => opt.Condition(x => x.ClientId > 0))
            .ReverseMap()
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.ClientId, opt => opt.Condition(x => x.ClientId > 0));
```

When MapperConfiguration returns I get the following error

**{"Property 'Boolean IsExotic' is not defined for type 'Web.Models.VehicleViewModel'"}**

```
public class ApplicationVehicleModel : VehicleViewModel, IApplicationHeaderModel, IApplicationVehicleModel

public class VehicleViewModel {
     public bool IsExotic { get; set; }
     ...
}

public class ApplicationVehicle {
     public bool IsExotic { get; set; }
     ...
}

public interface IVehicleModel{
     bool IsExotic { get; set; }
     ...
}

public class Vehicle {
     public bool IsExotic { get; set; }

}
```

Any suggestions?  Could it be related to inheritance? Or due to mapping from an interface to an unrelated concrete?

**Comment by jwwelbor** [comment]
Please stand by... I may have figured something out.

**Comment by lbargaoanu** [comment]
Stacktrace?

**Comment by jbogard** [comment]
Yes can you post your full exception?

**Comment by mikehachen** [comment]
Hi there

I have exactly the same problem... Here is the full exception:
`System.ArgumentException occurred
  HResult=0x80070057
  Message=Property 'ProIT.ComaticWebApi.Contract.Accounts.AccountCostCenter AccountCostCenter' is not defined for type 'ProIT.ComaticWebApi.Web.Api.Models.Account'
  Source=AutoMapper
  StackTrace:
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal(IConfiguration configuration)
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at ProIT.ComaticWebApi.Web.Api.NinjectConfigurator.ConfigureAutoMapper(IKernel container) in C:\WS\ProITAG\Comatic.WebApi\Dev\Dev-Branch\src\ProIT.ComaticWebApi.Web.Api\App_Start\NinjectConfigurator.cs:line 170
   at ProIT.ComaticWebApi.Web.Api.NinjectConfigurator.AddBindings(IKernel container) in C:\WS\ProITAG\Comatic.WebApi\Dev\Dev-Branch\src\ProIT.ComaticWebApi.Web.Api\App_Start\NinjectConfigurator.cs:line 54
   at ProIT.ComaticWebApi.Web.Api.NinjectConfigurator.Configure(IKernel container) in C:\WS\ProITAG\Comatic.WebApi\Dev\Dev-Branch\src\ProIT.ComaticWebApi.Web.Api\App_Start\NinjectConfigurator.cs:line 46
   at ProIT.ComaticWebApi.Web.Api.NinjectWebCommon.RegisterServices(IKernel kernel) in C:\WS\ProITAG\Comatic.WebApi\Dev\Dev-Branch\src\ProIT.ComaticWebApi.Web.Api\App_Start\NinjectWebCommon.cs:line 75
   at ProIT.ComaticWebApi.Web.Api.NinjectWebCommon.CreateKernel() in C:\WS\ProITAG\Comatic.WebApi\Dev\Dev-Branch\src\ProIT.ComaticWebApi.Web.Api\App_Start\NinjectWebCommon.cs:line 64
   at ProIT.ComaticWebApi.Web.Api.NinjectWebCommon.<>c__DisplayClass1_0.<Start>b__0() in C:\WS\ProITAG\Comatic.WebApi\Dev\Dev-Branch\src\ProIT.ComaticWebApi.Web.Api\App_Start\NinjectWebCommon.cs:line 31
   at Ninject.Web.Common.Bootstrapper.Initialize(Func`1 createKernelCallback)
   at ProIT.ComaticWebApi.Web.Api.NinjectWebCommon.Start() in C:\WS\ProITAG\Comatic.WebApi\Dev\Dev-Branch\src\ProIT.ComaticWebApi.Web.Api\App_Start\NinjectWebCommon.cs:line 29`

I upgraded from 4.1 to 5.1... Everything worked fine with version 4.1.

Thanks, Mike

**Comment by lbargaoanu** [comment]
Yes, it seems to be a problem, but we need a repro. Make a gist that we can execute and see fail.

**Comment by mikehachen** [comment]
As requested attachted two sample solutions. WebApplication_Working_AM421.zip is a working solution with AutoMapper 4.2.1. WebApplication_Crashing_AM511.zip is the same application but AutoMapper was updated to the latest version.
[WebApplication_Crashing_AM511.zip](https://github.com/AutoMapper/AutoMapper/files/595086/WebApplication_Crashing_AM511.zip)
[WebApplication_Working_AM421.zip](https://github.com/AutoMapper/AutoMapper/files/595085/WebApplication_Working_AM421.zip)

**Comment by lbargaoanu** [comment]
The message is weird, but the cause is clear enough

    CreateMap<IAccount, WebApplication.Data.Account>().As<Account>();

You can't do that. Those types are unrelated. The other use of As is correct. Unless @jbogard says otherwise.

**Comment by jwwelbor** [comment]
Thanks for picking up the torch, mikehachen.

We had lots of problems with the As() usages as well.  In most cases we refactored to get rid of that requirement, but I don't understand why it was causing a problem in most cases.

**Comment by mikehachen** [comment]
Hey there

OK, so I'm doing it wrong... :( But why does it work in 4.2.1 but in 5.1.1 it doesn't work anymore? Or how can I create a map between IAccount and WebApplication.Data.Account? Account is a simple class with no Ignore or custom resolver. But I have others with quite a few settings.

Is there a simple solution which works with 5.1.1?

Thanks!

**Comment by lbargaoanu** [comment]
You can define a mapping to a base class or an interface and reuse it with Include or IncludeBase. Do a little research and report back if things are not clear :)

**Comment by mikehachen** [comment]
Thank you for your hint. To be honest things are not clear at all. I tried a little around and came up with the following: 
`CreateMap<IAccount, WebApplication.Data.Account>().Include<Account, WebApplication.Data.Account>();`

But: It even work's when I do not have this line of code in my profile... Obviously I don't need this mapping... Do I?? Sorry if I sound stupid but I'm pretty new to this "auto mapping thing"... :(

**Comment by lbargaoanu** [comment]
Maybe I've misunderstood. If everything works as you want when you remove the "As" I've pointed out, then there's no issue.

**Comment by lbargaoanu** [comment]
This can be closed.
