### ISSUE TITLE
InvalidOperationException when mapping IList to CollectionBase via ResolveUsing

### ISSUE THREAD

**Issue by sberezovskiy** [AutoMapper/AutoMapper#1905]
Create custom collection

```
    public class MyCollection : CollectionBase
    {
        public MyCollection(List<string> list)
        {
            foreach (var item in list)
                List.Add(item);
        }
    }
```

Source and destination classes:

```
    public class SourceItem
    {
        public string Name { get; set; }
        public List<string> ShipsTo { get; set; }
    }

    public class DestItem
    {
        public string Name { get; set; }
        public MyCollection ShipsTo { get; set; }
    }
```

Mapping:

```
    Mapper.Initialize(cfg =>
    {
        cfg.CreateMap<SourceItem, DestItem>()
            .ForMember(d => d.ShipsTo, o => o.ResolveUsing((s,d) => new MyCollection(s.ShipsTo)));
    });
```
Mapper crashes during initialization.
Stack trace:

```
Unhandled Exception: System.InvalidOperationException: No coercion operator is defined between types 'System.Collections.Generic.List`1[System.Object]' and 'FooNamespace.MyCollection'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at AutoMapper.ExpressionExtensions.ToType(Expression expression, Type type)
   at AutoMapper.Execution.TypeMapPlanBuilder.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, TypePair typePair, Expression sourceParameter, Expression contextParameter, PropertyMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression, IEnumerable`1 mappers)
   at AutoMapper.Mapper.Initialize(Action`1 config)
```

**Comment by jbogard** [comment]
This is a bug, but I think you're better off using a type converter here:

```
cfg.CreateMap<List<string>, MyCollection>().ConvertUsing(src => new MyCollection(src));
```

**Comment by lbargaoanu** [comment]
I don't see a one line fix. This is an older collection, that doesn't support the generic ICollection. Probably this use case was dropped when we switched to expressions. I propose to not support this case until someone writes a mapper for it. It seems easy to work around it.
