### ISSUE TITLE
ProjectTo in Queryable throws exception

### ISSUE THREAD

**Issue by Allann** [AutoMapper/AutoMapper#1928]
I have created a .NET Core webapi that tries to separate the Domain model used by the ORM from the Models presented to the controller and therefore the user of the API.  This works well for single models, but fails when attempting to return IQueryable.  I am unable to return an enumerable because in the real database there are many hundreds of thousand records.
Here is the exception:
```
System.Exception: Can't resolve this to Queryable Expression
   at AutoMapper.QueryableExtensions.ExpressionBuilder.ResolveExpression(PropertyMap propertyMap, Type currentType, Expression instanceParameter)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, ConcurrentDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.<CreateMapExpression>b__5_0(ExpressionRequest tp)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)
   at TestContext.BusinessLogic.Countries.TestContext.Shared.IEntities<TestContext.BusinessLogic.Models.CountryModel>.GetAll() in D:\Dev\test\TestContext\BusinessLogic\Countries.cs:line 25
   at TestContext.Controllers.CountriesController.Get() in D:\Dev\test\TestContext\Controllers\CountryController.cs:line 21
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()

```

I have attached a zip file with a webapi server project in it that demonstrates the problem.  Run it, and once it's built the database (localdb, see connection string in appsettings), use postman or similar to execute http://localhost:8088/Countries.

[TestContext.zip](https://github.com/AutoMapper/AutoMapper/files/737479/TestContext.zip)

To see it working execute http://localhost:8088/Countries/AU.

Once I added the UrlResolver the error started.  However, I know the resolver works because I get a URL in the returned model.  I do not want the user to know the DB Id (Guid) instead using the business key as the surrogate key in the derived URL.

> dotnet --info
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
VS2015 Update 3

**Comment by lbargaoanu** [comment]
The projection code is executed by the query provider, so you cannot run just any code, only what the DB supports. Maybe passing parameters to ProjectTo would help.

**Comment by Allann** [comment]
So should I change the IQueryable to include a Select that does the mapping at that point instead?

**Comment by lbargaoanu** [comment]
It seems best to pass the needed parameters to ProjectTo. Any reason why that wouldn't work?

**Comment by Allann** [comment]
I have no idea how to make the UrlResolver a parameter that will work in the databse.  A URL is derived from the HttpContext Route name and a key,  There is no way to get that at the database level.  Or am I not understanding your response.

Can you change my attached project and show what you mean please?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/wiki/Queryable-Extensions#parameterization

**Comment by Allann** [comment]
There must be something I'm not getting here, as that was the page I read before raising this issue.

I already have the code 
```
CreateMap<Country, CountryModel>()
                .ForMember(c => c.Url, opt => opt.ResolveUsing<CountryUrlResolver>())
                .ReverseMap();
```
Which will inject the CountryUrlResolver into the mapping process.  A single place and works in most cases.  This is what broke the IQueryable.

But you are saying that I should change this to a MapFrom and pass this in everywhere I need to do mapping?  That's a lot of refactoring.  

I would now need to inject the resolvers into the repositories (Countries in the example code) and use them in the numerous places I am getting a country from the DbContext, not just the GetAll method.  Is that correct?

**Comment by lbargaoanu** [comment]
If you want to use the same map with ProjectTo _and_ Map, I don't think that would work in this case. Map uses parameters in a different way. I guess it's easier to use just Map everywhere. Of course that's not exactly optimal.

**Comment by lbargaoanu** [comment]
@jbogard How come is not possible to use the same map with parameters with Map and ProjectTo? Am I missing smth or people just use one or the other?
