### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by gtomolillo** [AutoMapper/AutoMapper#1929]
Hi,

I'm facing this issue using AutoMapper in an environment with a high number of parallel requests.

The stack trace is:

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
   at AutoMapper.Execution.TypeMapPlanBuilder.MapExpression(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider, TypePair typePair, Expression sourceParameter, Expression contextParameter, PropertyMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
   at AutoMapper.TypeMap.Seal(TypeMapRegistry typeMapRegistry, IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
   at AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.get_Value()
   at AutoMapper.MapperConfiguration.GetUntypedMapperFunc(MapRequest mapRequest)
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at AutoMapper.Mapper.Map[TDestination](Object source)
```

The configuration is very basic, I've just enabled `CreateMissingTypeMaps`

To fix the problem I needed to restart the application and the error disappeared, I think it might be an issue that appears only if two concurrent requests are coming when the mapping is still not created.

Is there any way to solve this at all?

**Comment by lbargaoanu** [comment]
Well, yes, you should avoid CreateMissingTypeMaps and simply create the maps you need. It's good for you :) Does the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build behave the same way?
