### ISSUE TITLE
OutOfMemoryException on a particular mapping

### ISSUE THREAD

**Issue by cryo75** [AutoMapper/AutoMapper#1999]
I've upgraded to the latest version from 4.2.1 and now I'm getting an OutOfMemoryException on a particular mapping. The stacktrace is:

```
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.MapperConfiguration.GetUntypedMapperFunc(MapRequest mapRequest)
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at AutoMapper.Mapper.Map[TDestination](Object source)
```

The class that's being automapped is:

```
    public class UserModel
    {
        public UserModel()
        {
            this.SomeList1 = new List<SomeClass1>();
            this.SomeList2 = new List<SomeClass2>();
        }

        public int Id { get; set; }
        public int SomeClass1Id { get; set; }
        public int? SomeClass3Id { get; set; }
        public string Name { get; set; }
        public string Login { get; set; }
        public bool IsActive { get; set; }

        public virtual SomeClass1 SomeClass1 { get; set; }
        public virtual SomeClass3 SomeClass3 { get; set; }
        public virtual ICollection<SomeClass1> SomeList1 { get; set; }
        public virtual ICollection<SomeClass2> SomeList2 { get; set; }
    }
```

The mapping is simple:

`    cfg.CreateMap<UserModel, UserDto>(MemberList.Destination).ReverseMap();`

All other classes have similar mappings.

I then load a user from the db into the model class, and to test, I'm doing the following:

```
    myUser.SomeList1 = null;
    myUser.SomeClass1 = null;
    myUser.SomeClass3 = null;
    myUser.SomeList2 = null;
    var u = Mapper.Map<UserDto>(myUser);
```

Now all reference properties are null. However the mapping is causing the exception above. I've also made sure I don't have circular references.

If I create an empty dto object, set all its value properties manually and automap its reference properties, it works fine.

So why to I get this exception when automapping the actual class?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/1693#issuecomment-270148644
In the MyGet build DontInline was renamed to MapAtRuntime.

**Comment by jbogard** [comment]
How many maps do you have? I've tested in configurations ranging in the 150-200 range without much problem.
