### ISSUE TITLE
ProjectTo fails when calling aggregate functions on includes

### ISSUE THREAD

**Issue by epohknarf** [AutoMapper/AutoMapper#2033]
Hi,

I get an exception in my mapping when calling aggregate functions.
Here is an example that fails: (id1 and id2 are foreign keys in the database)

    public static class MappingsForSomething
    {
        public static MapperConfigurationExpression ConfigureMappingsForSomething(this MapperConfigurationExpression configExpression)
        {
            configExpression.CreateMap<ParentClass, ParentClassDTO>()
                .ForMember(destination => destination.Id1, c => c.MapFrom(source => source.id1))
                .ForMember(destination => destination.Id2, c => c.MapFrom(source => source.id2))
                .ForMember(destination => destination.NumberOfChildren, c => c.MapFrom(source => source.Children.Count()));

            return configExpression;
        }
    }

    public class ParentClass
    {
        public string id1 { get; set; }
        public int id2 { get; set; }
        public ICollection<ChildClassDTO> Children { get; set; }
    }
	
    public class ChildClass
    {
        public string id1 { get; set; }
        public int id2 { get; set; }
        public int id3 { get; set; }
    }

    public class ParentClassDTO
    {
        public string Id1 { get; set; }
        public int Id2 { get; set; }
        public int NumberOfChildren { get; set; }
    }
	
    public class ChildClassDTO
    {
        public string Id1 { get; set; }
        public int Id2 { get; set; }
        public int Id3 { get; set; }
    }

Running against EFCore with the following code:

    var parentDTOs = await Context.Parents
	    .Include(p => p.Children)
        .ProjectTo<ParentClassDTO>(MapperConfiguration)
        .ToListAsync();

I get the following exception;

    System.InvalidOperationException occurred
    HResult=0x80131509
    Message=No value provided for required parameter '_outer_id1'.
    Source=Microsoft.EntityFrameworkCore.Relational
    StackTrace:
        at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
        at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__26.MoveNext()
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<BufferlessMoveNext>d__9.MoveNext()
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__6`2.MoveNext()
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable.AsyncEnumerator.<MoveNext>d__8.MoveNext()
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.<MoveNext>d__4.MoveNext()
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        at ALF.Storage.Repositories.Transfers.BankTransferHeapRepository.<GetHeaps>d__7.MoveNext() in C:\Users\hopeefra\Source\Repos\ALF\src\ALF.Storage\Repositories\Transfers\BankTransferHeapRepository.cs:line 27

If I exclude ProjectTo - it works fine

    var parentDTOs = await Context.Parents
	    .Include(p => p.Children)
        .Select(p => new ParentClassDTO() {
            Id1 = p.id1,
            Id2 = p.id2,
            NumberOfChildren = p.Children.Count()
        })
        .ToListAsync();

Also - if I map from the same models and not using aggregate functions - no error occurs.
	
    public static class MappingsForSomething
    {
        public static MapperConfigurationExpression ConfigureMappingsForSomething(this MapperConfigurationExpression configExpression)
        {
            configExpression.CreateMap<ParentClass, ParentClassDTO>()
                .ForMember(destination => destination.Id1, c => c.MapFrom(source => source.id1))
                .ForMember(destination => destination.Id2, c => c.MapFrom(source => source.id2))
                .ForMember(destination => destination.ChildrensId1s, c => c.MapFrom(source => source.Children.Select(child => child.id1));
        
            return configExpression;
        }
    }

    public class ParentClass
    {
        public string id1 { get; set; }
        public int id2 { get; set; }
        public ICollection<ChildClassDTO> Children { get; set; }
    }
	
	public class ChildClass
    {
        public string id1 { get; set; }
        public int id2 { get; set; }
        public int id3 { get; set; }
    }

    public class ParentClassDTO
    {
        public string Id1 { get; set; }
        public int Id2 { get; set; }
        public IEnumerable<string> ChildrensId1s { get; set; }
    }
	
	public class ChildClassDTO
    {
        public string Id1 { get; set; }
        public int Id2 { get; set; }
        public int Id3 { get; set; }
    }
	
NOTE: It also fails when calling First, FirstOrDefault..

I am currently using:

    AutoMapper 5.2.0
    Microsoft.EntityFrameworkCore 1.1.1

**Comment by lbargaoanu** [comment]
I see the same error without AM.
