### ISSUE TITLE
FileNotFoundException in MapperConfiguration Constructor

### ISSUE THREAD

**Issue by RichardAtRRD** [AutoMapper/AutoMapper#2051]
I receive the following error when constructing a MapperConfiguration object:

Message:
----------
Could not load file or assembly 'System.Collections.Specialized, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Call stack:
-----------
   at AutoMapper.Mappers.NameValueCollectionMapper.IsMatch(TypePair context)
   at AutoMapper.MapperConfiguration.<>c__DisplayClass54_0.<CoveredByObjectMap>b__0(IObjectMapper m)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.MapperConfiguration.CoveredByObjectMap(TypePair typePair)
   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
   at AutoMapper.Execution.TypeMapPlanBuilder.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, TypePair typePair, Expression sourceParameter, Expression contextParameter, PropertyMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   ...

I'm using .Net framework 4.6.1 and Automapper 6.0.2.0.

Many thanks,
Richard

**Comment by lbargaoanu** [comment]
Maybe you're referencing the .NET Core dll somehow. System.Collections.Specialized is just a namespace in System.dll in the full framework.

**Comment by RichardAtRRD** [comment]
I know. That's what's odd about it. My project does reference System.dll, of course. Perhaps the problem is occurring when trying to resolve something in the configuration expression.

**Comment by lbargaoanu** [comment]
We need repro steps. It seems you're the only one hitting this.

**Comment by RichardAtRRD** [comment]
I'm seeing the problem even with this very simple code:

using AutoMapper;

namespace MyNamespace
{
    public class MappingConfiguration : IMappingConfiguration
    {
        private IMapper _mapper;

        public MappingConfiguration()
        { }

        public MappingConfiguration(IConfigurationProvider config)
        {
            _mapper = config.CreateMapper();
        }

        public IConfigurationProvider GetConfiguration()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<MyClass1, MyClass2>();
            });

            config.AssertConfigurationIsValid();

            return config;
        }

        public TDest Map<TSource, TDest>(TSource source)
        {
            var result = _mapper.Map<TSource, TDest>(source);
            return result;
        }
    }

    public class MyClass1
    {
        public int Number { get; set; }
        public string Text { get; set; }
    }

    public class MyClass2
    {
        public int Number { get; set; }
        public string Text { get; set; }
    }
}

In my Unity bootstrapper, I call the MappingConfiguration like this:

            var mappingConfiguration = new MappingConfiguration();
            var mappingConfig = mappingConfiguration.GetConfiguration();
            this.container.RegisterInstance(mappingConfig);
            this.container.RegisterType<IMappingConfiguration, MappingConfiguration>();

The exception occurs when calling mappingConfiguration.GetConfiguration(), in the constructor of the MapperConfiguration object (see stack trace above).

Both the mapping project and the boostrapper project are using the same versions of .Net and Automapper.

**Comment by RichardAtRRD** [comment]
If I comment out the configuration expression then the error does not occur.

**Comment by lbargaoanu** [comment]
Obviously this kind of code works for everybody else :) So that doesn't help. It might have smth to do with your reference to AM.

**Comment by RichardAtRRD** [comment]
I have resolved the problem. I referenced a different version of Automapper.dll, in the net45 nuget package folder, rather than the one in the netstandard1.3 folder, even though both assemblies have the same file version.

**Comment by jbogard** [comment]
That's odd, i've never seen NuGet do this.

**Comment by RichardAtRRD** [comment]
I may have had to make the reference manually because I have to use an old version of NuGet which AutoMapper doesn't seem to work with properly.

**Comment by jbogard** [comment]
So.....upgrade NuGet?

**Comment by RichardAtRRD** [comment]
I have to use an old version because one of our internal packages fails with the latest version for some reason.
