### ISSUE TITLE
Mapping to readonly IEnumerable property

### ISSUE THREAD

**Issue by StevenDevooght** [AutoMapper/AutoMapper#2064]
When trying to map to a readonly IEnumerable property backed by an instance of an IList field AutoMapper throws a NullReferenceException.

### Source/destination types

```csharp
public class Source
{
    private readonly List<string> _myCollection = new List<string>
    {
        "one", "two"
    };

    public string[] MyCollection => _myCollection.ToArray();
}

public class Destination
{
    private IList<string> _myCollection = new List<string>();
    public IEnumerable<string> MyCollection => _myCollection;
}
```

### Mapping configuration

```csharp
CreateMap<Source, Destination>()
                .ForMember(m => m.MyCollection, opt =>
                {
                    opt.MapFrom(src => src.MyCollection);
                    opt.UseDestinationValue();
                });
```

### Expected behavior
The `UseDestinationValue` option should add items to the IList<> backing field. Changing the property to a `IList<string>` works as expected.

### Actual behavior
AutoMapper throws a `NullReferenceException`.

### Steps to reproduce

```csharp
var result = Mapper.Map<Destination>(new Source());
```

**Comment by lbargaoanu** [comment]
Try MapAtRuntime.

**Comment by StevenDevooght** [comment]
`MapAtRuntime` gives the following exception:

`System.ArgumentException occurred
  HResult=0x80070057
  Message=Method 'Int32 Add(System.Object)' declared on type 'System.Collections.IList' cannot be called with instance of type 'System.Collections.Generic.IEnumerable`1[System.String]'
  Source=System.Core
  StackTrace:
   at System.Linq.Expressions.Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
   at System.Linq.Expressions.Expression.ValidateStaticOrInstanceMethod(Expression instance, MethodInfo method)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression[] arguments)
   at AutoMapper.Mappers.CollectionMapperExtensions.MapCollectionExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression, Func`2 conditionalExpression, Type ifInterfaceType, MapItem mapItem) in D:\AutoMapper-6.0.2\src\AutoMapper\Mappers\CollectionMapperExtensions.cs:line 35
   at AutoMapper.Mappers.CollectionMapper.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression) in D:\AutoMapper-6.0.2\src\AutoMapper\Mappers\CollectionMapper.cs:line 12
   at AutoMapper.MapperConfiguration.GenerateObjectMapperExpression(MapRequest mapRequest, IObjectMapper mapperToUse, MapperConfiguration mapperConfiguration) in D:\AutoMapper-6.0.2\src\AutoMapper\MapperConfiguration.cs:line 151
   at AutoMapper.MapperConfiguration.BuildExecutionPlan(MapRequest mapRequest) in D:\AutoMapper-6.0.2\src\AutoMapper\MapperConfiguration.cs:line 108
   at AutoMapper.MapperConfiguration.CreateMapperFuncs(MapRequest mapRequest) in D:\AutoMapper-6.0.2\src\AutoMapper\MapperConfiguration.cs:line 92
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1() in D:\AutoMapper-6.0.2\src\AutoMapper\LockingConcurrentDictionary.cs:line 15
   at System.Lazy`1.CreateValue()
`

**Comment by lbargaoanu** [comment]
That's definitely a bug.
