### ISSUE TITLE
Expression of type 'Destination`1[System.Int32]' cannot be used for parameter of type 'System.Object''

### ISSUE THREAD

**Issue by tghanem** [AutoMapper/AutoMapper#2099]
### Source/destination types

```csharp
public struct Source<T>
{
    public T Value { get; set; }
}

public struct Destination<T>
{
    public T Value { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
{
    cfg.CreateMap(typeof(Destination<>), typeof(Source<>)).ConstructUsing(src => new Source<int>() { Value = 5 });
});
```

### Expected behavior

When i do:
```csharp
var destination = new Destination<int>() { Value = 5 };
var source = Mapper.Map(destination, typeof(Destination<int>), typeof(Source<int>));
```

I expect ```source ``` to contain the value 5.

### Actual behavior

However, i get:

```System.ArgumentException: 'Expression of type 'Destination`1[System.Int32]' cannot be used for parameter of type 'System.Object''```

At:
```
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.Invoke(Expression expression, IEnumerable`1 arguments)
   at AutoMapper.Internal.ExpressionFactory.ReplaceExpressionVisitor.Visit(Expression node)
   at AutoMapper.Internal.ExpressionFactory.Replace(Expression exp, Expression old, Expression replace)
   at AutoMapper.Internal.ExpressionFactory.ReplaceParameters(LambdaExpression exp, Expression[] replace)
   at AutoMapper.ExpressionExtensions.ReplaceParameters(LambdaExpression exp, Expression[] replace)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateNewDestinationFunc(Boolean& constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateDestinationFunc(Boolean& constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.FindClosedGenericTypeMapFor(TypePair typePair, TypePair requestedTypes)
   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
```

**Comment by lbargaoanu** [comment]
That ConstructUsing doesn't look good. Does it work without it?

**Comment by tghanem** [comment]
It does work without it. However, i need to be able to customize the construction of the ```Source<T>``` type.

**Comment by lbargaoanu** [comment]
Then you have to do it in a generic way.

**Comment by tghanem** [comment]
How?

**Comment by lbargaoanu** [comment]
:) That's your problem to solve. There is nothing wrong in AM. You have the source, get the type, Activator.CreateInstance etc.
