### ISSUE TITLE
Nullable properties mapping failure

### ISSUE THREAD

**Issue by yohny** [AutoMapper/AutoMapper#2123]
### Source/destination types

```csharp
// source
public class MyClass
{
  public DateTimeOffset? MyProp { get; set; }
}

// destination
public class MyDto
{
  public DateTime? MyProp { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
{
  cfg.CreateMap<MyClass, MyDto>();
  cfg.CreateMap<DateTimeOffset, DateTime>().ConvertUsing(datetimeoffset => datetimeoffset.DateTime);
});
```

### Expected behavior

Mapper.AssertConfigurationIsValid(); does not complain, so I would expect that mapping from/to `Nullable<>` versions of configured types would work (if those properties are not nullable, it works).

### Actual behavior

following exception is thrown:

```
AutoMapper.AutoMapperMappingException was unhandled
  HResult=-2146233088
  Message=Error mapping types.

Mapping types:
MyClass -> MyDto
AutomapperSamples.Program+MyClass -> AutomapperSamples.Program+MyDto

Type Map configuration:
MyClass -> MyDto
AutomapperSamples.Program+MyClass -> AutomapperSamples.Program+MyDto

Property:
MyProp
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , Object , Object , ResolutionContext )
       at AutomapperSamples.Program.Main(String[] args) in c:\users\nej\documents\visual studio 2015\Projects\AutomapperSamples\AutomapperSamples\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233088
       Message=Missing type map configuration or unsupported mapping.

Mapping types:
DateTimeOffset -> Nullable`1
System.DateTimeOffset -> System.Nullable`1[[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
       Source=Anonymously Hosted DynamicMethods Assembly
       StackTrace:
            at lambda_method(Closure , DateTimeOffset , Nullable`1 , ResolutionContext )
            at lambda_method(Closure , Object , Object , ResolutionContext )
       InnerException: 
```

### Steps to reproduce

```csharp
Mapper.AssertConfigurationIsValid();  // passes

var myClass = new MyClass { MyProp = DateTimeOffset.Now};
var dto = Mapper.Map<MyDto>(myClass); // exception twrown
```

I'm positive that this used to work in old version of Automapper (3.3.1 to be exact)

**Comment by lbargaoanu** [comment]
Now it complains :) Try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build. So now you need:

    cfg.CreateMap<DateTimeOffset, DateTime?>();

**Comment by yohny** [comment]
confirming that `AutoMapper 6.1.0-ci-01328` is throving exception now on `Mapper.AssertConfigurationIsValid()`, but is this necessary?
If we have a mapping configured between `T` and `U`, why do we need to explicitly configure also mapping for their `Nullable<>` versions? we don't need to explicitly define mapping for `int -> int?`
I see only 4 cases here:
`T` -> `U` => this is normal case, use map T->U
`T` -> `U?`=> always safe, use map T->U
`T?` -> `U?` =>  safe, If T null destination is also null, otherwise use map T->U
`T?` -> `U` => can be dangerous (if T is null), complain in AssertConfigurationIsValid()

I see in #1987 that there was some attempt to consolidate this

**Comment by lbargaoanu** [comment]
A PR is welcome.

**Comment by monaFarshidi** [comment]
Hi every one
I have a strange problem in my web App. I used Mapper for mapped class to each other, But sometimes I get a error and after IIS stop and start every thing work fine.
this happens cause of GetVersionID that refers to primary key in GetVersion property that is NotNull.
 I use code like that :
      Mapper.CreateMap<GetVersion, JsonVersion>();

Can somebody help me ????
