### ISSUE TITLE
NotSupportedException exception with EF unmapped members

### ISSUE THREAD

**Issue by FilipFilipov** [AutoMapper/AutoMapper#2155]
### Source/destination types
Source
```csharp
public partial class Ticket : EntityBase
    {
        public Ticket()
        {
    		this.TicketReactions = new HashSet<TicketReaction>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public bool IsDeleted { get; set; }
        public string Subject { get; set; }
        public string Status { get; set; }
        public bool IsPublic { get; set; }
        public string JiraKey { get; set; }
        public string IssueType { get; set; }

        public virtual ICollection<TicketReaction> TicketReactions { get; set; }
    }

public partial class TicketReaction : EntityBase
    {   
        public System.Guid TicketId { get; set; }
        public string ExternalReactionId { get; set; }
        public string UserName { get; set; }
        public string Text { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }

public class EntityBase
    {
        protected List<String> _columnsToIgnore = new List<string>();
        public virtual List<String> ColumnsToIgnore {
            get { return _columnsToIgnore; }
        }

        protected EntityBase()
        {
            _columnsToIgnore = new List<string> { "_columnsToIgnore", "ColumnsToIgnore", "Id", "Created", "Modified" };
        }
    }
```

Destination
```csharp
public class TicketViewModel
    {
        public Guid Id { get; set; }
        public string JiraKey { get; set; }
        public string Subject { get; set; }
        public string Status { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public string IssueType { get; set; }
        public TicketReactionViewModel LastReaction { get; set; }
    }

public class TicketReactionViewModel
    {
        public string UserName { get; set; }
        public DateTime Modified { get; set; }
    }
```

### Mapping configuration

```csharp
CreateMap<Ticket, TicketViewModel>()
  .ForMember(dest => dest.LastReaction, opt => opt.MapFrom(src => src.TicketReactions.FirstOrDefault()));

CreateMap<TicketReaction, TicketReactionViewModel>();
```

### Expected behavior

Under version 6.0.2 this mapping should produce an Expression like this when used with ProjectTo
```csharp
System.Data.Entity.Core.Objects.ObjectQuery`1[MarketingDb.Domain.EntityFramework.Model.Entities.Ticket]
	.MergeAs(MergeOption.AppendOnly)
	.Select(
        dto => new TicketViewModel
        {
            Id = dto.Id,
            JiraKey = dto.JiraKey,
            Subject = dto.Subject,
            Status = dto.Status,
            Created = dto.Created,
            Modified = dto.Modified,
            IssueType = dto.IssueType,
            LastReaction = (dto.TicketReactions.FirstOrDefault() != null)
                ? new TicketReactionViewModel
                {
                    UserName = dto.TicketReactions.FirstOrDefault().UserName,
                    Modified = dto.TicketReactions.FirstOrDefault().Modified
                }
                : null
        })
```

### Actual behavior

In 6.1.0 it will instead produce an expression like this
```csharp
System.Data.Entity.Core.Objects.ObjectQuery`1[MarketingDb.Domain.EntityFramework.Model.Entities.Ticket]
    .MergeAs(MergeOption.AppendOnly)
    .Select(
        dto => new 0_Culture=neutral_PublicKeyToken=null>
        {
            TicketReactions = dto.TicketReactions,
            IssueType = dto.IssueType,
            JiraKey = dto.JiraKey,
            IsPublic = dto.IsPublic,
            Status = dto.Status,
            Subject = dto.Subject,
            IsDeleted = dto.IsDeleted,
            Modified = dto.Modified,
            Created = dto.Created,
            Id = dto.Id,
            ColumnsToIgnore = dto.ColumnsToIgnore,
            LastReaction = dto.TicketReactions.FirstOrDefault()
        })
    .Select(
        dto => new TicketViewModel
        {
            Id = dto.Id,
            JiraKey = dto.JiraKey,
            Subject = dto.Subject,
            Status = dto.Status,
            Created = dto.Created,
            Modified = dto.Modified,
            IssueType = dto.IssueType,
            LastReaction = (dto.LastReaction != null)
                ? new TicketReactionViewModel
                {
                    UserName = dto.LastReaction.UserName,
                    Modified = dto.LastReaction.Modified
                }
                : null
        })
```
Notice that it tries to pull all of the Ticket's properties from the database, even ones not present in the view model. ColumnsToIgnore in particular is not meant to be a database column, but is defined in partial classes instead. Trying to execute this query leads to an exception
```
System.NotSupportedException : The specified type member 'ColumnsToIgnore' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.
```
Using ```ForSourceMember(src => src.ColumnsToIgnore, opt => opt.Ignore()``` doesn't help either. I should note that all of my entities inherit from EntityBase and thus have this property, but I'm only hitting this issue on mappings that use a ```MapFrom``` pointing to another mapped property and ending in ```FirstOrDefault```.

### Steps to reproduce
I dug into your code a bit and I think this may be caused by whatever ```GetSubQueryExpression``` is doing, so you may need to be on .NET 4.5 to see it. Other than that, just call something like  ```db.Tickets.ProjectTo<TicketViewModel>().ToArray()```

**Comment by FilipFilipov** [comment]
Version 6.1.1 didn't fix this for me, but it did add a minor twist. Now it throws this `ArgumentException` before it gets to the sql translation:
```
System.ArgumentException : The property 'System.Collections.Generic.List`1[System.String] ColumnsToIgnore' has no 'set' accessor
   at System.Linq.Expressions.Expression.ValidateSettableFieldOrPropertyMember(MemberInfo member, Type& memberType)
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at AutoMapper.QueryableExtensions.Impl.AssignableExpressionBinder.BindAssignableExpression(PropertyMap propertyMap, ExpressionResolutionResult result)
   at AutoMapper.QueryableExtensions.Impl.AssignableExpressionBinder.Build(IConfigurationProvider configuration, PropertyMap propertyMap, TypeMap propertyTypeMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.<CreateMemberBindings>g__CreateMemberBinding15_1(PropertyMap propertyMap, <>c__DisplayClass15_0& )
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.FirstPassLetPropertyMaps.GetSubQueryExpression(ExpressionBuilder builder, Expression projection, TypeMap typeMap, ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at AutoMapper.LockingConcurrentDictionary`2.GetOrAdd(TKey key)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)
```
If I add a setter for `ColumnsToIgnore` (which again should not be part of any mapping) I get the old `NotSupportedException` once more.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lbargaoanu** [comment]
Nevermind, I see it. I guess it's relevant it's a list.

**Comment by lbargaoanu** [comment]
@FilipFilipov Without a full repro, things like this are bound to happen. I had to make my own and saw the same error with any read only column, it didn't seem relevant it was a list.

**Comment by FilipFilipov** [comment]
The setter thing is not the core of the issue here, it should not be trying to map this property at all, read only or not.

**Comment by lbargaoanu** [comment]
And how would AM know that? :)

**Comment by FilipFilipov** [comment]
The fact that it's not in my destination types or mapping configurations.

**Comment by lbargaoanu** [comment]
Obviously that doesn't matter here. I don't see an easy way to do that.

**Comment by FilipFilipov** [comment]
What are you talking about? The whole point of the queryable projection is not to touch anything unnecessary during mapping. Not to mention it worked fine until version 6.1.0.

**Comment by lbargaoanu** [comment]
Only things in your DTO will be fetched from the DB.

**Comment by FilipFilipov** [comment]
[Here's your repro.](https://gist.github.com/FilipFilipov/0f27788b39662601118d9ceeb01cb91f) You'll need the ReadableExpressions package, as it outputs both the Queryable expression and the generated SQL to the console.
