### ISSUE TITLE
Error when mapping first element of collection only

### ISSUE THREAD

**Issue by slubowsky** [AutoMapper/AutoMapper#2174]
### Source/destination types

```csharp
    public class Person
    {
        public int Id { get; set; }
        public string Name {get; set; }
	    public List<PersonReferenceNumber> PersonReferenceNumbers { get; set; }
    }

    public class PersonReferenceNumber
    {
        public int Id { get; set; }
        public string RefNumber { get; set; }
    }

    public class PersonViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }

        // This works - (and remove ForMember from mapping)
        //public List<PersonReferenceNumberViewModel> PersonReferenceNumbers { get; set; }

        // This breaks
        public PersonReferenceNumberViewModel PersonReferenceNumber { get; set; }
    }

    public class PersonReferenceNumberViewModel
    {
        public int Id { get; set; }
        public string RefNumber { get; set; }
    }
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
            {
                cfg.CreateMap<Person, PersonViewModel>()
                    .ForMember(dest => dest.PersonReferenceNumber, opt => opt.MapFrom(src =>
                        src.PersonReferenceNumbers.FirstOrDefault()));
                cfg.CreateMap<PersonReferenceNumber, PersonReferenceNumberViewModel>();
            });
            Mapper.AssertConfigurationIsValid();
```

### Version: x.y.z
 
6.1.1
### Expected behavior

Mapping should work.

### Actual behavior

Get exception. Different exceptions in .NET Core 1.1 and .NET Core 2.0 Preview 2. Below is the 2.0 Preview 2 error:
```csharp
System.InvalidOperationException occurred
  HResult=0x80131509
  Message=variable 'markerPersonReferenceNumber' of type 'ConsoleApp.SQLite.PersonReferenceNumber' referenced from scope '', but it is not defined
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.LambdaExpression.Compile()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.Create(Shaper originalShaper, LambdaExpression materializer)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at ConsoleApp.SQLite.Program.Main() in C:\dev\ConsoleApp.SQLite\Program.cs:line 25

```
The .error in .NET Core 1.1 is something like below (didnt actually run the gist in 1.1)
```csharp
System.ArgumentNullException: Value cannot be null.
Parameter name: querySource
   at Remotion.Utilities.ArgumentUtility.CheckNotNull[T](String argumentName, T actualValue)
   at Remotion.Linq.Clauses.Expressions.QuerySourceReferenceExpression..ctor(IQuerySource querySource)
....
```

### Steps to reproduce

Gist here - https://gist.github.com/slubowsky/d992fd34a5e648b3c0f4fd0b0a915944

```csharp
context.Persons.Add(new Person { Id = 1, Name = "John Doe", PersonReferenceNumbers = new List<PersonReferenceNumber> { new PersonReferenceNumber { Id = 1, RefNumber = "TEST123" } } });
context.SaveChanges();
var result = context.Persons.ProjectTo<PersonViewModel>().FirstOrDefault();
```

**Comment by lbargaoanu** [comment]
Does this work with EF6?

**Comment by lbargaoanu** [comment]
The problem with this kind of query is that the resulting SQL is [lousy](https://github.com/AutoMapper/AutoMapper/issues/2114). The fix doesn't seem to work with EF Core. But we don't fix EF core issues at this time. So, unless you can make a repro with EF6, the suggestion is to rewrite the query. At least you would be able to improve on what AM can do by default.

**Comment by slubowsky** [comment]
Yes, It does work with Entity Framework 6, so I guess its an Entity Framework Core issue then. Ill add an issue there. Thanks!
