### ISSUE TITLE
NullReferenceException while trying to map expression

### ISSUE THREAD

**Issue by VadimGatsura** [AutoMapper/AutoMapper#2267]
### Source/destination types

```csharp
public class Course
{
    public int Id { get; set; }
}

public class CourseModel
{
    public int Id { get; set; }
}
```

### Mapping configuration

```csharp
Mapper.Initialize(cfg =>
{
    cfg.CreateMap<Course, CourseModel>();
}); 
```

### Expected behavior

Expression should be mapped without any errors.

### Actual behavior

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoMapper.XpressionMapper.XpressionMapperVisitor.FindDestinationFullName(Type typeSource, Type typeDestination, String sourceFullName, List`1 propertyMapInfoList)
   at AutoMapper.XpressionMapper.XpressionMapperVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.XpressionMapper.XpressionMapperVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at AutoMapper.XpressionMapper.Extensions.MapperExtensions.MapExpression[TDestDelegate](IMapper mapper, LambdaExpression expression)
   at AutoMapper.MapExpression.Issue.Program.Main(String[] args) in ...\AutoMapper.MapExpression.Issue\Program.cs:line 18
```
After investigation I figured out that the reason of NullReference was lack of configuration for mapping CourseModel to Course. After map creation, expression was mapped.
I think AutoMapperMappingException with details of missed mapping types will be more appropriate in this case. In addition, I was surprised why AutoMapper needed reverse mapping.

### Steps to reproduce

```csharp
Expression<Func<Course, bool>> exp = course => course.Id == 1;
var mappedExpresion = Mapper.Instance.MapExpression<Expression<Func<CourseModel, bool>>>(exp);
```
[Program.zip](https://github.com/AutoMapper/AutoMapper/files/1215552/Program.zip)

**Comment by VadimGatsura** [comment]
I would be very grateful for the opportunity to create pull request. I believe implementation of throwing AutoMapperMappingException is more appropriate than

**Comment by lbargaoanu** [comment]
Yes, it is. Please do :)
