### ISSUE TITLE
Argument types do not match exception when mapping DateTime? to object

### ISSUE THREAD

**Issue by geriadejes** [AutoMapper/AutoMapper#2283]
Hi, 

I've had a mapping:
`cfg.CreateMap<DateTime?, DateAndTimeViewModel>().ForMember(x => x.DateAndTime, m => m.MapFrom(x => x));`

Which was working fine with .ProjectTo() until I updated to Automapper 6.1.1, now I'm getting this exception:

`System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.ValidateCoalesceArgTypes(Type left, Type right)
   at System.Linq.Expressions.Expression.Coalesce(Expression left, Expression right, LambdaExpression conversion)
   at AutoMapper.QueryableExtensions.NullableSourceExpressionBinder.Build(IConfigurationProvider configuration, PropertyMap propertyMap, TypeMap propertyTypeMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.<CreateMemberBindings>g__CreateMemberBinding15_1(PropertyMap propertyMap, <>c__DisplayClass15_0& )
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)`

I haven't noticed any breaking changes related to this behavior in release notes, is something wrong with the mapping, or it's a bug in the latest version?

Greetings,
Donatas

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lbargaoanu** [comment]
Or try the [MyGet](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-Build) build.

**Comment by geriadejes** [comment]
The repro is really simple: https://gist.github.com/geriadejes/51c0759dd3ddbc79e429b4fe3e6f8522

**Comment by lbargaoanu** [comment]
That works for me with the MyGet build.

**Comment by geriadejes** [comment]
Ok, I can confirm it works fine with the latest build, looking forward for the official release, Thank you for quick response.
