### ISSUE TITLE
MapperConfiguration.AddProfiles Could not load file or assembly 'System.Collections.Specialized'

### ISSUE THREAD

**Issue by thnk2wn** [AutoMapper/AutoMapper#2287]
### Source/destination types

```csharp
// Source/destination types are not applicable here
```

### Mapping configuration

```csharp
    public static class MappingConfigService
    {
        public static MapperConfiguration Configure()
        {
            Assembly assembly = typeof(MappingConfigService).GetTypeInfo().Assembly;
            MapperConfiguration config = new MapperConfiguration(
                cfg =>
                {
                    // 'Could not load file or assembly 'System.Collections.Specialized, 
                    // Version =4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' 
                    // or one of its dependencies. The system cannot find the file specified.'
                    cfg.AddProfiles(assembly);
                });

            return config;
        }
    } 
```

### Expected behavior
Expected mapper to be created in the context of a UWP test that invokes mapping setup in a UWP project which uses assembly scanning for profiles. Works when running the UWP app directly.

### Actual behavior

Running the UWP unit test gives the following error. Similar to #2051 but different context/issue:

`
System.IO.FileNotFoundException occurred
  HResult=0x80070002
  Message=Could not load file or assembly 'System.Collections.Specialized, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
  Source=AutoMapper
  StackTrace:
   at AutoMapper.Mappers.NameValueCollectionMapper.IsMatch(TypePair context)
   at AutoMapper.MapperConfiguration.<>c__DisplayClass59_0.<FindMapper>b__0(IObjectMapper m)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
   at AutoMapper.Execution.TypeMapPlanBuilder.ResolvePropertyTypeMap(PropertyMap propertyMap)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.<>c__DisplayClass17_0.<CheckForCycles>g__CheckPropertyMapsForCycles0()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 visitedTypeMaps)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 visitedTypeMaps)
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider, HashSet`1 visitedTypeMaps)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapperUWP2.Mapping.MappingConfigService.Configure() in C:\Users\geoffh\Documents\Visual Studio 2017\Projects\AutoMapperUWPAddProfilesIssue\AutoMapperUWP2\Mapping\MappingConfigService.cs:line 12
   at AutoMapperUWPTests.Common.ViewModelTestFixture.CreateMapper() in C:\Users\geoffh\Documents\Visual Studio 2017\Projects\AutoMapperUWPAddProfilesIssue\AutoMapperUWPTests\Common\ViewModelTestFixture.cs:line 26
   at AutoMapperUWPTests.Common.ViewModelTestFixture.PerformOneTimeSetup() in C:\Users\geoffh\Documents\Visual Studio 2017\Projects\AutoMapperUWPAddProfilesIssue\AutoMapperUWPTests\Common\ViewModelTestFixture.cs:line 21
   at AutoMapperUWPTests.Common.ViewModelTestFixture..ctor() in C:\Users\geoffh\Documents\Visual Studio 2017\Projects\AutoMapperUWPAddProfilesIssue\AutoMapperUWPTests\Common\ViewModelTestFixture.cs:line 13
`

### Steps to reproduce
See sample issue repo at https://github.com/thnk2wn/AutoMapperUWPAddProfilesIssue. Run the single unit test in https://github.com/thnk2wn/AutoMapperUWPAddProfilesIssue/blob/master/AutoMapperUWPTests/UnitTest.cs. Error will happen via the test fixture that's passed into unit test class ctor; that'll call MappingConfigService.Configure() in the UWP project being tested.

The projects are configured for Windows 10 Creators Update but if that's not installed, you might be able to reproduce targeting older UWP version in project properties. In my case I'm going through ReSharper's unit test runner and using xunit but don't think that's relevant.

```csharp
// No calls to Map are relevant here.
```

### Misc
Found https://github.com/dotnet/corefx/issues/10338 and updated UWP and also tried workarounds to no avail.

I'm guessing there's fault here outside AutoMapper but I'm non positive there's not an issue using AutoMapper in UWP within the context of unit testing or why this wouldn't work / what to change.

**Comment by lbargaoanu** [comment]
A repro without UWP would be nice :) The install is smth like 4Gb. Other than that, you could simply remove the NameValueCollectionMapper. Most people don't need it anyway.

**Comment by lbargaoanu** [comment]
Another thing to try: https://www.hanselman.com/blog/ReferencingNETStandardAssembliesFromBothNETCoreAndNETFramework.aspx.

**Comment by thnk2wn** [comment]
Turns out the issue was running UWP tests through ReSharper's test runner. Had a similar issue in the past - https://youtrack.jetbrains.com/issue/RSRP-464103. Running the test via Test Explorer didn't produce the AutoMapper issue.
