### ISSUE TITLE
ProjectTo throws error when mapping Enums

### ISSUE THREAD

**Issue by TrplM** [AutoMapper/AutoMapper#2291]
### Source/destination types

```csharp

namespace Domain
{
    enum Numbers
    {
        One = 1,
        Two = 2
    }

    class Foo
    {
        public Numbers numbers { get; set; }
        ...
    }
}

namespace Presentation
{
    enum Numbers
    {
        One = 1,
        Two = 2
    }
    
    class Bar
    {
        public Numbers numbers { get; set; }
        ...
    }
}

```

### Mapping configuration

```csharp
CreateMap<Domain.Numbers, Presentation.Numbers>().ReverseMap();

CreateMap<Foo, Bar>().ReverseMap();
```

### Expected behavior

EF Core produces valid sql. ProjectTo() should be able to handle enums in a similar manner

```csharp
context.Foo.Select(f => new Bar { 
    Numbers = (Presentation.Numbers) f.numbers //Domain.Numbers
})
.ToList()

//SELECT [f].[numbers] FROM [Foo] AS [f]
```

### Actual behavior

throws "Argument types do not match"

### Steps to reproduce

```csharp

context.Foo.ProjectTo<Bar>().ToList()

//OR

context.Foo.UseAsDataSource().For<Bar>()

```

### Stack Trace

```csharp

System.ArgumentException occurred
  HResult=0x80070057
  Message=Argument types do not match
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.BindMappedTypeExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.<CreateMemberBindings>g__CreateMemberBinding15_1(PropertyMap propertyMap, <>c__DisplayClass15_0& )
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Expression`1[] membersToExpand)
   at FooController.ctor(ILogger`1 Logger)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
```

**Comment by lbargaoanu** [comment]
That map you created doesn't do anything useful :) Try

    cfg.CreateMap<Numbers1, Numbers2>().ProjectUsing(s=>(Numbers2)s);
