### ISSUE TITLE
Projection from Type to string does not work es expected

### ISSUE THREAD

**Issue by DerAlbertCom** [AutoMapper/AutoMapper#2292]
I don't know if this is supposed to work, in my view it should.

I make a mapping ` c.CreateMap<BarEntity, string>().ConstructProjectionUsing(b => b.Type);` this works on a concrete instance, but is throws an exception on a projection . I'm using **AutoMapper 6.1.1** (on .NET CoreApp, it does not matter 1.1 or 2.0)

```
System.ArgumentNullException : Value cannot be null.
Parameter name: newExpression
```

Here is a reproduction sample.

```
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Xunit;

namespace StructureMapBug
{
    public class StructureMapProjectionBug
    {
        public class FooEntity
        {
            public FooEntity()
            {
                Bars = new List<BarEntity>();
            }

            public int Id { get; set; }

            public IList<BarEntity> Bars { get; set; }
        }

        public class BarEntity
        {
            public string Type { get; set; }
        }

        public class FooModel
        {
            public int Id { get; set; }
            public string[] Bars { get; set; }
        }

        [Fact]
        public void Test1()
        {
            var config = new MapperConfiguration(c =>
            {
                c.CreateMap<FooEntity, FooModel>();
                c.CreateMap<BarEntity, string>().ConstructProjectionUsing(b => b.Type);
            });
            var mapper = config.CreateMapper();

            var list = new List<FooEntity>().AsQueryable();

            var result = list.ProjectTo<FooModel>(mapper.ConfigurationProvider).ToArray();
        }
    }
}
``` 
the real code is using EntityFramework

and here to complete stacktrace. from the unit test

```
      System.ArgumentNullException : Value cannot be null.
       Parameter name: newExpression
      Stack Trace:
         at System.Linq.Expressions.Expression.MemberInit(NewExpression newExpression, IEnumerable`1 bindings)
         at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.Impl.EnumerableExpressionBinder.BindEnumerableExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.ExpressionBuilder.<CreateMemberBindings>g__CreateMemberBinding15_1(PropertyMap propertyMap, <>c__DisplayClass15_0& )
         at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.LazyInitValue()
         at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
         at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
         at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Expression`1[] membersToExpand)
        c:\src\StructureMapBug\StructureMapBug\StructureMapProjectionBug.cs(46,0): at StructureMapBug.StructureMapProjectionBug.Test1()
```

**Comment by jbogard** [comment]
Try this on EF without AutoMapper using Select.

**Comment by lbargaoanu** [comment]
ConstructProjectionUsing must return a constructor :), try ProjectUsing instead.

**Comment by DerAlbertCom** [comment]
@lbargaoanu ProjectUsing is working now.. Thanks.
@jbogard it now works also with EF.
