### ISSUE TITLE
AutoMapper 6.2.* + AutoMapper.Collection => System.ArgumentException: 'Argument types do not match' 

### ISSUE THREAD

**Issue by ristogod** [AutoMapper/AutoMapper#2411]
We just updated AutoMapper from version 6.1.1 to 6.2.0. I also tried the more recently released 6.2.1 and the issue still persists.

As soon as we did we not get **System.ArgumentException: 'Argument types do not match'** on application startup.

>    at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
   at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Execution.ExpressionBuilder.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, TypePair typePair, Expression sourceParameter, Expression contextParameter, PropertyMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, Expression destination)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(Stack`1 typeMapsPath)
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider, Stack`1 typeMapsPath)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at TestApp.Startup.ConfigureServices(IServiceCollection services) in C:\Users\natha\source\repos\TestApp\TestApp\Startup.cs:line 115

It is thrown from this code

``` csharp
var mapperConfiguration = new MapperConfiguration(_ =>
                                                  {
                                                      _.AddCollectionMappers();
                                                      _.AddProfile<DefaultProfile>();
                                                  });
```

I've tried looking up how to resolve this, but found nothing. I don't understand what's causing it. Everything worked before updating.

I've reported this issue prior and was instructed to make a gist. I could not figure out how to load an entire application into a gist, so **I made a new repo demonstrating the problem [here](https://github.com/ristogod/AutoMapper.TestApp).**

The project that demonstrates the issue is a cut down version containing parts of the original application we first witnessed the issue happening. All of the internal nuget packages not available publicly have been converted to projects within the solution to be referenced.

The project TestApp should be set to be the startup project. Within TestApp.csproj you will see the nuget package reference to AutoMapper 6.2.1. Left in place the exception will be thrown on startup. If changed to 6.1.1, the application starts normally.

I feel this might be related to AutoMapper.Collections as if I remove the lines 
``` csharp
 _.AddCollectionMappers();
```
and lines like this from the mapping Profile
```csharp
.EqualityComparison((source, target) => source.SectionId == target.SectionId)
```
then application starts. But without the collection equality comparisons, the mapping does not work correctly.

**Comment by lbargaoanu** [comment]
Yes, it looks like a problem with AutoMapper.Collections, so please open an issue there. We'll reopen this one if @TylerCarlson1 decides it's an AM problem.
