### ISSUE TITLE
Upgrading from 6.2.0 to 6.2.1 get null pointer exception on mapper initialization

### ISSUE THREAD

**Issue by slubowsky** [AutoMapper/AutoMapper#2415]
### Source/destination types

Haven't yet narrowed it down to mappings causing the issue (I have lots) - but works fine with previous version - 6.2.0. If needed I will try to identify cause.
Not sure if this is an Automapper or Automapper.Collection issue - but its the automapper update thats causing the issue...

### Version: x.y.z
6.2.1

### Expected behavior

Initialization should succeed as it does with 6.2.0

### Actual behavior

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=AutoMapper.Collection
  StackTrace:
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c.<CreateEquivalentExpression>b__11_0(PropertyMap pm)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.CreateEquivalentExpression(IEnumerable`1 propertyMaps)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c__DisplayClass7_0.<GetEquivalentExpression>b__1(IGeneratePropertyMaps _)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.<>c__DisplayClass7_0.<GetEquivalentExpression>b__0(TypePair tp)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationProvider configurationProvider, TypeMap typeMap)
   at AutoMapper.EquivalencyExpression.EquivalentExpressions.GetEquivalentExpression(IConfigurationObjectMapper mapper, Type sourceType, Type destinationType)
   at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.IsMatch(TypePair typePair)
   at AutoMapper.MapperConfiguration.<>c__DisplayClass63_0.<FindMapper>b__0(IObjectMapper m)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at AutoMapper.MapperConfiguration.FindMapper(TypePair types)
   at AutoMapper.MapperConfiguration.GetTypeMap(TypePair initialTypes)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration)
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair)
   at AutoMapper.Execution.TypeMapPlanBuilder.ResolveTypeMap(TypePair types)
   at AutoMapper.Execution.TypeMapPlanBuilder.ResolvePropertyTypeMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>b__17_1(PropertyMap pm)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(Stack`1 typeMapsPath)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(Stack`1 typeMapsPath)
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider, Stack`1 typeMapsPath)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at MyApp.API.ViewModels.Mappings.AutoMapperConfiguration.Configure(IServiceProvider provider) in C:\dev\myApp-api\MyApp.API\ViewModels\Mappings\AutoMapperConfiguration.cs:line 16
   at MyApp.API.Startup.ConfigureServices(IServiceCollection services) in C:\dev\myApp-api\MyApp.API\Startup.cs:line 218
```

**Comment by TylerCarlson1** [comment]
You are using GeneratePropertyMap logic.  Are you using AutoMapper.Collections.EntityFramework?  Issue might be caused by validation changes.

There's another issue with 6.2.1 with CollectionMapper returning lists instead of ICollection, but I'm not sure if this is causing it or not.

**Comment by lbargaoanu** [comment]
This belongs in the AM.Collections repository.

**Comment by slubowsky** [comment]
@TylerCarlson1 No I am not using AutoMapper.Collections.EntityFramework (its not compatible with Entity Framework Core apparently). I do have a custom implementation of GenerateEntityFrameworkPrimaryKeyPropertyMaps but as far as I can tell its not doing anything different now after the update in AutoMapper versions.
