### ISSUE TITLE
Struct self-mapping

### ISSUE THREAD

**Issue by juwens** [AutoMapper/AutoMapper#2418]
https://gist.github.com/juwens/16ab14f6cd5357cad21c81654aa841a1

### Expected behavior
No Exception

### Actual behavior
Excepttion

System.InvalidOperationException was unhandled
  HResult=-2146233079
  Message=The binary operator NotEqual is not defined for the types 'ConsoleApplication2.Program+MyStruct' and 'System.Object'.
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
       at System.Linq.Expressions.Expression.NotEqual(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
       at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
       at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(Stack`1 typeMapsPath)
       at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider, Stack`1 typeMapsPath)
       at AutoMapper.MapperConfiguration.Seal()
       at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
       at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
       at ConsoleApplication2.Program.Main(String[] args) in c:\users\abk07\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\Program.cs:line 14
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()

### Steps to reproduce
run gist

**Comment by lbargaoanu** [comment]
As a workaround, you can remove the setter or use 
    
     ForMember(d=>d.A, o=>o.Ignore()));
