### ISSUE TITLE
Mapping collections with AutoMapper.Collection is broken in 6.2.0 and higher

### ISSUE THREAD

**Issue by samisq** [AutoMapper/AutoMapper#2430]
### MCVE: 
[See gist](https://gist.github.com/samisq/527860e46e5355c829ef12dabb034150)

### Expected behavior

Maps should be initialized and should be able to map collections with AutoMapper.Collection. **This works correctly in 6.1.1**

### Actual behavior

Throws the exception below and maps cannot be initialized:
```
Unhandled Exception: System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse)
   at AutoMapper.Mappers.EquivalentExpressionAddRemoveCollectionMapper.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, PropertyMap propertyMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Execution.ExpressionBuilder.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, TypePair typePair, Expression sourceParameter, Expression contextParameter, PropertyMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(PropertyMap propertyMap, Expression destination)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc, Boolean constructorMapping)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(Stack`1 typeMapsPath)
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider, Stack`1 typeMapsPath)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.Mapper.Initialize(Action`1 config)
```

### Steps to reproduce

Use the gist as a console App with AutoMapper 6.2.0 or 6.2.1.

**Comment by lbargaoanu** [comment]
This belongs in the AM.Collection repo.

**Comment by samisq** [comment]
Same as AutoMapper/AutoMapper.Collection#63

**Comment by TylerCarlson1** [comment]
@samisq Can you try to see if it works on the [MyGet Build](https://github.com/AutoMapper/AutoMapper/wiki/The-MyGet-build)?  Just do AutoMapper.Collections instead of AutoMapper

**Comment by samisq** [comment]
@TylerCarlson1 Yep, that fixed it! Thanks for the quick turnaround. I'll look out for the official package :).

**Comment by TylerCarlson1** [comment]
Done  I just needed someone to confirm
