### ISSUE TITLE
How to project and flatten and create a custom list type?

### ISSUE THREAD

**Issue by Thomas5890** [AutoMapper/AutoMapper#2470]
### Source/destination types
The **custom list type** is defined like this – with an interface and an implementation of this interface:
```csharp
public interface ICustomList : System.Collection.Generic.IList
{}
public class CustomList : System.Collection.Generic.List, ICustomList
{}
```

The **entities** look like this, Person has an 1:n-Relation to PersonAccount (and of course there’s another entity Account, but, I think, that’s not important for this sample) (they are the source of the projection):
```csharp
public class Person  
{  
    public int Id { get; set; }  
    public string Name { get; set; }  
    public ICollection<Account> Accounts { get; set; }  
}  

public class PersonAccount  
{  
    public int Id { get; set; }  
    public int PersonId { get; set; }  
    public int AccountId { get; set; }  
    public Person Person { get; set; }  
} 
```
The **DTO** looks like this (it's the projection destination):
```csharp
public class PersonAccountDTO  
{  
    public int PersonId { get; set; }  
    public ICustomList<int> PersonAccountIds { get; set; }  
}  
```

### Mapping configuration

**AutoMapper is configured** like this:
```csharp
config.CreateMap<System.Collections.Generic.List<int>, ICustomList<int>>()  
      //.ConvertUsing(x => new CustomList<int>(x));  // does not work either
      //.ConstructProjectionUsing(x => new Custo,List<int>(x))  // does not work either
      .ConstructUsing(x => new CustomList<int>())
          .DisableCtorValidation();  

config.CreateMap<Person, PersonAccountDTO>()  
   .ForMember(dest => dest.PersonId, source => source.MapFrom(x => x.Id))  
   .ForMember(dest => dest.PersonAccountIds, source => source.MapFrom(person => person.Accounts
                .Where(y => ….)  
                .OrderBy(y => …)  
                .Select(y => y.Id)  
                .ToList();  

```

### Version:
 
Automapper 6.2.0
Entity Framework 6.1.3

### Steps to reproduce

The query is build like that:
```csharp
var query = context.Persons.AsNoTracking()  
        .Where(x => persIds.Contains((int)x.Id))  
        .ProjectTo<PersonAccountDTO>();
```

### Expected behavior

I expected that data is projected into new DTO instances and new list instances (of type CustomList).

### Actual behavior

When trying to build the EF query an exception is thrown
ArgumentException: Argument types do not match

   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at AutoMapper.QueryableExtensions.Impl.EnumerableExpressionBinder.BindEnumerableExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.Impl.EnumerableExpressionBinder.Build(IConfigurationProvider configuration, PropertyMap propertyMap, TypeMap propertyTypeMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.<CreateMemberBindings>g__CreateMemberBinding|15_0(PropertyMap propertyMap, <>c__DisplayClass15_0& )
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps, TypeMap& typeMap)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, String[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, IDictionary`2 parameters, String[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IDictionary`2 parameters, String[] membersToExpand)

### See also
https://stackoverflow.com/questions/47305348/how-to-project-and-flatten-and-create-a-custom-list-type-projecttot-ef6

**Comment by lbargaoanu** [comment]
Try to write a LINQ query that does what you want and then we'll see how we can translate that to AM code.

**Comment by Thomas5890** [comment]
Hello lbargaoanu,

You had closed this issue. What do I have to do on my side to make things work?

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/2470#issuecomment-353609771

**Comment by Thomas5890** [comment]
I tried to write to a query, the result works, but it does not look like I wanted it to be.

I liked to do it this way.
```
    var query = sut.Persons.AsNoTracking()
        .Where(x => personIds.Contains((int)x.Id))

        .Select(x => new PersonAccountDTO
        {
            PersonId = (int)x.Id,
             // ToCustomList() is an extension method for IEnumerable<T>
            PersonAccountIds = x.PersonAccounts.Select(y => (int)y.Id).ToCustomList()
        });

    var list = query.ToList();
```
Trying to materialize this query the following exception is thrown.
System.NotSupportedException" in EntityFramework.dll
LINQ to Entities does not recognize the method 
'ICSYS.PS.Stammdaten.Entities.Ef6Context.Test.ICustomList`1[System.Int32] 
ToCustomList[Int32](System.Collections.Generic.IEnumerable`1[System.Int32])' method, 
and this method cannot be translated into a store expression.

This issue is described here
http://web.archive.org/web/20131124232125/http://mosesofegypt.net/post/LINQ-to-Entities-what-is-not-supported.aspx
The post is quite old, maybe now there’s a to overcome this issue!?

To work around this error, I added the projection into an anonymous type and a call to AsEnumerable. This way it works without pulling to much data from the database, but dealing with the anonymous type is not desirable.
```
    var query = sut.Persons.AsNoTracking()
        .Where(x => personIds.Contains((int)x.Id))
        .Select(x => new
        {
            PersonId = (int)x.Id,
            PersonAccountIds = x.PersonAccounts.Select(y => (int)y.EigschId).ToList()
        })
        .AsEnumerable() // Workaround: force materialization and client side evaluation of the rest of the query
        .Select(x => new PersonAccountDTO()
        {
            PersonId = x.PersonId,
            PersonAccountIds = new CustomList<int>(x.PersonAccountIds)
        });
```

**Comment by lbargaoanu** [comment]
My point was that I don't think this is possible with EF6, so it's not possible with ProjectTo. Unless proven otherwise :)

**Comment by Thomas5890** [comment]
What a pity!
Can you “recommend” me some dirty hack, may be some kind of interception in EF or Automapper, so that the desired type of list is created?

**Comment by lbargaoanu** [comment]
About AM, you can use Map instead. About EF, I don't know. cc @jbogard

**Comment by Thomas5890** [comment]
Thank you.

**Comment by jbogard** [comment]
Why not create a second property (a shadow property) that holds the list, and then your actual property returns the right value? Or you could make the setter of your list do the conversion? EF still just calls setters so you could try to get creative inside of there.

**Comment by Thomas5890** [comment]
Hello Jimmy,

> EF still just calls setters so you could try to get creative inside of there.

This would be a viable way. But it seems EF does not like my way of being creative:
    

```
     public class PersonAccountDTO
    {
        private System.Collections.Generic.IList<int> _personAccountIdsMsList { get; set; }
        private ICustomList<int> _personAccountIds;
        public int PersonId { get; set; }

        public ICustomList<int> PersonAccountIds
        {
            get { return _personAccountIds; }
            set { _personAccountIds = value; }
        }

        // shadow property that doesn’t work – it produces an empty list
        //public System.Collections.Generic.List<int> PersonAccountIdsMsList
        //{

        //    get { return (System.Collections.Generic.List<int>)_personAccountIds; }
        //    set
        //    {
        //        var newIntance = new CustomList<int>();
        //        newIntance.AddRange(value);
        //        _personAccountIds = newIntance;

        //    }
        //}

        // shadow property that doesn’t work – it doesn’t make any conversion
        public System.Collections.Generic.IList<int> PersonAccountIdsMsList
        {
            get { return _personAccountIdsMsList; }
            set { _personAccountIdsMsList = value; }
        }
    }

```
EFs projection is working properly as long as I’m writing the setter with nothing else then “_fieldname = value;”. Making any modifications (e.g. a type cast, an additional assignment, an empty setter / look at the commented code) produces any empty list. If I watch for the value of value inside the setter while debugging, value is always an empty list.
