### ISSUE TITLE
Generic IQueryable conversion error. "must be reducible node"

### ISSUE THREAD

**Issue by cispiroglu** [AutoMapper/AutoMapper#2473]
### Source/destination types
DTO and Model Classes(both same)

```csharp
   public class Users : Entity<int>
   {
        public virtual string UserName { get; set; }
        public virtual IList<Roles> Roles { get; protected set; }
    }
    public class Roles : Entity<int>
    {
        public virtual string Name { get; set; }
        public virtual IList<Users> Users { get; protected set; }
        public virtual IList<RoleInPages> RoleInPages { get; protected set; }
    }
    public class RoleInPages : Entity<int>
    {
        public virtual Roles Role { get; set; }
        public virtual Pages Page { get; set; }
    }
    public class Pages : Entity<int>
    {
        public virtual string Name { get; set; }
        public virtual IList<RoleInPages> RoleInPages { get; protected set; }
        public virtual IList<ControllerActions> ControllerActions { get; protected set; }
    }

    public class ControllerActions : Entity<int>
    {
        public virtual string Controller { get; set; }
        public virtual string Action { get; set; }
        public virtual string Description { get; set; }
        public virtual IList<Pages> Pages { get; protected set; }
    }

```
### Mapping configuration

```csharp

    public class AutoMapperGenericHelper<TSource, TDestination>
    {
        public static TDestination Convert(TSource model)
        {
            if (Mapper.Instance.ConfigurationProvider.FindTypeMapFor<TSource, TDestination>() == null)
                    Mapper.Initialize(cfg => {
                        cfg.CreateMap<TSource, TDestination>();
                        cfg.CreateMissingTypeMaps = true;
                        cfg.ForAllMaps((mapType, mapperExpression) => {
                            mapperExpression.MaxDepth(1);
                        });
                    });

                return Mapper.Map<TSource, TDestination>(model);
        }

        public static IQueryable<TDestination> ConvertAsQueryable(IQueryable<TSource> sourceQueryable)
        {
                if (Mapper.Instance.ConfigurationProvider.FindTypeMapFor<TSource, TDestination>() == null)
                    Mapper.Initialize(cfg => {
                        cfg.CreateMap<TSource, TDestination>();
                        cfg.CreateMissingTypeMaps = true;
                        cfg.ForAllMaps((mapType, mapperExpression) => {
                            mapperExpression.MaxDepth(1);
                        });
                    });
                
                return sourceQueryable.ProjectTo<TDestination>();
        }
    }



```

### Version: x.y.z
AutoMapper: 6.1.1
framework: 4.6.1

### Expected behavior

Expecting convert list of dto objects to business objects.

### Actual behavior

Convert method works perfectly for all objects. I'm expecting the same behaviour ConvertAsQueryable method too.

if i use like below still works perfectly...

```csharp

    IList<ControllerActionsModel> modelList = new List<ControllerActionsModel>();

    foreach (var controller in dal)
        modelList.Add(AutoMapperGenericHelper<ControllerActions, ControllerActionsModel>.Convert(controller));

```

Stacktrace: (Source: System.Core)
```csharp

  at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter..ctor(MemberAssignment binding, StackSpiller spiller, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.Create(MemberBinding binding, StackSpiller spiller, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter..ctor(MemberAssignment binding, StackSpiller spiller, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.Create(MemberBinding binding, StackSpiller spiller, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteInvocationExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at System.Linq.Expressions.Expression`1.Compile()
   at NHibernate.Linq.ExpressionToHqlTranslationResults.MergeLambdasAndCompile[TDelegate](IList`1 itemTransformers)
   at NHibernate.Linq.ExpressionToHqlTranslationResults..ctor(HqlTreeNode statement, IList`1 itemTransformers, IList`1 listTransformers, IList`1 postExecuteTransformers, List`1 additionalCriteria, Type executeResultTypeOverride)
   at NHibernate.Linq.IntermediateHqlTree.GetTranslation()
   at NHibernate.Linq.NhLinqExpression.Translate(ISessionFactoryImplementor sessionFactory, Boolean filter)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters)
   at NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow)
   at NHibernate.Impl.SessionImpl.CreateQuery(IQueryExpression queryExpression)
   at NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at XX.Services.Auth.Classes.ControllerActionsService.GetAllAsync() in YYY
   at Castle.Proxies.Invocations.IControllerActionsService_GetAllAsync.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at XX.Infrastructure.Dependency.CastleWindsor.UnitOfWorkInterceptor.Intercept(IInvocation invocation) in YYY

```

### Steps to reproduce

How i call ConvertAsQueryable method(call project to):
```csharp

IQueryable<ModelObjectBusinessClass> modelList = AutoMapperGenericHelper<ModelObjectDTOClass, ModelObjectBusinessClass>.ConvertAsQueryable(dal);
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by jbogard** [comment]
Can you rewrite your code to just call Select instead? That will tell me if
the query is even possible in LINQ.

**Comment by cispiroglu** [comment]
it hard to make gist because of the nhibernate creates own instance for relations between inner objects.

it returns resultSelect correctly

```csharp
var resultSelect = from s in sourceQueryable select s;
```

Changed ConvertAsQueryable method return like below and it still working but i think this is also same for my Convert method.

```csharp

return sourceQueryable.AsEnumerable().Select(source => Mapper.Map<TSource, TDestination>(source)).AsQueryable();

```

**Comment by TylerCarlson1** [comment]
Looks like it's a nhibernate limitation.  I know @jbogard said it had some kind of limitation that moved him to EF.  Maybe that's the same limitation, and that being you can't project multiple levels down with a list.

**Comment by jbogard** [comment]
@cispiroglu that's not quite what I meant - when you do `AsEnumerable` then `Mapper.Map` that's not the same as `ProjectTo` by itself.

What I meant was to create the `Select` projection manually like:


`session.Query<Cat>().Select(c =>  new CatDto { /* stuff */ }).ToList();`

Fill in the right types and let me know if NHibernate can make the projection work by itself.

Remember, `ProjectTo` just creates `Select` part. It makes assumptions about what the LINQ provider can handle.
