### ISSUE TITLE
ProjectTo can not map Collection to Property

### ISSUE THREAD

**Issue by NetTecture** [AutoMapper/AutoMapper#2555]
I have a little unusual scenario. I map objects (obviosly). Every object has a RIGHTS collection. There is one entry there for every user that has access to the object.

In order to configure the UI, I need to return the rights for the CURRENT USER (i.e. only ONE right object ever) in my mapped DTO.

The entity in question is TMandator, having VMandatorRights mapped to Mandator and Rights.

I define:

* "base" object:

`public virtual ICollection<VMandatorRights> Rights { get; set; }`

* Maps to the following dto property:

 `public Rights Rights { get; set; }`

Then I map - easy for demonstration, in the mapping of the base object...

`.ForMember(d => d.Rights, o => o.MapFrom(s => s.Rights.FirstOrDefault()))`

The idea is to inject the current user into the mapping so there will later be a WHERE clause in there.

Sadly, there is no way to get this working. The above mapping (there obviously is a VMandatorRights to Rights mapping), results in:

  | Name | Value | Type
-- | -- | -- | --
▶ | $exception | {"The interface has a conflicting property Rights\r\nParameter name: interfaceType"} | System.ArgumentException
```
Stack trace:

   at AutoMapper.Execution.ProxyGenerator.EmitProxy(TypeDescription typeDescription)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.Execution.ProxyGenerator.GetSimilarType(Type sourceType, IEnumerable`1 additionalProperties)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.FirstPassLetPropertyMaps.GetSubQueryExpression(ExpressionBuilder builder, Expression projection, TypeMap typeMap, ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, String[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, IDictionary`2 parameters, String[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IDictionary`2 parameters, String[] membersToExpand)
   at RestApi.OBB.Web.Controllers.Global.MandatorController.List(String expand) in C:\Work\OBB\RestApi.OBB.Web\Controllers\Global\MandatorController.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
```

if I change the mapped property to a collection:

`public ICollection<Rights> Rights { get; set; }`

and the mapping to

`.ForMember(d => d.Rights, o => o.MapFrom(s => s.Rights))`

i get.... results. It is quite obvious that the mapping of one element of the collection to a property is going wrong somewhere. From a LINQ point of view that would not be a problem.

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by NetTecture** [comment]
I can not put up a decently small sample case - this does not happen on "simple" scenarios (which I tried as unit test in a fork).

What I can offer is that next week I copy our code into a separate project, rip everything out except the mappings we have (which are 5 configs), then rip everything out of our EF DAL (except the classes needed - about 10 or so) and make a small test project demonstrating the case. I would have to submit that via email, though, under confidentiality (for legal reasons). This defintely seems to ahve something to do with repetitive property naming.

I got it sorted out to the level that I get now:

"The parameter 'dto' was not bound in the specified LINQ to Entities query expression."
ExceptionType
:
"System.InvalidOperationException"
Message
:
"An error has occurred."
StackTrace
:
"   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.ParameterTranslator.TypedTranslate(ExpressionConverter parent, ParameterExpression linq)
↵   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1

The mapping is a ocllection to a single property (with the colelction mapped as 

.ForMember(d => d.EntityRights, o => o.MapFrom(s => s.Rights.Where(x => x.LoginID == loginId).FirstOrDefault()))

If I remove the FirstOrDefault and have a collection in the target - then it works.

**Comment by lbargaoanu** [comment]
Did you understand what the workaround is?

**Comment by NetTecture** [comment]
? Not sure what you mean? Did you say one? The Workaround is expsing a collection with one Element on the target. Did you talk anywhere about a workaround?

**Comment by NetTecture** [comment]
I did do some renaming - that is how I dneded up geettging the last error (about dto). DO not see any double property name now.

**Comment by lbargaoanu** [comment]
For that last error we do need a repro. When I rename, it works for me.

**Comment by NetTecture** [comment]
As I said, I can cut down our code for a repro next week, if I can send you a download link. H ave been unsusccessfull in reproing it with an easy case, and it happens on the linq layer so it needs the mappings.

**Comment by TylerCarlson1** [comment]
From the exception it looks like you are using EF.Core, and the exception might be a limitation of that vs what EF6 can do.

Also have you tried s.Rights.FirstOrDefault(x => x.LoginID == loginId) and see if that works any better.

**Comment by NetTecture** [comment]
Nope, not using EF Core - EF 6 also has a core namespace that has some internal stuff there. We plan to migrate to dotnet core - but seriously, as long as we dont ahve dotnet core 2.1 - where ef core can group by on the database - this is hopeless. Definitely no ef core here ;)

**Comment by lbargaoanu** [comment]
Try the [MyGet](http://docs.automapper.org/en/stable/The-MyGet-build.html) build.
