### ISSUE TITLE
Mapping Profiles not found

### ISSUE THREAD

**Issue by dhruvb14** [AutoMapper/AutoMapper#2642]
Using Latest Dotnetcore 2 Angular template from Microsoft.

I have 2 other projects with a similar setup and it works perfectly fine. Not sure what is missed here

### Source/destination types

```csharp
using AutoMapper;
using Brownbag.Data.Models;
using Brownbag.Web.Models;

namespace Brownbag.Web.Automapper
{
    public class BrownbagMappingProfile : Profile
    {
        public BrownbagMappingProfile()
        {
            CreateMap<Blog, BlogViewModel>();
            CreateMap<BlogViewModel, Blog>();
        //    .ReverseMap();
            CreateMap<Post, PostViewModel>();
            CreateMap<PostViewModel, Post>();
        //    .ReverseMap();
        }
    }
}
```

### Mapping configuration

```csharp
public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();

            var connection = @"Server=Localhost;Database=Brownbag;Trusted_Connection=True;ConnectRetryCount=0";
            services.AddDbContext<ApplicationDataContext>(options => options.UseSqlServer(connection));

            services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
            services.AddMvc()
                    .AddJsonOptions(options => options.SerializerSettings.ContractResolver = new DefaultContractResolver());

            services.AddKendo();
            services.AddScoped<IBrownbagRoleProvider, BrownbagRoleProvider>();

            // In production, the Angular files will be served from this directory
            services.AddSpaStaticFiles(configuration =>
            {
                configuration.RootPath = "ClientApp/dist";
            });

            services.AddAutoMapper();
            services.AddTransient<RolesAuthorizationMiddleware>();

            services.AddAuthorization(options =>
            {
                options.AddPolicy("Admin",
                    policy =>
                    {
                        policy.RequireAuthenticatedUser();
                        policy.RequireClaim(ClaimTypes.Role, "Admin");
                    });
            });
            services.Configure<IISOptions>(options =>
            {
                options.AutomaticAuthentication = true;
            });
            services.AddAuthentication(IISDefaults.AuthenticationScheme);

        }
```

### Version: x.y.z
6.2

### Expected behavior

Mapped Profiles

### Actual behavior
```
AutoMapper.AutoMapperConfigurationException: 
Unmapped members were found. Review the types and members below.
Add a custom mapping expression, ignore, add a custom resolver, or modify the source/destination type
For no matching constructor, add a no-arg ctor, add optional arguments, or map all of the constructor parameters
=======================================================================================================================================================================================================
EntityQueryable`1 -> BlogViewModel (Destination member list)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[Brownbag.Data.Models.Blog, Brownbag.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> Brownbag.Web.Models.BlogViewModel (Destination member list)

Unmapped properties:
Id
Url
Rating

   at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps)
   at lambda_method(Closure , EntityQueryable`1 , BlogViewModel , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source)
   at Brownbag.Web.Controllers.BlogController.Read(Int32 currentPage, Int32 rows, String searchQuery) in C:\Dev\Dotnetcore2EFAngularCliTemplate\brownbags\Brownbag.Web\Controllers\BlogController.cs:line 52
```
Mentions that profiles are not found and there are unmapped 
### Steps to reproduce

```csharp
git clone https://github.com/dhruvb14/AutomapperIssue
Open Brownbag.sln in VS
open package manager and switch to brownbag.data project
run 'update-database'
start application 
click blog tab.
**OR**
try and hit /api/blog/test or /api/blog/test2 and see automapper can't find profiles
```

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection

**Comment by lbargaoanu** [comment]
@jbogard Maybe remove the overload without parameters? :)

**Comment by jbogard** [comment]
It's a `params` array so....yeah

**Comment by dhruvb14** [comment]
So I'm a little confused since I have 2 other projects using this exact setup including have EF Models located in another solution and they seem to all be working fine. Also my profiles are located in the same solution as the startup.cs so it shouldn't even be an issue with going to another assembly. Did I miss something?
