### ISSUE TITLE
Regression: Exception during Expression Builder Map Creation

### ISSUE THREAD

**Issue by Tornhoof** [AutoMapper/AutoMapper#2661]
I'm actually not certain how to call the part where it crashes, Expression Builder Map Creation?
I use the ``ExpressionBuilder.GetMapExpression`` to get the lambda expression for the map between both types and then use ExpressionVisitors to find out which types are mapped (used for loading only the relevant data from the db, i.e. only the mapped parts are loaded).

### Source/destination types

```csharp
public class ParentReference {}

public class ParentReferenceModel {}

public class ChildObject : BaseObject
{
    public List<ParentReference> ParentReferences { get; set; } = new List<ParentReference>();
}

public class MyObject : BaseObject
{
    public string Name { get; set; }
    public List<ChildObject> Children { get; set; } = new List<ChildObject>();

}

public class Model : BaseModel
{
    public string Name { get; set; }
    public List<BaseModelWithParent> Children { get; set; } = new List<BaseModelWithParent>();
}

public class BaseModelWithParent : BaseModel
{
    public ParentReferenceModel Parent { get; set; }
}


public abstract class BaseObject {}

public abstract  class BaseModel
{
    public string CalculatedValue { get; set; }
}

public static class Calculator
{
    public static string Calculate(BaseObject input)
    {
        return "Hello World";
    }
}

```

### Mapping configuration

```csharp
CreateMap<ParentReference, ParentReference>();
CreateMap<BaseObject, BaseModel>()
    .ForMember(a => a.CalculatedValue, e => e.MapFrom(f => Calculator.Calculate(f))); // <-- here it crashes
CreateMap<MyObject, Model>().IncludeBase<BaseObject, BaseModel>()
    .ForMember(a => a.Name, e => e.MapFrom(f => f.Name));
CreateMap<ChildObject, BaseModelWithParent>().IncludeBase<BaseObject, BaseModel>()
    .ForMember(a => a.Parent, e => e.MapFrom(f => f.ParentReferences.FirstOrDefault())); // <-- this line results in the exception
```

### Version: x.y.z
7.0.0, does not happen in 6.2.2

### Expected behavior
- I get the mapped expression back,

### Actual behavior
Following Exception
```csharp
System.ArgumentException
  HResult=0x80070057
  Message=Expression of type 'Proxy_System.Object___Parent_1910784887' cannot be used for parameter of type 'AutomapperRepro.BaseObject' of method 'System.String Calculate(AutomapperRepro.BaseObject)'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at System.Linq.Expressions.MethodCallExpression1.Rewrite(Expression instance, IReadOnlyList`1 args)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.FirstPassLetPropertyMaps.<>c__DisplayClass10_0.<GetSubQueryExpression>g__ReplaceSubQueries|2()
   at AutoMapper.QueryableExtensions.ExpressionBuilder.FirstPassLetPropertyMaps.GetSubQueryExpression(ExpressionBuilder builder, Expression projection, TypeMap typeMap, ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.Impl.EnumerableExpressionBinder.BindEnumerableExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.<>c__DisplayClass15_0.<CreateMemberBindings>g__CreateMemberBinding|0(PropertyMap propertyMap)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutomapperRepro.Program.Main(String[] args) in c:\users\tornhoof\documents\visual studio 2017\Projects\AutomapperRepro\AutomapperRepro\Program.cs:line 16
```

### Steps to reproduce

Full repro below, just execute 
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using AutoMapper;
using AutoMapper.Configuration;

namespace AutomapperRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            var configuration = new MapperConfiguration(cfg => cfg.AddProfile(typeof(TestProfile)));
            var mapper = configuration.CreateMapper();
            var expression = configuration.ExpressionBuilder.GetMapExpression(typeof(MyObject), typeof(Model), new Dictionary<string, object>(), Array.Empty<MemberInfo>());
        }
    }


    public class TestProfile : Profile
    {
        public TestProfile()
        {
            CreateMap<ParentReference, ParentReference>();
            CreateMap<BaseObject, BaseModel>()
                .ForMember(a => a.CalculatedValue, e => e.MapFrom(f => Calculator.Calculate(f))); // <-- here it crashes
            CreateMap<MyObject, Model>().IncludeBase<BaseObject, BaseModel>()
                .ForMember(a => a.Name, e => e.MapFrom(f => f.Name));
            CreateMap<ChildObject, BaseModelWithParent>().IncludeBase<BaseObject, BaseModel>()
                .ForMember(a => a.Parent, e => e.MapFrom(f => f.ParentReferences.FirstOrDefault())); // <-- this line results in the exception
        }
    }

    public class ParentReference
    {

    }

    public class ParentReferenceModel
    {

    }

    public class ChildObject : BaseObject
    {
        public List<ParentReference> ParentReferences { get; set; } = new List<ParentReference>();
    }

    public class MyObject : BaseObject
    {
        public string Name { get; set; }
        public List<ChildObject> Children { get; set; } = new List<ChildObject>();

    }

    public class Model : BaseModel
    {
        public string Name { get; set; }
        public List<BaseModelWithParent> Children { get; set; } = new List<BaseModelWithParent>();
    }

    public class BaseModelWithParent : BaseModel
    {
        public ParentReferenceModel Parent { get; set; }
    }


    public abstract class BaseObject
    {

    }

    public abstract  class BaseModel
    {
        public string CalculatedValue { get; set; }
    }

    public static class Calculator
    {
        public static string Calculate(BaseObject input)
        {
            return "Hello World";
        }
    }
}

```

**Comment by lbargaoanu** [comment]
Actually your mapping seems too complicated for ProjectTo. IncludeBase, MapFrom functions... A repro would have to work with ProjectTo and EF6.

**Comment by Tornhoof** [comment]
I don't really follow, no I don't use ProjectTo (no EF6/Core). If you say GetMapExpression is not part of the public api surface, ok that's valid. I'll see that I fix it myself.

**Comment by lbargaoanu** [comment]
You got it :)

**Comment by Tornhoof** [comment]
Looking at the relevant changes to it, is in ProjectTo() supported to call a method on one of the types?, because in your pull request you replace the real type of the proxy with an approximation of the type with the properties, this will always fail as soon as you have a method in there which assumes the type.

**Comment by Tornhoof** [comment]
Ok, took me a bit longer to actually validate the fix in my solution (copying around local nuget feeds is ugly...), PR #2662 should fix the problem.
