### ISSUE TITLE
Exception while using IQueryable Extension "ProjectTo" with Objects using ISet/HashSet

### ISSUE THREAD

**Issue by greenlight2k** [AutoMapper/AutoMapper#2678]
I was using the IQueryable-Extension 'ProjectTo' on some random tests and encountered this issue,
but only if the destination type has a property with generic type ISet/HashSet.
This problem does **not** occur, if the destination is using IList/List insted of ISet/HashSet.

### Source/destination types

Source:
```csharp
public class Tree
{
    public string Name { get; set; }
    public Tree Parent { get; set; }
    public ISet<Tree> Children { get; set; } = new HashSet<Tree>();
}
```

Destination:
```csharp
public class TreeDto
{
    public string Name { get; set; }
    public TreeDto Parent { get; set; }

    // comment out following line and uncomment second line - exception will not occur
    public ISet<TreeDto> Children { get; set; } = new HashSet<TreeDto>();
    //public IList<TreeDto> Children { get; set; } = new List<TreeDto>();
}
```

### Steps to reproduce

```csharp
// configure AutoMapper
Mapper.Initialize(cfg =>
{
    cfg.CreateMap<Tree, TreeDto>().PreserveReferences();
});

// create Parent and Child and connect their relation
var parent = new Tree
{
    Name = "Parent"
};

var child = new Tree
{
    Name = "Child",
    Parent = parent
};

parent.Children.Add(child);

// regular mapping works as expected
var mapped = Mapper.Map<TreeDto>(parent);


// create list with parent and convert it to IQueryable<Tree>
var list = new List<Tree>
{
    parent
};

var queryable = list.AsQueryable();

// throws exception
var projectedList = queryable.ProjectTo<TreeDto>().ToList();
```

### Exception

```
Exception thrown: 'System.ArgumentException' in mscorlib.dll
System.ArgumentException: Argument types do not match
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at AutoMapper.QueryableExtensions.Impl.EnumerableExpressionBinder.BindEnumerableExpression(IConfigurationProvider configuration, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.Impl.EnumerableExpressionBinder.Build(IConfigurationProvider configuration, PropertyMap propertyMap, TypeMap propertyTypeMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.<>c__DisplayClass15_0.<CreateMemberBindings>g__CreateMemberBinding|0(PropertyMap propertyMap)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpressionCore(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps, TypeMap& typeMap)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.CreateMapExpression(ExpressionRequest request)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at AutoMapper.LockingConcurrentDictionary`2.GetOrAdd(TKey key)
   at AutoMapper.QueryableExtensions.ExpressionBuilder.GetMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, MemberInfo[] membersToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, Expression`1[] membersToExpand)
```

I do not know if this is a bug or the ISet/HashSet is simply not yet supported by this Extension.

**Comment by lbargaoanu** [comment]
ProjectTo is supposed to be used with databases. And recursive structures and relational databases don't really mix.

**Comment by greenlight2k** [comment]
> lbargaoanu:
ProjectTo is supposed to be used with databases. And recursive structures and relational databases don't really mix.

That may be true but it is not the issue here.
I can use a regular one-to-many relation for another example:

### Source/destination types

Sources:
```csharp
public class Customer
{
    public ISet<Order> Orders { get; set; } = new HashSet<Order>();
}

public class Order
{
    public Customer Customer { get; set; }
}
```

Destinations:
```csharp
public class CustomerDto
{
    // comment out following line and uncomment second one - exception will not occur
    public ISet<OrderDto> Orders { get; set; } = new HashSet<OrderDto>();
    //public IList<OrderDto> Orders { get; set; } = new List<OrderDto>();
}

public class OrderDto
{
    public CustomerDto Customer { get; set; }
}
```

### Steps to reproduce

```csharp
// Configure AutoMapper
Mapper.Initialize(cfg =>
{
    cfg.CreateMap<Customer, CustomerDto>();
    cfg.CreateMap<Order, OrderDto>();
});

// create empty customer object
var customer = new Customer();

// Mapping works as expected
var mapped = Mapper.Map<CustomerDto>(customer);

// Create list and convert it to IQueryable<Customer>
var list = new List<Customer>
{
    customer
};

var queryable = list.AsQueryable();

// Throws exception
var projectedList = queryable.ProjectTo<CustomerDto>().ToList();
```

As you can see, the customer object isn't even filled with any orders. The very same exception is thrown.
Only if i use a IList/List instead of ISet/HashSet on the destination type, the exception will not occur and the projection works as expected.

Also, the exception will be thrown regardless of using a NHibernate Session IQueryable or a IQueryable created by the Linq-Extension AsQueryable(); from a List.

**Comment by lbargaoanu** [comment]
OK then, what would the manual projection look like with EF6?

**Comment by jbogard** [comment]
@greenlight2k We mainly target EF6, but to be sure you'll need to test the projection manually using NHibernate first. It's really not important if a projection works via in-memory collections, but instead if your query provider can actually handle those types. If NH can't support sets in LINQ projections, there's no point in us supporting them.

**Comment by greenlight2k** [comment]
@jbogard I see your point. I'm not quite sure how this actually works, though...
Since im on NHibernate and not EntityFramework, i can not test it.
I just stumbled upon this exception while experimenting with this ProjectTo Extention and NHibernate.
So, to make sure, this is not a NHibernate problem, i used the AsQueryable() Extension from .NET itself (System.Linq.Queryable) to create a generic IQueryable from a generic List.
Isn't this the actual query-provider in that case (.NET itself)? 
What am I missing here?

**Comment by lbargaoanu** [comment]
Test it in NHibernate without AutoMapper. EF6 doesn't support it.

**Comment by lbargaoanu** [comment]
Anyway, this can be done outside AM with a custom [EnumerableExpressionBinder](https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/QueryableExtensions/Impl/EnumerableExpressionBinder.cs) or smth similar, like [this](https://github.com/AutoMapper/AutoMapper/blob/master/src/UnitTests/Projection/BindersAndResultConverters.cs).

**Comment by greenlight2k** [comment]
I see now where this is coming from. The static Enumerable class, like it is used in the EnumerableExpressionBinder, simply does not have a method like "ToMap" or "ToHashMap".
Neither List nor HashSet is an Array, so it will always Call the "ToList" method.
You would have to do a workaround to check for ISet's and other stuff.
That would be impossible, since anyone can implement his own IEnumerable.
Now i get it! Thank you.
