### ISSUE TITLE
Cannot map property with abstract class

### ISSUE THREAD

**Issue by fubar-coder** [AutoMapper/AutoMapper#2701]
### Source/destination types

```csharp
using Newtonsoft.Json.Linq;

class TestClass1
{
    public JToken Token { get; set; }
}

class TestClass2
{
    public JToken Token { get; set; }
}
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
{
    cfg
        .CreateMap<TestClass1, TestClass2>()
        .ForMember(x => x.Token, opt =>
        {
            opt.AllowNull();
            opt.ResolveUsing(x => x.Token);
        });
});
```

### Expected behavior

Copying the `Token` property value directly to the destination without an exception.

### Actual behavior

An `ArgumentException` gets thrown:

```text
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
TestClass1 -> TestClass2
AutoMapperTests.Program+TestClass1 -> AutoMapperTests.Program+TestClass2

Type Map configuration:
TestClass1 -> TestClass2
AutoMapperTests.Program+TestClass1 -> AutoMapperTests.Program+TestClass2

Property:
Token ---> System.ArgumentException: Cannot create an instance of abstract type Newtonsoft.Json.Linq.JToken.
Parameter name: type
   at lambda_method(Closure , TestClass1 , TestClass2 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , TestClass1 , TestClass2 , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 207
   at AutoMapperTests.Program.Main(String[] args) in D:\Test-Projekte\AutoMapperTests\AutoMapperTests\Program.cs:line 25
```

### Steps to reproduce

```csharp
var mapper = config.CreateMapper();
var result = mapper.Map<TestClass2>(new TestClass1());
```

### Execution plan

```text
.Lambda #Lambda1<System.Func`4[AutoMapperTests.Program+TestClass1,AutoMapperTests.Program+TestClass2,AutoMapper.ResolutionContext,AutoMapperTests.Program+TestClass2]>(
    AutoMapperTests.Program+TestClass1 $src,
    AutoMapperTests.Program+TestClass2 $dest,
    AutoMapper.ResolutionContext $ctxt) {
    .Block(AutoMapperTests.Program+TestClass2 $typeMapDestination) {
        .If ($src == null) {
            .Default(AutoMapperTests.Program+TestClass2)
        } .Else {
            .Block() {
                $typeMapDestination = ($dest ?? .New AutoMapperTests.Program+TestClass2());
                .Try {
                    .Block<System.Void>() {
                        .Block(
                            Newtonsoft.Json.Linq.JToken $resolvedValue,
                            Newtonsoft.Json.Linq.JToken $propertyValue) {
                            .Block() {
                                $resolvedValue = .Invoke (.Constant<AutoMapper.Configuration.MemberConfigurationExpression`3+<>c__DisplayClass16_0`1[AutoMapperTests.Program+TestClass1,AutoMapperTests.Program+TestClass2,Newtonsoft.Json.Linq.JToken,Newtonsoft.Json.Linq.JToken]>(AutoMapper.Configuration.MemberConfigurationExpression`3+<>c__DisplayClass16_0`1[AutoMapperTests.Program+TestClass1,AutoMapperTests.Program+TestClass2,Newtonsoft.Json.Linq.JToken,Newtonsoft.Json.Linq.JToken]).resolver)($src)
                                ;
                                $propertyValue = .If ($resolvedValue == null) {
                                    .Block() {
                                        .Throw .Constant<System.ArgumentException>(System.ArgumentException: Cannot create an instance of abstract type Newtonsoft.Json.Linq.JToken.
Parameter name: type);
                                        null
                                    }
                                } .Else {
                                    $resolvedValue
                                };
                                $typeMapDestination.Token = $propertyValue
                            }
                        }
                    }
                } .Catch (System.Exception $ex) {
                    .Throw .New AutoMapper.AutoMapperMappingException(
                        "Error mapping types.",
                        $ex,
                        .Constant<AutoMapper.TypePair>(AutoMapper.TypePair),
                        .Constant<AutoMapper.TypeMap>(AutoMapper.TypeMap),
                        .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap))
                };
                $typeMapDestination
            }
        }
    }
}
```

### Additional information

It did work in 6.1.1, but not in 6.2.0 anymore. This is the 6.1.1 execution plan:

```text
.Lambda #Lambda1<System.Func`4[AutoMapperTests.Program+TestClass1,AutoMapperTests.Program+TestClass2,AutoMapper.ResolutionContext,AutoMapperTests.Program+TestClass2]>(
    AutoMapperTests.Program+TestClass1 $src,
    AutoMapperTests.Program+TestClass2 $dest,
    AutoMapper.ResolutionContext $ctxt) {
    .Block(AutoMapperTests.Program+TestClass2 $typeMapDestination) {
        .If ($src == .Default(AutoMapperTests.Program+TestClass1)) {
            .Default(AutoMapperTests.Program+TestClass2)
        } .Else {
            .Block() {
                $typeMapDestination = ($dest ?? .New AutoMapperTests.Program+TestClass2());
                .Try {
                    .Block<System.Void>() {
                        .Block(
                            Newtonsoft.Json.Linq.JToken $resolvedValue,
                            Newtonsoft.Json.Linq.JToken $propertyValue) {
                            .Block() {
                                $resolvedValue = .Invoke (.Constant<AutoMapper.Configuration.MemberConfigurationExpression`3+<>c__DisplayClass16_0`1[AutoMapperTests.Program+TestClass1,AutoMapperTests.Program+TestClass2,Newtonsoft.Json.Linq.JToken,Newtonsoft.Json.Linq.JToken]>(AutoMapper.Configuration.MemberConfigurationExpression`3+<>c__DisplayClass16_0`1[AutoMapperTests.Program+TestClass1,AutoMapperTests.Program+TestClass2,Newtonsoft.Json.Linq.JToken,Newtonsoft.Json.Linq.JToken]).resolver)($src)
                                ;
                                $propertyValue = .If ($resolvedValue == null) {
                                    .Default(Newtonsoft.Json.Linq.JToken)
                                } .Else {
                                    $resolvedValue
                                };
                                $typeMapDestination.Token = $propertyValue
                            }
                        }
                    }
                } .Catch (System.Exception $ex) {
                    .Throw .New AutoMapper.AutoMapperMappingException(
                        "Error mapping types.",
                        $ex,
                        .Constant<AutoMapper.TypePair>(AutoMapper.TypePair),
                        .Constant<AutoMapper.TypeMap>(AutoMapper.TypeMap),
                        .Constant<AutoMapper.PropertyMap>(AutoMapper.PropertyMap))
                };
                $typeMapDestination
            }
        }
    }
}
```

**Comment by lbargaoanu** [comment]
cfg.CreateMap<TestClass1, TestClass2>();
		cfg.AllowNullCollections = true;

**Comment by fubar-coder** [comment]
@lbargaoanu Thanks, that was the missing piece.

**Comment by lbargaoanu** [comment]
Yes, but the rest of the configuration can be removed.

**Comment by fubar-coder** [comment]
I was under the impression, that `AllowNull` might be required to allow null collections.

**Comment by lbargaoanu** [comment]
No, that's a hack to skip some null checks for ProjectTo. Unrelated :)
