### ISSUE TITLE
Is there a way to use EF.CompileQuery with ProjectTo?

### ISSUE THREAD

**Issue by danobri** [AutoMapper/AutoMapper#2705]
I have some complicated queries/mappings in my project, and would like to pre-compile these queries rather than wait for the for the compilation to occur on the first execution, as it can take quite a long time.  I use the ProjectTo AutoMapper extension throughout the application, and would like to be able to do something like this:

```csharp
var query = EF.CompileQuery((MyProjectContext db, int id) =>
  db.Product.ProjectTo<Models.Product>().FirstOrDefault(p => p.Id == id)
);
var product = query(context, 1);
```
But get the following error:

```csharp
Test method MyProject.Test.MappingTest.ProductGetPreCompile threw exception: 
System.NotSupportedException: Could not parse expression 'value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[MyProject.Data.Entities.Product]).ProjectTo(value(System.Linq.Expressions.Expression`1[System.Func`2[MyProject.Web.Models.Product,System.Object]][]))': This overload of the method 'AutoMapper.QueryableExtensions.Extensions.ProjectTo' is currently not supported.
    at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.GetNodeType(MethodCallExpression expressionToParse)
at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseNode(Expression expression, String associatedIdentifier)
at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseTree(Expression expressionTree)
at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CreateCompiledQuery[TResult](Expression query)
at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQuery`2.CreateCompiledQuery(IQueryCompiler queryCompiler, Expression expression)
at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.<>c__DisplayClass6_0.<EnsureExecutor>b__0(TContext c, LambdaExpression q)
at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam1,TParam2,TValue](TValue& target, TParam1 param1, TParam2 param2, Func`3 valueFactory)
at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.EnsureExecutor(TContext context)
at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, CancellationToken cancellationToken, Object[] parameters)
at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryBase`2.ExecuteCore(TContext context, Object[] parameters)
at MyProject.Test.MappingTest.ProductGetPreCompile() in C:\projects\MyCompany\MyCustomer\MyProject\MyProject.Test\MappingTest.cs:line 47
```
Is there a way to use EF.CompileQuery with Automapper?

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). That's what you have to pass to CompileQuery, not the ProjectTo call itself.

**Comment by danobri** [comment]
Thanks for the prompt reply!  So do I understand correctly that you are saying to use the ReadableExpressions library to get the generated expression code, and call EF.CompileQuery on that?  So each time the mapping changes, you would need to regenerate the expression code and update the corresponding compiled query?

**Comment by lbargaoanu** [comment]
No. That's just a nice way to see the generated expression.

**Comment by danobri** [comment]
So you are saying you can get the expression at run time, and pass that to the CompileQuery call?  Would you be wiling to provide a code snippet to clarify?  I can't seem to get that working with the example above.

**Comment by lbargaoanu** [comment]
That you'll have to figure out yourself.

**Comment by danobri** [comment]
But you believe it is possible to grab the expression at runtime, and compile?  Something like this:

```csharp
var expression = db.Product.ProjectTo<Models.Product>().Expression;
var query = EF.CompileQuery((MyProjectContext db) =>
  expression
);
var products = query(context);
```

**Comment by lbargaoanu** [comment]
Yes, that's the idea.
