### ISSUE TITLE
UseAsDataSource with GroupBy

### ISSUE THREAD

**Issue by bizunas** [AutoMapper/AutoMapper#2721]
Moved to [UseAsDataSource with GroupBy](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/6)

AutoMapper: 7.0.1
AutoMapper.Extensions.ExpressionMapping: 1.0.2

I'm trying to make use of UseAsDataSource with GroupBy but it fails. Gist is here: [gist](https://gist.github.com/bizunas/d8e8e20530de32d8537988d1de3ee15b)
Where and OrderBy works like a charm. I have tried using GroupBy before UseAsDataSource with Entity objects, and it works. Is there a way to group data with UseAsDataSource ? 

Note: Adding `cfg.AddExpressionMapping();` does not help.

StackTrace: 
```
at System.ThrowHelper.ThrowWrongValueTypeArgumentException(Object value, Type targetType) 
at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item) 
at AutoMapper.Extensions.ExpressionMapping.Impl.SourceInjectedQueryProvider`2.Execute[TResult](Expression expression) 
at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.GetEnumerator()
at AutoMapper.Extensions.ExpressionMapping.Impl.SourceSourceInjectedQuery`2.System.Collections.IEnumerable.GetEnumerator()
at UserQuery.Main(String[] args)
--
```
Message: 
```
The value "System.Linq.Lookup`2+Grouping[System.Int32,UserQuery+Model]" is not of type "System.Linq.IGrouping`2[System.Int32,UserQuery+ModelDto]" and cannot be used in this generic collection.Parameter name: value
--
```

**Comment by bizunas** [comment]
Moved to [UseAsDataSource with GroupBy](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/issues/6)
