### ISSUE TITLE
AutoMapper 7.0.1 not working with ILmerge

### ISSUE THREAD

**Issue by dzeitlin** [AutoMapper/AutoMapper#2734]
Trying to read assembly from the file 'XXXXXX\AutoMapper.dll'.
        Successfully read in assembly.
        There were errors reported in AutoMapper's metadata.
        **Array dimensions exceeded supported range**.
  An exception occurred during merging:
  ILMerge.Merge:        There were errors reported in AutoMapper's metadata.
        Array dimensions exceeded supported range.
     at ILMerging.ILMerge.Merge()
     at ILMerging.ILMerge.Main(String[] args)

with previous version 6.2.2 all was fine and merged correctly.

We must ILmerge all our assemblies.
Thanks

**Comment by lbargaoanu** [comment]
Feel free to investigate. We don't use IL Merge for anything.

**Comment by dzeitlin** [comment]
We found the problem, it was related to portable PDB you are using. ILmerge doesn't support these yet.
Deleteting `AutoMapper.pdb` solves this problem.
