### ISSUE TITLE
Is it possible to create generic Profile

### ISSUE THREAD

**Issue by Jenan** [AutoMapper/AutoMapper#2768]
### Source/destination types

```csharp
public class UserDto<TKey>
    {
        public TKey UserId { get; set; }

        public string UserName { get; set; }
    }

public class User<TKey>
    {
        public TKey Id { get; set; }

        public string UserName { get; set; }
    }

public class MyUser : User<int>
    {
        public string Email { get; set; }
    }

public class MyUserDto : UserDto<int>
    {
        public string Email { get; set; }
    }
```

### Mapping configuration

```csharp
services.AddAutoMapper(config =>
{
config.AddProfile<UserMappingProfile<MyUserDto, int, MyUser, int>>();
});
```
I have tried to create following generic Profile:

```csharp
public class UserMappingProfile<TUserDto, TUserDtoKey, TUser, TUserKey> : Profile 
        where TUserDto : UserDto<TUserDtoKey>
        where TUser : User<TUserKey>
    {
        public UserMappingProfile()
        {
            CreateMap<TUserDto, TUser>(MemberList.Destination)
                .ForMember(x => x.Id, opts => opts.MapFrom(x => x.UserId));
        }
    }
```

### Expected behavior

I have used following for mapping in controller:
```
var myUser = new MyUser
            {
                Id = 1,
                UserName = "Test",
                Email = "test@test.com"
            };

var myUserDto = _mapper.Map<MyUserDto>(myUser);
```

### Actual behavior
But after starting the application I get this error:

```
$exception {System.ArgumentException: Cannot create an instance of GenericMapping.Mapping.UserMappingProfile`4[TUserDto,TUserDtoKey,TUser,TUserKey] because Type.ContainsGenericParameters is true.
   at System.RuntimeType.CreateInstanceCheckThis()
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at AutoMapper.Configuration.MapperConfigurationExpression.AddProfile(Type profileType) in C:\projects\automapper\src\AutoMapper\Configuration\MapperConfigurationExpression.cs:line 44
   at AutoMapper.ServiceCollectionExtensions.<>c__DisplayClass10_0.<AddAutoMapperClasses>g__ConfigAction|4(IMapperConfigurationExpression cfg) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 83
   at AutoMapper.MapperConfiguration.Build(Action`1 configure) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 307
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`1 additionalInitAction, IEnumerable`1 assembliesToScan) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 89
   at GenericMapping.Startup.ConfigureServices(IServiceCollection services) in C:\Projects\GenericMapping\GenericMapping\Startup.cs:line 37}	System.ArgumentException
```

How can I solve this issue?
Thx.

**Comment by lbargaoanu** [comment]
You can make the generic class abstract and define statically concrete profile classes and then you don't need AddProfile anymore. Anyway this is a question for the DI repository.

**Comment by Jenan** [comment]
Something like services.AddMyService<MyUserDto, int, MyUser, int>;

**Comment by lbargaoanu** [comment]
As far a I can tell, you must not include the generic type in an assembly scanned by AddAutomapper. And then you can use AddProfile your way. But that code is not in this repository.

**Comment by lbargaoanu** [comment]
If you're interested in solving this yourself, @jbogard would most likely accept a PR in the DI repository that would skip generic profiles types, the same as it skips abstract types.

**Comment by jbogard** [comment]
@Jenan yep can you open an issue in the DI repo? This is an issue with that code that scans for profiles.
