### ISSUE TITLE
System.InvalidOperationException: 'Mapper not initialized. ...'

### ISSUE THREAD

**Issue by hellfirehd** [AutoMapper/AutoMapper#2822]
I've been fighting with this for a few hours now...

Standard green ASP.NET Core Web App.  In `ConfigureServices` I call...

```csharp
 services.AddAutoMapper(typeof(Startup));
 Mapper.AssertConfigurationIsValid();
```

Which throws:

```text
System.InvalidOperationException
  HResult=0x80131509
  Message=Mapper not initialized. Call Initialize with appropriate configuration. If you are trying to use mapper instances through a container or otherwise, make sure you do not have any calls to the static Mapper.Map methods, and if you're using ProjectTo or UseAsDataSource extension methods, make sure you pass in the appropriate IConfigurationProvider instance.
  Source=AutoMapper
  StackTrace:
   at AutoMapper.Mapper.get_Configuration()
   at AutoMapper.Mapper.AssertConfigurationIsValid()
   at AutoMapperWebApplication.Startup.ConfigureServices(IServiceCollection services) in D:\Source\AutoMapperWebApplication\AutoMapperWebApplication\Startup.cs:line 75
```

Full Repro is here: https://gist.github.com/hellfirehd/3eafe1e222f85a2fdcc7797e51a10b0a.js

**Comment by jbogard** [comment]
That link is bad.

**Comment by hellfirehd** [comment]
My bad. How about this: 

https://gist.github.com/hellfirehd/3eafe1e222f85a2fdcc7797e51a10b0a

**Comment by jbogard** [comment]
Are you calling the static version of AutoMappee?

**Comment by hellfirehd** [comment]
Nothing is being called at that point.  Here's a failing test to go with my gist:

```csharp
[Fact]
public void Should_have_valid_configuration()
{
    var config = A.Fake<IConfiguration>();
    var startup = new Startup(config);
    var services = new ServiceCollection();
    startup.ConfigureServices(services);
    Mapper.AssertConfigurationIsValid();
}
```

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.Microsoft.DependencyInjection#configuration-validation

**Comment by hellfirehd** [comment]
Thanks @lbargaoanu, that helped.  So how would you rewrite that unit test so that it passes?
