### ISSUE TITLE
Cannot create an instance of type ITypeConverter

### ISSUE THREAD

**Issue by reloaded** [AutoMapper/AutoMapper#2825]
### Source/destination types

```csharp

    public abstract class CustomerOffer
    {
        private readonly OfferId _offerId;

        protected CustomerOffer(OfferId offerId)
        {
            _offerId = offerId;
        }

        public OfferId OfferId() => _offerId;
    }

    public class LoanOffer : CustomerOffer
    {
        private readonly IEnumerable<LoanTerm> _preApprovedTerms;
        private readonly IEnumerable<LoanApplyTier> _applyTiers;

        public LoanOffer(
            OfferId offerId, 
            IEnumerable<LoanTerm> preApprovedTerms,
            IEnumerable<LoanApplyTier> applyTiers) : base(offerId)
        {
            _preApprovedTerms = preApprovedTerms;
            _applyTiers = applyTiers;
        }

        public IEnumerable<LoanTerm> PreApprovedTerms() => _preApprovedTerms;

        public IEnumerable<LoanApplyTier> ApplyTiers() => _applyTiers;
    }

    public class OfferId
    {
        private readonly Guid _id;
        private readonly string _type;

        public OfferId(Guid id, string type)
        {
            _id = id;
            _type = type;
        }

        public Guid Id() => _id;

        public string Type() => _type;
   }

    public class LoanApplyTier
    {
        private readonly string _name;
        private readonly int _creditLow;
        private readonly int _creditHigh;
        private readonly IEnumerable<LoanTerm> _terms;

        public LoanApplyTier(string name, int creditLow, int creditHigh, IEnumerable<LoanTerm> terms)
        {
            _name = name;
            _creditLow = creditLow;
            _creditHigh = creditHigh;
            _terms = terms;
        }

        public string Name() => _name;

        public int CreditLow() => _creditLow;

        public int CreditHigh() => _creditHigh;

        public IEnumerable<LoanTerm> Terms() => _terms;
    }

    public class LoanTerm
    {
        private readonly float _minimumAmount;
        private readonly float _maximumAmount;
        private readonly int _term;
        private readonly decimal _apr;

        public LoanTerm(float minimumAmount, float maximumAmount, int term, decimal apr)
        {
            _minimumAmount = minimumAmount;
            _maximumAmount = maximumAmount;
            _term = term;
            _apr = apr;
        }

        public float MinimumAmount() => _minimumAmount;

        public float MaximumAmount() => _maximumAmount;

        public int Term() => _term;

        public decimal Apr() => _apr;
    }

    public class OfferDto
    {
        public Guid OfferId { get; set; }

        public string OfferType { get; set; }
    }

    public class LoanOfferDto : OfferDto
    {
        public IEnumerable<LoanTermDto> PreApprovedTerms { get; set; }

        public IEnumerable<LoanApplyTierDto> ApplyTiers { get; set; }
    }

    public class LoanApplyTierDto
    {
        public CreditBandDto CreditBand { get; set; }
        public IEnumerable<LoanTermDto> Terms { get; set; }
    }

    public class CreditBandDto
    {
        public string Name { get; set; }

        public int CreditLow { get; set; }

        public int CreditHigh { get; set; }
    }

    public class LoanTermDto
    {
        public float MinimumAmount { get; set; }

        public float MaximumAmount { get; set; }

        public int Term { get; set; }

        public decimal Apr { get; set; }
    }
```

### Mapping configuration

```csharp

    public class CustomerOffersProfile : Profile
    {
        public CustomerOffersProfile()
        {
            CreateMap<LoanTerm, LoanTermDto>();
            CreateMap<LoanApplyTier, LoanApplyTierDto>().ConvertUsing<LoanApplyTierConverter>();

            CreateMap<CustomerOffer, OfferDto>()
                .ForMember(dest => dest.OfferId, opts => opts.MapFrom(src => src.OfferId().Id()))
                .ForMember(dest => dest.OfferType, opts => opts.MapFrom(src => src.OfferId().Type()))
                .Include<LoanOffer, LoanOfferDto>();

            CreateMap<LoanOffer, LoanOfferDto>()
                .IncludeBase<CustomerOffer, OfferDto>();
        }

        // ReSharper disable once ClassNeverInstantiated.Global
        // ReSharper disable once MemberCanBePrivate.Global
        public class LoanApplyTierConverter : ITypeConverter<LoanApplyTier, LoanApplyTierDto>
        {
            public LoanApplyTierDto Convert(LoanApplyTier src, LoanApplyTierDto dest, ResolutionContext context)
            {
                return new LoanApplyTierDto
                {
                    CreditBand = new CreditBandDto
                    {
                        CreditHigh = src.CreditHigh(),
                        CreditLow = src.CreditLow(),
                        Name = src.Name()
                    },
                    Terms = src.Terms().Select(t => new LoanTermDto
                    {
                        Term = t.Term(),
                        MinimumAmount = t.MinimumAmount(),
                        MaximumAmount = t.MaximumAmount(),
                        Apr = t.Apr()
                    })
                };
            }
        }
    }
```

### Version: x.y.z
7.0.1

### Expected behavior
Expected automapper to instantiate my custom type converter for some complex mapping.

### Actual behavior
It throws an exception and says it cannot instantiate my custom type converter.

```
Storefront.Api.Controllers.SessionOffersController:Critical: Error mapping types.

Mapping types:
SelectListIterator`2 -> IEnumerable`1
System.Linq.Enumerable+SelectListIterator`2[[Campaign.Dtos.StorefrontCustomerOfferDto, Campaign.Dtos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Storefront.Domain.CustomerOffersService.CustomerOffer, Storefront.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.IEnumerable`1[[Storefront.Dtos.SessionOffers.OfferDto, Storefront.Dtos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]

AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
SelectListIterator`2 -> IEnumerable`1
System.Linq.Enumerable+SelectListIterator`2[[Campaign.Dtos.StorefrontCustomerOfferDto, Campaign.Dtos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Storefront.Domain.CustomerOffersService.CustomerOffer, Storefront.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.IEnumerable`1[[Storefront.Dtos.SessionOffers.OfferDto, Storefront.Dtos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
LoanOffer -> LoanOfferDto
Storefront.Domain.CustomerOffersService.LoanOffer -> Storefront.Dtos.SessionOffers.LoanOfferDto

Type Map configuration:
LoanOffer -> LoanOfferDto
Storefront.Domain.CustomerOffersService.LoanOffer -> Storefront.Dtos.SessionOffers.LoanOfferDto

Property:
ApplyTiers ---> AutoMapper.AutoMapperMappingException: Cannot create an instance of type Storefront.Api.DtoMappers.CustomerOffersProfile+LoanApplyTierConverter
   at AutoMapper.MappingOperationOptions`2.CreateInstance[T]() in C:\projects\automapper\src\AutoMapper\MappingOperationOptions.cs:line 47
   at lambda_method(Closure , CustomerOffer , OfferDto , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , CustomerOffer , OfferDto , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IRuntimeMapper.Map[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, PropertyMap propertyMap) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 370
   at lambda_method(Closure , SelectListIterator`2 , IEnumerable`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , SelectListIterator`2 , IEnumerable`1 , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 207
   at Storefront.Api.Controllers.SessionOffersController.GetCustomerOffers(Guid sessionId) in C:\git\Storefront\Storefront.Api\Controllers\SessionOffersController.cs:line 44
Storefront.Api.Controllers.SessionOffersController:Critical: Error mapping types.

Mapping types:
SelectListIterator`2 -> IEnumerable`1
System.Linq.Enumerable+SelectListIterator`2[[Campaign.Dtos.StorefrontCustomerOfferDto, Campaign.Dtos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Storefront.Domain.CustomerOffersService.CustomerOffer, Storefront.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.IEnumerable`1[[Storefront.Dtos.SessionOffers.OfferDto, Storefront.Dtos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]

AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
SelectListIterator`2 -> IEnumerable`1
System.Linq.Enumerable+SelectListIterator`2[[Campaign.Dtos.StorefrontCustomerOfferDto, Campaign.Dtos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Storefront.Domain.CustomerOffersService.CustomerOffer, Storefront.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] -> System.Collections.Generic.IEnumerable`1[[Storefront.Dtos.SessionOffers.OfferDto, Storefront.Dtos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
LoanOffer -> LoanOfferDto
Storefront.Domain.CustomerOffersService.LoanOffer -> Storefront.Dtos.SessionOffers.LoanOfferDto

Type Map configuration:
LoanOffer -> LoanOfferDto
Storefront.Domain.CustomerOffersService.LoanOffer -> Storefront.Dtos.SessionOffers.LoanOfferDto

Property:
ApplyTiers ---> AutoMapper.AutoMapperMappingException: Cannot create an instance of type Storefront.Api.DtoMappers.CustomerOffersProfile+LoanApplyTierConverter
   at AutoMapper.MappingOperationOptions`2.CreateInstance[T]() in C:\projects\automapper\src\AutoMapper\MappingOperationOptions.cs:line 47
   at lambda_method(Closure , CustomerOffer , OfferDto , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , CustomerOffer , OfferDto , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IRuntimeMapper.Map[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, PropertyMap propertyMap) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 370
   at lambda_method(Closure , SelectListIterator`2 , IEnumerable`1 , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , SelectListIterator`2 , IEnumerable`1 , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 207
   at Storefront.Api.Controllers.SessionOffersController.GetCustomerOffers(Guid sessionId) in C:\git\Storefront\Storefront.Api\Controllers\SessionOffersController.cs:line 44


```

### Steps to reproduce

```csharp

        [HttpGet("all")]
        public async Task<IActionResult> GetCustomerOffers(Guid sessionId)
        {
            try
            {
                var offers =
                    await _offersService.ForSession(sessionId, HttpContext.Connection.RemoteIpAddress.ToString());

                return Ok(new DataListResponse<OfferDto>(_mapper.Map<IEnumerable<OfferDto>>(offers)));
            }
            catch (Exception ex)
            {
                return this.InternalServerError();
            }
        }
```

**Comment by lbargaoanu** [comment]
There's s probably some problem with your DI configuration. I think this is better suited for StackOverflow.

**Comment by reloaded** [comment]
> There's s probably some problem with your DI configuration. I think this is better suited for StackOverflow.

Thanks for the assistance.
