### ISSUE TITLE
Mapping with inheritance does not work due to downcast error.

### ISSUE THREAD

**Issue by PhilipCotan** [AutoMapper/AutoMapper#2832]
I am trying to cast the an object of type `NamespaceB.SearchResult` to `NamespaceA.SearchResult` (exactly the same structure, just different namespace) with the below configurations: 

### Source/destination types

```csharp
namespace AutoMapper_Test.NamespaceA
{
    //Types
    class SearchResult
    {
        public SearchItem[] SearchItems { get; set; }
    }

    class SearchItem
    {
        public BaseProfile Profile { get; set; }
        
        public DerivedProfile[] SubProfiles { get; set; }
    }

    //Property Types
    class BaseProfile
    {
        public string Id { get; set; }
    }

    class DerivedProfile : BaseProfile 
    {
        public string Name { get; set; }
    }
}

//Main
        static void Main(string[] args)
        {
            ConfigureMappings();

            var searchResultBeta = CreateData();
            var searchResult = Mapper.Map<NamespaceA.SearchResult>(searchResultBeta);

            System.Console.WriteLine(searchResult.SearchItems.Length);

            Console.ReadLine();
        }
```

### Mapping configuration

```csharp
public static void ConfigureMappings()
{
    var mappings = new MapperConfigurationExpression();
    mappings.CreateMap<NamespaceA.SearchResult, NamespaceB.SearchResult>();
    Mapper.Initialize(mappings);
}
```

### Exception details

```
Unhandled Exception: AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
SearchResult -> SearchResult
AutoMapper_Test.NamespaceB.SearchResult -> AutoMapper_Test.NamespaceA.SearchResult

Type Map configuration:
SearchResult -> SearchResult
AutoMapper_Test.NamespaceB.SearchResult -> AutoMapper_Test.NamespaceA.SearchResult

Property:
SearchItems ---> AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
SearchItem -> SearchItem
AutoMapper_Test.NamespaceB.SearchItem -> AutoMapper_Test.NamespaceA.SearchItem

Type Map configuration:
SearchItem -> SearchItem
AutoMapper_Test.NamespaceB.SearchItem -> AutoMapper_Test.NamespaceA.SearchItem

Property:
SubProfiles ---> System.InvalidCastException: Unable to cast object of type 'AutoMapper_Test.NamespaceA.BaseProfile' to type 'AutoMapper_Test.NamespaceA.DerivedProfile'.
   at lambda_method(Closure , SearchResult , SearchResult , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , SearchResult , SearchResult , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , SearchResult , SearchResult , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 207
   at AutoMapper_Test.Program.Main(String[] args) in D:\Projects\AutoMapper Test\Program.cs:line 55
```

**Comment by lbargaoanu** [comment]
Set CreateMissingTypeMaps to false and read [this](http://docs.automapper.org/en/latest/Mapping-inheritance.html). But other than that, I think this is better suited for StackOverflow.

**Comment by PhilipCotan** [comment]
Not a very helpful answer. Thought you guys have a hint for this specific downcast situation. Cheers.

**Comment by jbogard** [comment]
If you’ve got a bug to report or feature request, that’s what our issues
are for. Otherwise SO for general questions.
