### ISSUE TITLE
UseAsDataSource with async/await operators

### ISSUE THREAD

**Issue by Luke-1988** [AutoMapper/AutoMapper#2879]
Hi guys,

I am using AutoMapper 7.0.1 with EF Core 2.1 and I would love to use UseAsDataSource with async/await operators. This is my code:

```
var _query = this.IUnitOfWork.IDataCrmRepository.contacts
                                .Where(w => w.org_id == config_org_id)
                                .UseAsDataSource(this.IMapper.ConfigurationProvider)
                                .For<DTO.contact>()
                                ;
// nov order by optional navigation property (address) which may be null    
_query = _query.OrderBy(o => o.address.city);

return _query.ToArray();
```
UseAsDataSource does the job very well, except I want to do SQL in async mode and await result, just like this:

`return await _query.ToArrayAsync();`

This code runs into exception:

```
System.InvalidOperationException: The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IEntityQueryProvider can be used for Entity Framework asynchronous operations.  
  at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)   
  at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.CountAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
```

I could eventually use ProjectTo, but it leads to NullReferenceException because navigation properti _address_ may be null:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , TransparentIdentifier`2 )
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
```

How can I use UseAsDataSource with async/await?

**Comment by lbargaoanu** [comment]
See [this](https://github.com/AutoMapper/AutoMapper/issues/2767#issuecomment-414060736).
