### ISSUE TITLE
AssertConfigurationIsValid fails after upgrade to 8.0

### ISSUE THREAD

**Issue by slubowsky** [AutoMapper/AutoMapper#2889]
Code working using version 7.0.1 fails with exception after upgrade to 8.0. Mapping was using resolver with ResolveUsing which is now changed to MapFrom. AssertConfigurationIsValid seems to not see the mapping. (I dont think my usage is one that is called out by the upgrade guide as a breaking case, and looks to be as shown in documentation - http://docs.automapper.org/en/latest/Custom-value-resolvers.html). I tried with a converter instead of a resolver with same results.

### Source/destination types

```csharp
public class DoctorViewModel
{
    public string FirstName { get; set; }
    ...
}

public class DoctorDetailViewModel : DoctorViewModel
{
    public List<int> DoctorSpecialties { get; set; }
    ...
}

public class Doctor 
{
    public string FirstName { get; set; }
    public ICollection<DoctorSpecialty> DoctorSpecialties { get; set; }
    ...
}

public class DoctorSpecialty
{
    public int SpecialtyId { get; set; }
    ...
}
```

### Mapping configuration

```csharp
// Using Resolver shown, same failure using converter
CreateMap<DoctorDetailViewModel, Doctor>(MemberList.Source)
    .ForMember(dest => dest.DoctorSpecialties, opt => opt.MapFrom<SpecialtyFromIdResolver>());
	
private class SpecialtyFromIdResolver : IValueResolver<DoctorDetailViewModel, Doctor, ICollection<DoctorSpecialty>>
{
    ICollection<DoctorSpecialty> IValueResolver<DoctorDetailViewModel, Doctor, ICollection<DoctorSpecialty>>.Resolve(DoctorDetailViewModel source, Doctor destination, ICollection<DoctorSpecialty> destMember, ResolutionContext context)
    {
        List<DoctorSpecialty> specialties = new List<DoctorSpecialty>();
        source.DoctorSpecialties?.ForEach(s => specialties.Add(new DoctorSpecialty() { SpecialtyId = s }));
        return specialties;
    }
}
```

### Expected behavior

Configuration and mapping should succeed as expected as it does using 7.0.1

### Actual behavior

Get exception:

```
{AutoMapper.AutoMapperConfigurationException: The following property on Doctor cannot be mapped: 
	DoctorSpecialties 
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type Doctor.
Context:
	Mapping to property DoctorSpecialties from DoctorDetailViewModel to Doctor
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.
   at AutoMapper.ConfigurationValidator.DryRunTypeMap(ICollection`1 typeMapsChecked, TypePair types, TypeMap typeMap, PropertyMap propertyMap) in C:\projects\automapper\src\AutoMapper\ConfigurationValidator.cs:line 97}
```

### Steps to reproduce

```csharp
Mapper.AssertConfigurationIsValid();
```

**Comment by lbargaoanu** [comment]
I don't see it. A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by lbargaoanu** [comment]
What's with MemberList.Source? Maybe you want MemberList.None to skip validation? Once you have a repro, we'll take a look.

**Comment by slubowsky** [comment]
MemberList.None didnt help. I use MemberList.Source to avoid having to ignore the many unmapped entity framework navigation properties in my destination model (if I recall correctly)
As I'm unable to reproduce in stand alone small project, for now I'll just work around it using AfterMap. Im sure it will turn up elsewhere and be fixed eventually, but meanwhile we can pretend the issue doesnt exist by closing it.

```
CreateMap<DoctorDetailViewModel, Doctor>(MemberList.Source)
    .ForMember(dest => dest.DoctorSpecialties, opt => opt.Ignore())
    .AfterMap<MapDoctorSpecialtiesAction>();

private class MapDoctorSpecialtiesAction : IMappingAction<DoctorDetailViewModel, Doctor>
{
    public void Process(DoctorDetailViewModel source, Doctor destination)
    {
        List<DoctorSpecialty> specialties = new List<DoctorSpecialty>();
        source.DoctorSpecialties?.ForEach(s => specialties.Add(new DoctorSpecialty() { SpecialtyId = s }));
        destination.DoctorSpecialties = specialties;
    }
}
```

**Comment by slubowsky** [comment]
I notice my last comment was deleted. I apologize if it came across as at all insulting, it certainly wasn't meant that way. Thanks for the great free library!

**Comment by jonsagara** [comment]
I was able to reproduce this in a simple ASP.NET Core 2.1 web application:

https://github.com/jonsagara/AutoMapper8MapFromIssue

Open the solution file and CTRL+F5, and you'll see the configuration exception if you "Show output from: ASP.NET Core Web Server" in the Output window.

As noted above, this worked prior to upgrading to AutoMapper 8.0.0.

Any ideas?

Thanks,

Jon

Startup.cs configuration:
```
services.AddAutoMapper(opts => opts.CreateMissingTypeMaps = false, typeof(Startup));
```

Check AutoMapper Configuration in Program.cs:
```
public static class IWebHostExtensions
    {
        public static IWebHost CheckAutoMapperConfiguration(this IWebHost host)
        {
            using (var scope = host.Services.CreateScope())
            {
                try
                {
                    var mapperConfig = scope.ServiceProvider.GetRequiredService<IConfigurationProvider>();
                    mapperConfig.AssertConfigurationIsValid();
                }
                catch (Exception ex)
                {
                    Console.Error.WriteLine($"Unhandled exception in {nameof(CheckAutoMapperConfiguration)}: {ex}");
                    throw;
                }
            }

            return host;
        }
    }
```

Profile and IValueResolver:
```
public class HomeProfile : Profile
    {
        public HomeProfile()
        {
            CreateMap<HomeIndex.Query, HomeIndex.Command>()
                .ForMember(d => d.Details, o => o.MapFrom<DetailsValueResolver>());
        }
    }

    public class DetailsValueResolver : IValueResolver<HomeIndex.Query, HomeIndex.Command, List<KeyValuePair<string, string>>>
    {
        public List<KeyValuePair<string, string>> Resolve(HomeIndex.Query source, HomeIndex.Command destination, List<KeyValuePair<string, string>> destMember, ResolutionContext context)
        {
            return source.Details
                .Select(d => new KeyValuePair<string, string>(d.ToString(), d.ToString()))
                .ToList();
        }
    }
```

Model declarations:
```
public class HomeIndex
    {
        public class Query : IRequest<Command>
        {
            public List<int> Details { get; private set; } = new List<int>();
        }

        public class Command : IRequest
        {
            public List<KeyValuePair<string, string>> Details { get; private set; } = new List<KeyValuePair<string, string>>();
        }


        public class QueryHandler : IRequestHandler<Query, Command>
        {
            private readonly IMapper _mapper;

            public QueryHandler(IMapper mapper)
            {
                _mapper = mapper;
            }

            public async Task<Command> Handle(Query message, CancellationToken cancellationToken)
            {
                await Task.CompletedTask;

                var command = _mapper.Map<Command>(message);

                return command;
            }
        }
    }
```

Error text output:
```
AutoMapper8MapFromIssue> Unhandled exception in CheckAutoMapperConfiguration: AutoMapper.AutoMapperConfigurationException: The following property on AutoMapper8MapFromIssue.Models.Home.HomeIndex+Command cannot be mapped: 
AutoMapper8MapFromIssue> 	Details 
AutoMapper8MapFromIssue> Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type AutoMapper8MapFromIssue.Models.Home.HomeIndex+Command.
AutoMapper8MapFromIssue> Context:
AutoMapper8MapFromIssue> 	Mapping to property Details from AutoMapper8MapFromIssue.Models.Home.HomeIndex+Query to AutoMapper8MapFromIssue.Models.Home.HomeIndex+Command
AutoMapper8MapFromIssue> Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.
AutoMapper8MapFromIssue>    at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps) in C:\projects\automapper\src\AutoMapper\ConfigurationValidator.cs:line 48
AutoMapper8MapFromIssue>    at AutoMapper8MapFromIssue.IWebHostExtensions.CheckAutoMapperConfiguration(IWebHost host) in C:\Dev\SANDBOX\AutoMapper8MapFromIssue\src\AutoMapper8MapFromIssue\Program.cs:line 33
AutoMapper8MapFromIssue> 
AutoMapper8MapFromIssue> Unhandled Exception: AutoMapper.AutoMapperConfigurationException: The following property on AutoMapper8MapFromIssue.Models.Home.HomeIndex+Command cannot be mapped: 
AutoMapper8MapFromIssue> 	Details 
AutoMapper8MapFromIssue> Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type AutoMapper8MapFromIssue.Models.Home.HomeIndex+Command.
AutoMapper8MapFromIssue> Context:
AutoMapper8MapFromIssue> 	Mapping to property Details from AutoMapper8MapFromIssue.Models.Home.HomeIndex+Query to AutoMapper8MapFromIssue.Models.Home.HomeIndex+Command
AutoMapper8MapFromIssue> Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.
AutoMapper8MapFromIssue>    at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps) in C:\projects\automapper\src\AutoMapper\ConfigurationValidator.cs:line 48
AutoMapper8MapFromIssue>    at AutoMapper8MapFromIssue.IWebHostExtensions.CheckAutoMapperConfiguration(IWebHost host) in C:\Dev\SANDBOX\AutoMapper8MapFromIssue\src\AutoMapper8MapFromIssue\Program.cs:line 33
AutoMapper8MapFromIssue>    at AutoMapper8MapFromIssue.Program.Main(String[] args) in C:\Dev\SANDBOX\AutoMapper8MapFromIssue\src\AutoMapper8MapFromIssue\Program.cs:line 13
```

**Comment by lbargaoanu** [comment]
@jonsagara You can workaround it by not using a class for your resolver.

**Comment by jonsagara** [comment]
Thanks!

**Comment by dipaklazycoder** [comment]
Automapper 8 having issue with unmapped property. I am mapping from source to destination where destination has some fields which i do not want to map.
I am getting error after tried all alternat solution as suggested 

  configuration.CreateMap<Destination, Source>(MemberList.Source).ReverseMap();
  configuration.CreateMap<Source, Destination, >(MemberList.Source);
 configuration.CreateMap<Source, Destination, >(MemberList.Source)
.ForMember(dest=>dest.Id, y=>y.Ignore());



=================
AutoMapper created this type map for you, but your types cannot be mapped using the current configuration.
AddQuestionCommand -> QuestionDm (Destination member list)
UserActivityManagement.Application.Questions.Command.AddQuestion.AddQuestionCommand -> UserActivityManagement.Domain.Entities.QuestionDm (Destination member list)

Unmapped properties:
Id

   at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps) in C:\projects\automapper\src\AutoMapper\ConfigurationValidator.cs:line 48
   at lambda_method(Closure , AddQuestionCommand , QuestionDm , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 211
