### ISSUE TITLE
ProjectTo throws NullReferenceException

### ISSUE THREAD

**Issue by m-demydiuk** [AutoMapper/AutoMapper#2908]
### Bug description
When I try to use ProjectTo it fails with exception

### Mapping configuration

```csharp
var mapperConfig = new MapperConfiguration(cfg =>
{
    cfg.CreateMap<Source, Destination>()
        //this throw's nullreference exception when is used with ProjectTo but works with Mapper.Map
        .ForMember(dest => dest.CountryIso, opts => opts.MapFrom(src =>
                src.User.SchoolUsers.First().School.Country.Iso3 ?? string.Empty));
});
```

### Expected behavior

Should show value from db

### Actual behavior
Exception is thrown `System.NullReferenceException: Object reference not set to an instance of an object.`
```csharp
   at lambda_method(Closure , QueryContext , TransparentIdentifier`2 )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ProjectionShaper.TypedProjectionShaper`3.Shape(QueryContext queryContext, ValueBuffer& valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Additional information
I tried to to configure mapper this way
```csharp
.ForMember(dest => dest.CountryIso, opts => opts.MapFrom(src => 
       src.User.SchoolUsers.First().School.Country == null ? "is null" : "is not null"));
```

and in destination I got all values `is not null`, but if I try to get value from any `Country` property it fails

Any ideas how to solve this?

Thanks in advance.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html). Using the execution plan you can write that query without AM. It might be an EF Core issue.
