### ISSUE TITLE
Issue with mapping to ILookup

### ISSUE THREAD

**Issue by svenschmidt75** [AutoMapper/AutoMapper#2922]
### Source/destination types

```csharp
  internal class Model
    {
        public ILookup<int, string> Data { get; set; }
    }

    internal class ModelDTO
    {
        public IEnumerable<(int, string)> Data { get; set; }
    }
```

### Mapping configuration

```csharp
var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Model, ModelDTO>()
                    .ForMember(dest => dest.Data, opts => opts.MapFrom(new DataToDTOResolver()));
                cfg.CreateMap<ModelDTO, Model>()
                    .ForMember(dest => dest.Data, opts => opts.MapFrom(new DataFromDTOResolver()));
            });
            var mapper = config.CreateMapper();
```

### Version: x.y.z
 
8.0.0

### Expected behavior

```
            var model = new Model
            {
                Data = new Dictionary<int, string>
                {
                    {1, "AGM1"}
                    , {2, "ML1"}
                }.ToLookup(p => p.Key, p => p.Value)
            };
            var modelDTO = mapper.Map<Model, ModelDTO>(model);
            var mappedModel = mapper.Map<ModelDTO, Model>(modelDTO);
```
yields properly initialized Data field on mappedModel.

### Actual behavior

```
Unhandled Exception: AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
ModelDTO -> Model
AutoMapperILookup.ModelDTO -> AutoMapperILookup.Model

Type Map configuration:
ModelDTO -> Model
AutoMapperILookup.ModelDTO -> AutoMapperILookup.Model

Destination Member:
Data
 ---> System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.List`1[System.String]' to type 'System.Linq.IGrouping`2[System.Int32,System.String]'.
   at lambda_method(Closure , ModelDTO , Model , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , ModelDTO , Model , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TSource,TDestination](TSource source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 233
   at AutoMapperILookup.Program.Main(String[] args) in C:\Users\s.schmidt\source\repos\AutoMapperILookup\AutoMapperILookup\Program.cs:line 40
```

### Steps to reproduce

```csharp
using System.Collections.Generic;
using System.Linq;
using AutoMapper;

namespace AutoMapperILookup
{
    internal class Model
    {
        public ILookup<int, string> Data { get; set; }
    }

    internal class ModelDTO
    {
        public IEnumerable<(int, string)> Data { get; set; }
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<Model, ModelDTO>()
                    .ForMember(dest => dest.Data, opts => opts.MapFrom(new DataToDTOResolver()));
                cfg.CreateMap<ModelDTO, Model>()
                    .ForMember(dest => dest.Data, opts => opts.MapFrom(new DataFromDTOResolver()));
            });
            var mapper = config.CreateMapper();


            var model = new Model
            {
                Data = new Dictionary<int, string>
                {
                    {1, "AGM1"}
                    , {2, "ML1"}
                }.ToLookup(p => p.Key, p => p.Value)
            };
            var modelDTO = mapper.Map<Model, ModelDTO>(model);
            var mappedModel = mapper.Map<ModelDTO, Model>(modelDTO);
        }
    }

    internal class DataFromDTOResolver : IValueResolver<ModelDTO, Model, ILookup<int, string>>
    {
        public ILookup<int, string> Resolve(ModelDTO source, Model destination, ILookup<int, string> destMember, ResolutionContext context)
        {
            return source.Data.ToLookup(t => t.Item1, t => t.Item2);
        }
    }

    internal class DataToDTOResolver : IValueResolver<Model, ModelDTO, IEnumerable<(int, string)>>
    {
        public IEnumerable<(int, string)> Resolve(Model source, ModelDTO destination, IEnumerable<(int, string)> destMember, ResolutionContext context)
        {
            return source.Data.SelectMany(grp => { return grp.ToList().Select(s => (grp.Key, s)); }).ToList();
        }
    }
}
```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
But the idea would be to try using type converters instead of value resolvers.

**Comment by svenschmidt75** [comment]
Thank you for the type converter hint, works like a charm.
Maybe the documentation could be improved in this regard as I don;t
think this is obvious. Anyways, thanks again.

**Comment by jbogard** [comment]
Any way we can improve it, let us know!

**Comment by svenschmidt75** [comment]
@jbogard I would suggest adding something to http://docs.automapper.org/en/stable/Custom-value-resolvers.html. Unfortunately, I cannot come up with the text myself, as I don't know why the value converter does not work in the above scenario. Maybe something along the lines of

Add to http://docs.automapper.org/en/stable/Custom-value-resolvers.html:

Note: For certain scenarios (explain why the above fails), using a value converter results in an invalid cast exception. For those cases, please use a type converter instead.

**Comment by lbargaoanu** [comment]
It doesn't work because a resolved value is mapped (not assigned) to the destination property. 
Check [the execution plan](http://docs.automapper.org/en/stable/Understanding-your-mapping.html).
