### ISSUE TITLE
Open generics and untyped MapFrom

### ISSUE THREAD

**Issue by TdMxm** [AutoMapper/AutoMapper#2926]
### Source/destination types

```csharp
        public class Source<T>
        {
            public T Value1 { get; set; }
        }

        public class Destination<T>
        {
            public T Value2 { get; set; }
        }
```

### Mapping configuration

```csharp
 var mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap(typeof(Source<>), typeof(Destination<>))
                    .ForMember("Value2", x => x.MapFrom("Value1"));
            });
```

### Expected behavior

Mappping creation should work and not to throw exception

### Actual behavior

Throwing exception on mapperConfiguration initialization.
```
Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Linq.Expressions.Expression.CreateLambda(Type delegateType, Expression body, String name, Boolean tailCall, ReadOnlyCollection`1 parameters)
   at System.Linq.Expressions.Expression.Lambda(Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at AutoMapper.PropertyMap.MapFrom(String propertyOrField) in C:\projects\automapper\src\AutoMapper\PropertyMap.cs:line 120
   at AutoMapper.Configuration.MemberConfigurationExpression`3.<>c__DisplayClass21_0.<MapFrom>b__0(PropertyMap pm) in C:\projects\automapper\src\AutoMapper\Configuration\MemberConfigurationExpression.cs:line 127
   at AutoMapper.Configuration.MemberConfigurationExpression`3.Apply(PropertyMap propertyMap) in C:\projects\automapper\src\AutoMapper\Configuration\MemberConfigurationExpression.cs:line 335
   at AutoMapper.Configuration.MemberConfigurationExpression`3.Configure(TypeMap typeMap) in C:\projects\automapper\src\AutoMapper\Configuration\MemberConfigurationExpression.cs:line 330
   at AutoMapper.Configuration.MappingExpression`2.Configure(TypeMap typeMap) in C:\projects\automapper\src\AutoMapper\Configuration\MappingExpression.cs:line 579
   at AutoMapper.ProfileMap.BuildTypeMap(IConfigurationProvider configurationProvider, ITypeMapConfiguration config) in C:\projects\automapper\src\AutoMapper\ProfileMap.cs:line 132
   at AutoMapper.ProfileMap.Register(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\ProfileMap.cs:line 107
   at AutoMapper.MapperConfiguration.Seal() in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 325
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 52
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 57
   at Testing.AutoMapperTest.RunTest() in c:\Projects\Sandbox\CancellationTokenDisposing\AutoMapperTest.cs:line 19
   at Testing.Program.Main(String[] args) in c:\Projects\Sandbox\CancellationTokenDisposing\Program.cs:line 12
```

### Steps to reproduce

Just try to run _Test_ method:
```csharp
internal class AutoMapperTest
    {
        public class Source<T>
        {
            public T Value1 { get; set; }
        }

        public class Destination<T>
        {
            public T Value2 { get; set; }
        }

        public static void Test()
        {
            var mapper = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap(typeof(Source<>), typeof(Destination<>))
                    .ForMember("Value2", x => x.MapFrom("Value1"));
            });
        }
    }

**Comment by TdMxm** [comment]
Seems linked with #1427 #1624

**Comment by TdMxm** [comment]
A little bit more complex example:
```
using System.Collections.Generic;
using AutoMapper;
using NUnit.Framework;

namespace Testing
{
    class Program
    {
        static void Main(string[] args)
        {
            TestGenericPropertyMappingInGenericTypesMap();
        }

        public interface ITestA
        {
            int A { get; set; }
        }

        public class TestA : ITestA
        {
            public int A { get; set; }
        }

        public interface ITestB
        {
            int A { get; set; }
        }

        public class TestB : ITestB
        {
            public int A { get; set; }

            private bool Equals(TestB other) => A == other.A;

            public override bool Equals(object obj)
            {
                if (ReferenceEquals(null, obj))
                    return false;
                if (ReferenceEquals(this, obj))
                    return true;
                if (obj.GetType() != this.GetType())
                    return false;
                return Equals((TestB)obj);
            }

            public override int GetHashCode()
            {
                return A;
            }

            public static bool operator ==(TestB left, TestB right)
            {
                return Equals(left, right);
            }

            public static bool operator !=(TestB left, TestB right)
            {
                return !Equals(left, right);
            }
        }

        public class Foo<T>
            where T : ITestA
        {
            public T A { get; set; }
            public T B { get; set; }
        }

        public sealed class Bar<T>
            where T : ITestB
        {
            public T C { get; set; }
            public T D { get; set; }

            private bool Equals(Bar<T> other)
            {
                return EqualityComparer<T>.Default.Equals(C, other.C) && EqualityComparer<T>.Default.Equals(D, other.D);
            }

            public override bool Equals(object obj)
            {
                if (ReferenceEquals(null, obj))
                    return false;
                if (ReferenceEquals(this, obj))
                    return true;
                if (obj.GetType() != this.GetType())
                    return false;
                return Equals((Bar<T>)obj);
            }

            public override int GetHashCode()
            {
                unchecked
                {
                    return (EqualityComparer<T>.Default.GetHashCode(C) * 397) ^ EqualityComparer<T>.Default.GetHashCode(D);
                }
            }

            public static bool operator ==(Bar<T> left, Bar<T> right)
            {
                return Equals(left, right);
            }

            public static bool operator !=(Bar<T> left, Bar<T> right)
            {
                return !Equals(left, right);
            }
        }

        [Test]
        public static void TestGenericPropertyMappingInGenericTypesMap()
        {
            var some = new MapperConfiguration(m =>
            {
                m.CreateMap<ITestA, TestB>();

                m.CreateMap(typeof(Foo<>), typeof(Bar<>))
                    .ForMember("C", to => to.MapFrom("A"))
                    .ForMember("D", to => to.MapFrom("B"));
            });

            var mapper = some.CreateMapper();

            var plainMappingResult = mapper.Map<TestB>(new TestA { A = 5 });

            Assert.AreEqual(plainMappingResult, new TestB { A = 5 });

            var source = new Foo<TestA>
            {
                A = new TestA { A = 5 },
                B = new TestA { A = 10 },
            };

            var dest = mapper.Map<Bar<TestB>>(source);

            Assert.AreEqual(dest.C, new TestB { A = 5 });
            Assert.AreEqual(dest.D, new TestB { A = 10 });
        }
    }
}
```

**Comment by lbargaoanu** [comment]
As a workaround, you can use dynamic with a Func based overload.

**Comment by karl-sjogren** [comment]
@lbargaoanu Care to elaborate on that workaround? I've spent a few hours upgrading to AutoMapper 8 in all our projects but the last one is failing this and I can't figure out what you mean with "use dynamic with a Func based overload".

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by karl-sjogren** [comment]
That worked, thanks.

**Comment by stephenlautier** [comment]
When this will be released?

**Comment by lbargaoanu** [comment]
@stephenlautier You don't _really_ need that overload. You can use `dynamic` instead.

**Comment by stephenlautier** [comment]
@lbargaoanu mm oki.. i didn't get exactly how do you mean with the `dynamic` tho. Can you show me exactly, please?
