### ISSUE TITLE
Ability to unit test a profile that has an `AfterMap` using an `IMappingAction` with dependency injection

### ISSUE THREAD

**Issue by robertmiles3** [AutoMapper/AutoMapper#2956]
### Source/destination types

```csharp
    public class MySourceObject
    {
        public int SourceValue { get; set; }
    }

    public class MyDestinationObject
    {
        public int DestinationValue { get; set; }
    }
```

### Mapping configuration

```csharp
    public interface IDoubler
    {
        int WorkIt(int val);
    }

    public class Doubler : IDoubler
    {
        public int WorkIt(int val) => val * 2;
    }

    public class AutoMapperProfile : Profile
    {
        public AutoMapperProfile()
        {
            CreateMap<MySourceObject, MyDestinationObject>()
                .AfterMap<DoublerAction>();
        }
    }
```

### Version
AutoMapper 8.0.0
AutoMapper.Extensions.Microsoft.DependencyInjection 6.0.0

### Expected behavior

Ability to unit test a mapper that has an `AfterMap` that uses a `IMappingAction` with dependency injection.

### Actual behavior

```
[xUnit.net 00:00:01.00]     Tests.Test.Mapper_DoublerAction [FAIL]
Failed   Tests.Test.Mapper_DoublerAction
Error Message:
 System.MissingMethodException : No parameterless constructor defined for this object.
Stack Trace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at AutoMapper.Configuration.MappingExpression`2.<>c__58`1.<AfterMap>g__AfterFunction|58_0(TSource src, TDestination dest, ResolutionContext ctxt) in C:\projects\automapper\src\AutoMapper\Configuration\MappingExpression.cs:line 448
   at lambda_method(Closure , MySourceObject , MyDestinationObject , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 211
   at Tests.Test.Mapper_DoublerAction() in /Users/robertmiles3/Desktop/automapper/Tests/Test.cs:line 58
```

### Steps to reproduce

```csharp
    public class Test
    {
        [Fact]
        public void Mapper_DoublerAction()
        {
            var mapper = new MapperConfiguration(opts => { opts.AddProfile(typeof(AutoMapperProfile)); }).CreateMapper();
            var src = new MySourceObject { SourceValue = 3 };
            var dest = mapper.Map<MyDestinationObject>(src);
            Assert.Equal(src.SourceValue * 2, dest.DestinationValue);
        }
    }
```

**Comment by lbargaoanu** [comment]
http://docs.automapper.org/en/latest/Dependency-injection.html

**Comment by robertmiles3** [comment]
Since there are no words in your reply, I can only assume you are directing me to the `ConstructServicesUsing` section. Sadly, it offers no real help on what `ObjectFactory.GetInstance` looks like in a unit test scenario.

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
