### ISSUE TITLE
ReflectionTypeLoadException exception when used with Asp.Net Core in-memory TestServer

### ISSUE THREAD

**Issue by smadurange** [AutoMapper/AutoMapper#2973]
I'm using Asp.Net Core 2.2 and AutoMapper.Extensions.Microsoft.DependencyInjection 6.0.0. For testing, I'm using Microsoft.AspNetCore.Mvc.Testing 2.2.0. I have two projects in the solution. One is the System Under Test which is a Asp.Net Core Web Api project and the other is a xUnit testing project.

In the System Under Test, in `Startup.cs` I'm registering Automapper like:

`services.AddAutoMapper();`

Then in the test project, I create a `IWebHostBuilder` like so:

    public IWebHostBuilder GetWebHostBuilder()
    {
         return new WebHostBuilder().UseContentRoot(_contentRoot)
                                           .ConfigureServices(InitializeServiceCollection)
                                           .UseEnvironment(_environment)
                                           .UseConfiguration(GetConfiguration())
                                           .UseStartup(typeof(TStartup));
    }

Here, the `InitializeServiceCollection` is implemented like so:

    private void InitializeServiceCollection(IServiceCollection services)
    {
         var manager = new ApplicationPartManager();
    
         manager.ApplicationParts.Add(new AssemblyPart(_assembly));
         manager.FeatureProviders.Add(new ControllerFeatureProvider());
         manager.FeatureProviders.Add(new ViewComponentFeatureProvider());
    
         services.AddSingleton(manager);
    }

and the `GetConfigurationMethod()`:

```
private IConfiguration GetConfiguration()
{
       return new ConfigurationBuilder().SetBasePath(_contentRoot)
                                             .AddJsonFile(_configFileName)
                                             .Build();
}
```

Then I create the `TestServer` like so:

    var myTestServer = new TestServer(GetWebHostBuilder());

Here I get the exception (full exception below). It gets thrown at `services.AddAutoMapper();` method call in the system under test. However, when I run the system under test on it's own and test it manually with Postman, it's working fine and the object mapping with Automapper is working well too. It just raises the exception in the integration test.

Full exception:

    System.AggregateException : One or more errors occurred. (Unable to load one or more of the requested types.
    Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.2.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.) (The following constructor parameters did not have matching fixture data: TestFixture fixture)
    ---- System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
    Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.2.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
    ---- The following constructor parameters did not have matching fixture data: TestFixture fixture
    
    ----- Inner Stack Trace #1 (System.Reflection.ReflectionTypeLoadException) -----
       at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
       at System.Reflection.RuntimeAssembly.get_DefinedTypes()
       at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
       at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
       at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`2 configAction, IEnumerable`1 assembliesToScan) in xxx\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 72
       at xxx.Startup.ConfigureServices(IServiceCollection services) in xxx\Startup.cs:line 35
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
       at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
       at Microsoft.AspNetCore.TestHost.TestServer..ctor(IWebHostBuilder builder, IFeatureCollection featureCollection)
       at xxx.Tests.TestFixture.InitializeServer() in xxx.Tests\TestFixture.cs:line 67
       at xxx.Tests.TestFixture..ctor() in xxx.Tests\TestFixture.cs:line 31
    ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by smadurange** [comment]
In any case, I figured it out. There seems to be some issue with your `AddAutoMapper()` method. In order to avoid the bad reflective call, I used `AddAutoMapper(Type[] types)` method and it worked okay.
