### ISSUE TITLE
AssertConfigurationIsValid() fails after upgrade to v8.0.0 for mappings using IMemberValueResolver

### ISSUE THREAD

**Issue by rikrak** [AutoMapper/AutoMapper#3011]
I've just upgraded my project o tuse v8 of the NuGet package and I'm experiencing test failures for those tests that make use of MapperConfiguration.AssertConfigurationIsValid().  Note the mappings appear to actually work.

I have created a simple repro project here: https://github.com/rikrak/AutoMapperConfigurationVerificationIssue

### Source/destination types

```csharp
// Put your source/destination types here

    /// <summary> Destination object </summary>
    public class MainModel
    {
        public int? ItemId { get; set; }
    }

    /// <summary> Source object </summary>
    public class MainViewModel
    {
        public ReferenceViewModel Item { get; set; }
    }
    public class ReferenceViewModel
    {
        public int? Id { get; set; }
        public string Name { get; set; }
    }

```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
    public class ApplicationMapperProfile : Profile
    {
        public ApplicationMapperProfile()
        {
            this.CreateMap<MainViewModel, MainModel>()
                // this does not appear to be recognised by the AssertConfigurationIsValid() method
                .ForMember(m => m.ItemId, opts => opts.MapFrom<ResolveNullableIdFromReferenceModel, ReferenceViewModel>(vm => vm.Item));
        }
    }
    public class ResolveNullableIdFromReferenceModel : IMemberValueResolver<object, object, ReferenceViewModel, int?>
    {
        public int? Resolve(object source, object destination, ReferenceViewModel sourceMember, int? destMember, ResolutionContext context)
        {
            return sourceMember?.Id ?? DataConstants.UndefinedId;
        }
    }

    public class ApplicationMapperConfigurationExpression : MapperConfigurationExpression
    {
        public ApplicationMapperConfigurationExpression()
        {
            this.DisableConstructorMapping();
            this.AllowNullCollections = true;
            this.CreateMissingTypeMaps = false; 
        }
    }

```

### Expected behavior

A call to MapperConfiguration.AssertConfigurationIsValid() should not throw.

### Actual behavior

A call to MapperConfiguration.AssertConfigurationIsValid() throws:
Test method AutoMapperVerifyMappings.Tests.Unit.VerifyMappingTests.VerifyConfiguration threw exception: 
```
AutoMapper.AutoMapperConfigurationException: The following property on AutoMapperVerifyMappings.Models.MainModel cannot be mapped: 
	ItemId 
Add a custom mapping expression, ignore, add a custom resolver, or modify the destination type AutoMapperVerifyMappings.Models.MainModel.
Context:
	Mapping to property ItemId from AutoMapperVerifyMappings.Models.MainViewModel to AutoMapperVerifyMappings.Models.MainModel
Exception of type 'AutoMapper.AutoMapperConfigurationException' was thrown.
    at AutoMapper.ConfigurationValidator.AssertConfigurationIsValid(IEnumerable`1 typeMaps) in C:\projects\automapper\src\AutoMapper\ConfigurationValidator.cs:line 48
   at AutoMapperVerifyMappings.Tests.Unit.VerifyMappingTests.VerifyConfiguration() in D:\Dev\Src\AutoMapperConfigurationVerificationIssue\AutoMapperVerifyMappings.Tests.Unit\VerifyMappingTests.cs:line 33
```

### Steps to reproduce
 Build and run tests from: https://github.com/rikrak/AutoMapperConfigurationVerificationIssue

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build. Or use a Func based resolver instead.

**Comment by rikrak** [comment]
Ta.  I've actually just checked this with the latest automapper code, and it appears to have been resolved :-)

**Comment by rikrak** [comment]
Another workaround appears to be to use the MapFrom method that uses a string to specify the property to use with the MemberValueResolver.

So instead of:
```
   this.CreateMap<MainViewModel, MainModel>()
     .ForMember(
       m => m.ItemId, 
       opts => opts.MapFrom<ResolveNullableIdFromReferenceModel, ReferenceViewModel>(
         vm =>vm.Item
       )
     );
```
Try:
```
   this.CreateMap<MainViewModel, MainModel>()
     .ForMember(
       m => m.ItemId, 
       opts => opts.MapFrom<ResolveNullableIdFromReferenceModel, ReferenceViewModel>(
         nameof(MainViewModel.Item)
       )
     );
```
