### ISSUE TITLE
When defining a a property to map the root object the creation of the mapper throws an exception

### ISSUE THREAD

**Issue by JPVenson** [AutoMapper/AutoMapper#3019]
Example Code (Cannot be executed in .net fiddle, so just for code dump reasons):

https://dotnetfiddle.net/Y5Fsmr

### Source/destination types

```csharp
	public class Foo {
		public string Test { get; set; }
	}
	
	public class Bar {
		public Foo Foo { get; set; }	
	}
```

### Mapping configuration

```csharp
               var configuration = new MapperConfiguration(f =>
			{
				f.CreateMap<Foo, Bar>()
					.ForMember(e => e.Foo, e => e.MapFrom(w => w));
				
				f.CreateMissingTypeMaps = true;
				f.ValidateInlineMaps = false;
			});
		IMapper mapper = configuration.CreateMapper();
```

### Expected behavior

I Expect that all properties of `Foo `should be copied into the object of `Foo.Bar`

### Actual behavior

Exception:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Sequence contains no elements
  Source=System.Core
  StackTrace:
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at AutoMapper.ConstructorParameterMap.get_SourceType() in C:\projects\automapper\src\AutoMapper\ConstructorParameterMap.cs:line 25
   at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveMemberTypeMap|17_4(IMemberMap memberMap) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 128
   at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>b__17_1(IMemberMap pm) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 88
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 90
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 58
   at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 287
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 278
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair, ITypeMapConfiguration inlineConfiguration) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 220
   at AutoMapper.MapperConfiguration.ResolveTypeMap(TypePair typePair) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 209
   at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveTypeMap|17_5(TypePair types) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 138
   at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>g__ResolveMemberTypeMap|17_4(IMemberMap memberMap) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 132
   at AutoMapper.Execution.TypeMapPlanBuilder.<CheckForCycles>b__17_1(IMemberMap pm) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 88
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckForCycles(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 90
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 58
   at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 287
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\TypeMap.cs:line 278
   at AutoMapper.MapperConfiguration.Seal() in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 371
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 52
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 59
   
```

### Steps to reproduce

```csharp
 Call `CreateMapper()`
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by JPVenson** [comment]
Confirmed to work with 8.1.0-ci-01543
