### ISSUE TITLE
ProjectTo<>() not working when source type uses Value Conversions

### ISSUE THREAD

**Issue by afranioce** [AutoMapper/AutoMapper#3024]
I using value conversions ([the feature is new in EF Core 2.1](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions)) BytesToStringConverter 

#### mapping

```csharp
    public class SupplyEntryDocumentMap : IEntityTypeConfiguration<EntryDocument>
    {
        public void Configure(EntityTypeBuilder<EntryDocument> builder)
        {
            builder.Property(r => r.IsCompleted)
                .HasColumnName("Ent_Concluido")
                .HasMaxLength(1)
                .HasConversion(new BoolToStringConverter("N", "S"));
        }
    }
```

#### entity

```csharp
    public class SupplyEntryDocumentViewModel
    {
        public bool? IsCompleted { get; set; }
    }
```

#### view model
```csharp
    public class SupplyEntryDocumentViewModel
    {
        public bool? IsCompleted { get; set; }
    }
```

### Mapping configuration

```csharp
    public class DomainToViewModelMappingProfile : Profile
    {
        public DomainToViewModelMappingProfile()
        {
            CreateMap<EntryDocument, SupplyEntryDocumentViewModel>()
                .ForMember(dest => dest.IsCompleted, opt => opt.NullSubstitute(false));
        }
    }
```

### Version: x.y.z
 
Automapper 8.0.0
Entity Framework (sqlServer) 2.2.2
dotnet core 2.2.0

### Expected behavior

Convert string to bool:
`"S"` (Yes) to `true`
`"N"` (No) to `false`

### Actual behavior

      System.Data.SqlClient.SqlException (0x80131904): Conversion failed when converting the varchar value 'S' to data type bit.
         at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
         at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
         at System.Data.SqlClient.SqlDataReader.<>c__DisplayClass190_0.<ReadAsync>b__1(Task t)
         at System.Data.SqlClient.SqlDataReader.InvokeRetryable[T](Func`2 moreFunc, TaskCompletionSource`1 source, IDisposable objectToDispose)

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by lbargaoanu** [comment]
But if you already use AM, why even bother with EF Core converters? Or the other way around :) That just seems needlessly complicated. Maybe you should stick to just using one of them.

**Comment by jbogard** [comment]
With any EF issue, try to map this first with a manual `Select` projection, removing `ProjectTo`.
