### ISSUE TITLE
Updating from 8.0.0 to 8.1.0 fails asserting config is valid

### ISSUE THREAD

**Issue by ristogod** [AutoMapper/AutoMapper#3145]
### Source/destination types

```csharp
  public class AttributeDataModel : IAttributeModel
  {
    public string Name { get; set; }
    public string Value { get; set; }
  }

public class ConfigurationMetaDataKeyRecord : ICreated
    {
        public virtual ConfigurationRecord Configuration { get; set; }
        public int ConfigurationId { get; set; }
        public DateTime CreatedTs { get; set; }
        public int Id { get; set; }
        public string Key { get; set; }
        public DateTime LastUpdatedTs { get; set; }
        public virtual ICollection<ConfigurationMetaDataValueRecord> Values { get; set; } = new HashSet<ConfigurationMetaDataValueRecord>();
    }
```

### Mapping configuration

```csharp
            CreateMap<AttributeDataModel, ConfigurationMetaDataKeyRecord>()
                .EqualityComparison((source, target) => source.Name.Equals(target.Key, OrdinalIgnoreCase))
                .ForMember(target => target.Configuration, _ => _.Ignore())
                .ForMember(target => target.ConfigurationId, _ => _.Ignore())
                .ForMember(target => target.CreatedTs, _ => _.Ignore())
                .ForMember(target => target.Id, _ => _.Ignore())
                .ForMember(target => target.Key, _ => _.MapFrom(source => source.Name))
                .ForMember(target => target.LastUpdatedTs, _ => _.Ignore())
                .ForMember(target => target.Values,
                           _ => _.MapFrom(source => new[]
                                                    {
                                                        source.Value
                                                    }));
```

### Version: x.y.z
8.1.1

### Expected behavior

I expect the unit test to pass that worked prior to updating AutoMapper

### Actual behavior

The test fails with this exception.

System.InvalidOperationException : Missing map from System.String to System.String. Create using Mapper.CreateMap<String, String>.
   at AutoMapper.MapperConfiguration.GetIncludedTypeMaps(IEnumerable`1 includedTypes)+MoveNext() in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 413
   at System.Linq.Enumerable.ZipIterator[TFirst,TSecond,TResult](IEnumerable`1 first, IEnumerable`1 second, Func`3 resultSelector)+MoveNext()
   at AutoMapper.ProfileMap.AddMemberMaps(LambdaExpression[] includedMembers, TypeMap mainMap, IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\ProfileMap.cs:line 258
   at AutoMapper.ProfileMap.ApplyMemberMaps(TypeMap mainMap, IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\ProfileMap.cs:line 252
   at AutoMapper.ProfileMap.Configure(TypeMap typeMap, IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\ProfileMap.cs:line 172
   at AutoMapper.ProfileMap.Configure(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\ProfileMap.cs:line 121
   at AutoMapper.MapperConfiguration.Seal() in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 348
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 56
   at Veil.Tests.ProfileTests`1..ctor(Type[] profileTypes) in C:\Users\nlristo\Source\Repos\Veil\test\Tests\ProfileTests.cs:line 20
   at Veil.Configurators.Tests.Mapping.DefaultProfileTests..ctor() in C:\Users\nlristo\Source\Repos\Veil\test\Configurators.Tests\Mapping\DefaultProfileTests.cs:line 25

### Steps to reproduce

```csharp
        [Fact]
        public void AttributeDataModel_Maps_To_ConfigurationMetaDataKeyRecord_Correctly()
        {
            // Arrange
            var source = TestInstances.AttributeDataModel;

            // Act
            var target = Mapper.Map<ConfigurationMetaDataKeyRecord>(source);

            // Assert
            Assert.Equal(source.Name, target.Key);
            Assert.Collection(target.Values, _ => Assert.Equal(source.Value, _.Value));
        }
```

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.
