### ISSUE TITLE
No parameterless constructor defined for this object on Unit Test (XUnit) Only

### ISSUE THREAD

**Issue by aborderon** [AutoMapper/AutoMapper#3200]
Hello,

I set up a resolver to map my specify identifier property directly to my entity. My DTO has not this property and i need to use a custom value resolver to find this identifier by db context repository.

Here is my profile mapper :

   ```
 public class ConnectorCreateProfile : Profile
    {
        /// <Summary>
        /// Constructor
        /// </Summary>
        public ConnectorCreateProfile()
        {
            CreateMap<ConnectorCreateDTO, ConnectorBaseEntity>()
            .ForMember(dest => dest.ERPProviderId, opt => opt.MapFrom<ErpProviderResolver>())
            .ForAllOtherMembers(opt => opt.Ignore());
        }
    }
```

I call my resolver :
```
public class ErpProviderResolver : IValueResolver<ConnectorCreateDTO, ConnectorBaseEntity, int>
    {
        private readonly IReferencesRepository _referencesRepository;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="referencesRepository"></param>
        public ErpProviderResolver(IReferencesRepository referencesRepository)
        {
            _referencesRepository = referencesRepository;
        }

        /// <summary>
        /// Resolve.
        /// </summary>
        /// <param name="source"></param>
        /// <param name="destination"></param>
        /// <param name="member"></param>
        /// <param name="context"></param>
        /// <returns>ERP Provider identifier</returns>
        public int Resolve(ConnectorCreateDTO source, ConnectorBaseEntity destination, int member, ResolutionContext context)
        {
            return _referencesRepository.GetERPProviderIdByERPTypeAndProviderTypeAsync(source.ERPVersion, source.ProviderType).Result;
        }
    }
```

My configuration is as follows into startup.cs :
In ConfigureServices :
`services.AddAutoMapper(typeof(Startup));`

and my Configure function : 
```
 public void Configure(IApplicationBuilder app, IHostingEnvironment env, AutoMapper.IConfigurationProvider autoMapper)
           ...
            autoMapper.AssertConfigurationIsValid();
           ...
        }
```

I use an AutoMapperConfiguration class like : 
```
   public static class AutoMapperConfiguration
    {
        public static MapperConfiguration RegisterMappings()
        {
            return new MapperConfiguration(cfg =>
            {
                ...
                cfg.AddProfile(new ConnectorProfile());
                ...
            });
        }
    }
```

My configuration works well because I have no problem when I use the API in production, I get well from the resolver and the mapping works.

On the other hand, when I perform unit tests with XUnit, I get the following error when mapping:
```
Type Map configuration:
ConnectorCreateDTO -> ConnectorOracleEntity
IBIS.API.Dto.Customer.ServerLicense.Connector.ConnectorCreateDTO -> IBIS.API.Entities.Customer.ServerLicense.Connector.ConnectorOracleEntity

Destination Member:
ERPProviderId

---- System.MissingMethodException : No parameterless constructor defined for this object.
    Stack Trace:
       at lambda_method(Closure , ConnectorCreateDTO , ConnectorOracleEntity , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at IBIS.API.Mappers.Factories.ConnectorBaseFactory.Create(ConnectorBaseDTO src, ResolutionContext context) in /home/adrien/Workdir/ibis/ibis-api/src/IBIS.API/Mappers/Factories/ConnectorBaseFactory.cs:line 25
   at IBIS.API.Mappers.Profiles.Customer.ServerLicense.Connector.ConnectorCreateProfile.<>c.<.ctor>b__0_0(ConnectorCreateDTO src, ResolutionContext context) in /home/adrien/Workdir/ibis/ibis-api/src/IBIS.API/Mappers/Profiles/Customer/ServerLicense/Connector/ConnectorCreateProfile.cs:line 20
   at lambda_method(Closure , ConnectorCreateDTO , ConnectorBaseEntity , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at IBIS.API.Controllers.Customer.ServerLicense.Connector.ConnectorsController.PostConnector(Int32 customerId, Int32 serverLicenseId, ConnectorCreateDTO connectorCreateDTO) in /home/adrien/Workdir/ibis/ibis-api/src/IBIS.API/Controllers/Customer/ServerLicense/Connector/ConnectorsController.cs:line 110
   at IBIS.API.UnitTests.Application.Controllers.Customer.ServerLicense.Connector.ConnectorsControllerTests.Add_specific_oracle_connector_by_customerId_and_serverlicenseId() in /home/adrien/Workdir/ibis/ibis-api/tests/IBIS.API.UnitTests/Application/Controllers/Customer/ServerLicense/Connector/ConnectorsControllerTests.cs:line 347
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at AutoMapper.MappingOperationOptions`2.CreateInstance[T]() in C:\projects\automapper\src\AutoMapper\MappingOperationOptions.cs:line 44
   at lambda_method(Closure , ConnectorCreateDTO , ConnectorOracleEntity , ResolutionContext )
```

I make a call to my controller in my unit test and I have to inject IMapper, to do that I use this statement in the constructor of my test file:

```
[Collection("SystemCollection")]
    public class ConnectorsControllerTests
    {
        private readonly IMapper _mapper;

        public ConnectorsControllerTests()
        {
            _mapper = new Mapper(AutoMapperConfiguration.RegisterMappings());
        }
}
```

Do you have an idea of ​​my problem with my unit tests?
Thanks,
Adrien

**Comment by jbogard** [comment]
If you're using ASP.NET Core, you should use the explicit extension for that so that you can do:

`services.AddAutoMapper(typeof(Startup));`

Then in your unit tests, I'd do the same thing, create a `ServicesCollection`, call `RegisterServices` in your `Startup` class, and make the unit tests use those services.

See:

https://github.com/jbogard/ContosoUniversityDotNetCore-Pages/blob/master/ContosoUniversity.IntegrationTests/SliceFixture.cs#L22

**Comment by aborderon** [comment]
Thank you for your answer, it gives me some leads but I have not managed to run my tests.

I use a TestContext like this:

 ```
   /// <summary>
    /// Test context startup class.
    /// </summary>
    public class TestContext : IDisposable
    {
        /// <summary>
        /// Test server.
        /// </summary>
        private readonly TestServer _server;

        /// <summary>
        /// Application db context in memory.
        /// </summary>
        public ApplicationDbContext Context { get; private set; }

        /// <summary>
        /// Constructor.
        /// </summary>
        public TestContext()
        {
            var builder = new WebHostBuilder()
                .UseEnvironment("Testing")
                .UseStartup<Startup>();

            builder.ConfigureServices(services =>
            {
                // Create a new service provider.
                var serviceProvider = new ServiceCollection()
                    .AddEntityFrameworkSqlite()
                    .BuildServiceProvider();

                var connectionStringBuilder = new SqliteConnectionStringBuilder { DataSource = ":memory:" };

                var connectionString = connectionStringBuilder.ToString();
                var connection = new SqliteConnection(connectionString);

                // Add a database context (ApplicationDbContext) using an in-memory database for testing
                services.AddDbContext<ApplicationDbContext>(options =>
                {
                    options.UseSqlite(connection).EnableSensitiveDataLogging(true);
                    options.UseInternalServiceProvider(serviceProvider);
                });


                //////////////////////////////
                I tried to define the two lines for AutoMapper but I have no difference ..
                //////////////////////////////

                services.AddAutoMapper(typeof(Startup));
                services.AddSingleton(AutoMapperConfiguration.RegisterMappings().CreateMapper());

                // Build the service provider.
                var sp = services.BuildServiceProvider();

                // Create a scope to obtain a reference to the database
                // context (ApplicationDbContext).
                using (var scope = sp.CreateScope())
                {
                    var scopedServices = scope.ServiceProvider;
                    var db = scopedServices.GetRequiredService<ApplicationDbContext>();
                    var logger = scopedServices
                        .GetRequiredService<ILogger<TestContext>>();

                    // Ensure the database is created.
                    db.Database.OpenConnection();
                    db.Database.EnsureCreated();
                }
            });

            _server = new TestServer(builder);
            Context = _server.Host.Services.GetService(typeof(ApplicationDbContext)) as ApplicationDbContext;
        }

        /// <summary>
        /// Dispose.
        /// </summary>
        public void Dispose()
        {
            _server?.Dispose();
            Context?.Dispose();
        }
    }
```

In the constructors of my tests I have to define IMapper like this:

This may not be the way to define it ..
```

public class ConnectorsControllerTests
    {
        private readonly TestContext _testContext;
        private readonly IConnectorsService _connectorsService;
        private readonly IMapper _mapper;

        public ConnectorsControllerTests()
        {
            _testContext = new TestContext();
            _connectorsService = new ConnectorsService(new ConnectorsRepository(_testContext.Context), new ServerLicensesRepository(_testContext.Context));
            _mapper = new Mapper(AutoMapperConfiguration.RegisterMappings());
        }
}
```

**Comment by jbogard** [comment]
You're double-registering AutoMapper. You don't need the `AutoMapperConfiguration` class at all. That's what `services.AddAutoMapper` does for you - it scans and adds profiles automatically.

In your test, don't instantiate a `Mapper`. Get one of those from the test server.

**Comment by aborderon** [comment]
Indeed, I deleted the double declaration and I added the recovery of IMapper in my context to be able in my tests. It works well.
`Mapper = _server.Host.Services.GetRequiredService<IMapper>();`

Thank you
