### ISSUE TITLE
Object reference not set to an instance of an object for IHttpContextAccessor in IMappingAction

### ISSUE THREAD

**Issue by aborderon** [AutoMapper/AutoMapper#3207]
Hello,
I use the Automapper resolvers to solve a lot of dependencies.

For a particular case I need to access to `IHttpContextAccessor` properties.

For that I realized a standard `IValueResolver` by injecting `IHttpContextAccessor` but I get the following error for `IHttpContextAccessor` at the time of use:

```
Outcome: Failed
    Error Message:
    System.NullReferenceException : Object reference not set to an instance of an object.
    Stack Trace:
       at IBIS.API.Mappers.Resolvers.Customer.ServerLicense.User.UserIdByUserIdentityIdResolver.Process(IndicatorCreateDTO source, IndicatorEntity destination) in /home/adrien/Workdir/ibis/ibis-api/src/IBIS.API/Mappers/Resolvers/Customer/ServerLicense/User/UserIdByUserIdentityIdResolver.cs:line 38
   at AutoMapper.Configuration.MappingExpressionBase`3.<>c__11`1.<AfterMap>g__AfterFunction|11_0(TSource src, TDestination dest, ResolutionContext ctxt) in C:\projects\automapper\src\AutoMapper\Configuration\MappingExpressionBase.cs:line 284
   at lambda_method(Closure , IndicatorCreateDTO , IndicatorEntity , ResolutionContext )
   at lambda_method(Closure , Object , Object , ResolutionContext )
   at AutoMapper.Mapper.AutoMapper.IMapper.Map[TDestination](Object source) in C:\projects\automapper\src\AutoMapper\Mapper.cs:line 211
   at IBIS.API.Controllers.Indicator.IndicatorsController.PostIndicator(IndicatorCreateDTO indicatorCreateDTO) in /home/adrien/Workdir/ibis/ibis-api/src/IBIS.API/Controllers/Indicator/IndicatorsController.cs:line 104
   at IBIS.API.UnitTests.Application.Controllers.Indicator.IndicatorsControllerTests.Add_specific_indicator() in /home/adrien/Workdir/ibis/ibis-api/tests/IBIS.API.UnitTests/Application/Controllers/Indicator/IndicatorsControllerTests.cs:line 350
--- End of stack trace from previous location where exception was thrown ---
```

So I followed your documentation (http://docs.automapper.org/en/stable/Before-and-after-map-actions.html#asp-net-core-and-automapper-extensions-microsoft-dependencyinjection) to use an `IMappingAction` instead but I have the same problem.

IHttpContextAccessor is well configured in the Startup as follows:
`services.TryAddTransient<IHttpContextAccessor, HttpContextAccessor>();`

Here is my IMappingResolver and my Mapper:

IMappingResolver :
```
    public class UserIdByUserIdentityIdResolver : IMappingAction<IndicatorCreateDTO, IndicatorEntity>
    {
        private readonly IUsersRepository _usersRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="usersRepository"></param>
        /// <param name="httpContextAccessor"></param>
        public UserIdByUserIdentityIdResolver(IUsersRepository usersRepository, IHttpContextAccessor httpContextAccessor)
        {
            _usersRepository = usersRepository ?? throw new ArgumentNullException(nameof(usersRepository));
            _httpContextAccessor = httpContextAccessor ?? throw new ArgumentNullException(nameof(httpContextAccessor));
        }

        /// <summary>
        /// Process
        /// </summary>
        /// <param name="source"></param>
        /// <param name="destination"></param>
        public void Process(IndicatorCreateDTO source, IndicatorEntity destination)
        {
            var userIdentityId = new Guid(_httpContextAccessor.HttpContext.User.FindFirst("sub").Value);

            var userId = _usersRepository.GetUserIdByUserIdentityId(userIdentityId).Result;

            if (userId == 0)
            {
                throw new NotFoundException(ExceptionMessageUtil.NOT_FOUND);
            }

            destination.UserId = userId;
        }
    }
```

User in Mapper in **AfterMap** : 
```
CreateMap<IndicatorCreateDTO, IndicatorEntity>()
            .ForMember(dest => dest.Id, opt => opt.Ignore())
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
            .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
            .ForMember(dest => dest.XAxis, opt => opt.MapFrom(src => src.XAxis))
            .ForMember(dest => dest.XAxisGranularityId, opt => opt.MapFrom<XAxisGranularityIdByTypeResolver, HierarchyTypeEnum?>(src => src.XAxisGranularity))
            .ForMember(dest => dest.Public, opt => opt.MapFrom(src => src.Public))
            .ForMember(dest => dest.UserId, opt => opt.Ignore())
            .ForMember(dest => dest.MeasureId, opt => opt.MapFrom<MeasureIdByTypeResolver, MeasureTypeEnum>(src => src.YAxis.MeasureType))
            .ForMember(dest => dest.FunctionId, opt => opt.MapFrom<FunctionIdByTypeResolver, FunctionTypeEnum>(src => src.YAxis.FunctionType))
            .ForMember(dest => dest.DimensionFilters, opt => opt.MapFrom<IndicatorDimensionFilterResolver>())
            .ForMember(dest => dest.SharedUsers, opt => opt.MapFrom<UserIndicatorSharedResolver>())
            .AfterMap<UserIdByUserIdentityIdResolver>()
            .ForAllOtherMembers(opt => opt.Ignore());
```

Thanks for your help.
Adrien

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.

**Comment by aborderon** [comment]
I just tested more, and I realized that the problem was present only with unit tests and not in production.

I did register the services in my TestContext

```
services.TryAddTransient<IHttpContextAccessor, HttpContextAccessor>();
services.AddAutoMapper(typeof(UnitTestsStartup).Assembly);
```
