### ISSUE TITLE
Non-Generic Mapper.Map failing for structs in v10

### ISSUE THREAD

**Issue by BlaiseD** [AutoMapper/AutoMapper#3455]
### Source/destination types

```csharp
   public struct Truck
    {
        public string Color { get; set; }
        public int Year { get; set; }
    }

    public struct TruckModel
    {
        public string Color { get; set; }
        public int Year { get; set; }
    }
```

### Mapping configuration

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var config = new MapperConfiguration(c =>
            {
                c.CreateMap<Truck, TruckModel>();
            });

            config.AssertConfigurationIsValid();

            var mapper = config.CreateMapper();
            TruckModel truckModel = mapper.Map<TruckModel>(new Truck { Color = "blue", Year = 1999 });

            //below fails
            object o1 = mapper.Map(new Truck { Color = "blue", Year = 1999 }, typeof(Truck), typeof(TruckModel));
        }
    }
```

### Expected behavior

Mapping succeeds as with generic methods.

### Actual behavior
Fails with:
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Func`4[System.Object,System.Object,AutoMapper.ResolutionContext,AutoMapper10.TruckModel]' to type 'System.Func`4[System.Object,System.Object,AutoMapper.ResolutionContext,System.Object]'.
  Source=AutoMapper
  StackTrace:
   at AutoMapper.MapperConfiguration.GetExecutionPlan[TSource,TDestination](MapRequest mapRequest)
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, IMemberMap memberMap)
   at AutoMapper.Mapper.Map(Object source, Object destination, Type sourceType, Type destinationType)
   at AutoMapper.Mapper.Map(Object source, Type sourceType, Type destinationType)
   at AutoMapper10.Program.Main(String[] args) in C:\.Research\AutoMapper10\AutoMapper10\Program.cs:line 21


```

**Comment by BlaiseD** [comment]
workaround works:
```c#
        private static MethodInfo GetMapObjectMethod(this string methodName)
           => typeof(MapperExtensions).GetMethod(methodName, BindingFlags.NonPublic | BindingFlags.Static);

        public static object MapObject(IMapper mapper, object obj, Type sourceType, Type destType)
        {
            return "_MapObject".GetMapObjectMethod().MakeGenericMethod
            (
                sourceType,
                destType
            ).Invoke(null, new object[] { mapper, obj });
        }

        private static TDest _MapObject<TSource, TDest>(IMapper mapper, TSource source)
        {
            return mapper.Map<TSource, TDest>(source);
        }
```

**Comment by lbargaoanu** [comment]
A simpler workaround:

    mapper.Map(new Truck { Color = "blue", Year = 1999 }, new TruckModel());

**Comment by BlaiseD** [comment]
That could work but the context is dynamic where I just know both types.
```c#
Mapper.Map(node.Value, Activator.CreateInstance(newType));//doesn't work
MapperExtensions.MapObject(Mapper, node.Value, node.Type, newType);//works
```

I'll need a way to cast `Activator.CreateInstance(newType)` to TruckModel.

**Comment by lbargaoanu** [comment]
Yes, I was wrong, passing the destination doesn't solve anything, it was just using the working overload.

**Comment by lbargaoanu** [comment]
But bug aside, this doesn't add up. Because of all the boxing an unboxing, it's doesn't really help to use the non-generic `Map` with structs. You either use the generic one somehow, or simply switch to classes.

**Comment by BlaiseD** [comment]
I think the context is a [development tool/library](https://github.com/AutoMapper/AutoMapper.Extensions.ExpressionMapping/blob/1ae850739c976d10eefd2836715db20502adc06b/src/AutoMapper.Extensions.ExpressionMapping/XpressionMapperVisitor.cs#L318).

We're mapping an expression with a local variable (or instantiated inline) where the variable is a struct or class and we don't the type ahead of time.  There are probably other cases.

It's not a business application - just a failed unit test.

IMO it's worth just making it work.

**Comment by lbargaoanu** [comment]
I see. Then, for the most part, users should avoid structs, they will be boxed and it's just overhead at this point. I guess from the moment the expression tree is built, the constants are boxed.

**Comment by BlaiseD** [comment]
Yep - that's correct.  e.g. `ConstantExpression.Value` is an object.
