### ISSUE TITLE
Static field requires null instance, non-static field requires non-null instance

### ISSUE THREAD

**Issue by KuraiAndras** [AutoMapper/AutoMapper#3516]
We just upgraded AutoMapper from 10.0.0 to 10.1.0 and the Microsoft DI extension from 8.0.1 to 8.1.0. It broke during automated testing with XUnit, in a .net core 3.1 environment, with c#8 and nullable reference types enabled.

In the test we scan the same assemblies for profiles as in the main application, and then do IMapper.ConfigurationProvider.AssertConfigurationIsValid().

When updateing from 10.0.0 to 10.1.0 the tests break when trying to resolve IMapper through an IServiceProvider, with this stack trace:
```
System.ArgumentException
Static field requires null instance, non-static field requires non-null instance. (Parameter 'expression')
   at System.Linq.Expressions.Expression.Field(Expression expression, FieldInfo field)
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(IMemberMap memberMap, Expression destination, MemberInfo destinationMember)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
   at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath)
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__12_2(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at AutoMapper.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__12_3(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at ApplicationName.Application.Tests.MappingTests..ctor(IServiceCollection services) in C:\***\ApplicationName.Application.Tests\MappingTests.cs:line 12
```

I read the release notes for [10.1.0](https://github.com/AutoMapper/AutoMapper/releases/tag/v10.1.0) but I did not see any breaking change there that might cause this. Do you have any idea what would cause an exception like this?

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by KuraiAndras** [comment]
@lbargaoanu I have created a minimal [repro](https://gist.github.com/KuraiAndras/e0cdc441706501452ef7fd9044a33382). It seems like calling ReverseMap is the culprit, without it don't get an exception.

**Comment by lbargaoanu** [comment]
I'm sure there are many workarounds. You can use a `Func` based `MapFrom` or simply `new Guid()`.

**Comment by KuraiAndras** [comment]
But what is causing this? We have a few dozen MapFrom expressions, and I'm quite sure this is not the only one causing problems for us. Do I have to check each one? Do you have documentation on where / when / how things have changed to cause this behavior?

**Comment by KuraiAndras** [comment]
Changing the mapping to the following fixed the problem:
```csharp
CreateMap<AddChannel, ChannelDto>()
    .ForMember(
        src => src.Id,
        opt => opt.MapFrom((_, __, ___) => Guid.Empty))
    .ReverseMap();
```
Thanks @lbargaoanu for the help

**Comment by lbargaoanu** [comment]
If you'd rather keep your original mapping, you can use the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by jbogard** [comment]
Should we keep this open until the other branch is merged?

**Comment by lbargaoanu** [comment]
The fix is in the MyGet build, so I don't see the need.

**Comment by lbargaoanu** [comment]
But if you think people will hit the issue and keeping it open will help them, sure. I'm thinking people will find it with google regardless, but maybe not :)

**Comment by jbogard** [comment]
More thinking that an issue is "fixed" when merged - was this fixed in a branch or in `master`?

**Comment by lbargaoanu** [comment]
It's fixed in the branch of the PR, but that's the latest from MyGet, so merging into master doesn't seem relevant.
