### ISSUE TITLE
InvalidProgramException with ProjectTo and nullable ints

### ISSUE THREAD

**Issue by davidkarlsson** [AutoMapper/AutoMapper#3519]
### Source/destination types

```csharp
public class SourceParentTest {
    public SourceChildTest? Child { get; set; }
}

public class SourceChildTest {
   public int TestInt { get; set; }
}

public class DestinationTest
{
    public int? TestNullableInt { get; set; }
}
```

### Mapping configuration

```csharp
CreateMap<SourceParentTest, DestinationTest>()
    .ForMember(
        a => a.TestNullableInt,
        opt => opt.MapFrom(b => b.Child!.TestInt)
    );
```

### Version: x.y.z
AutoMapper 10.1.0
Microsoft.EntityFrameworkCore.SqlServer 5.0.0-rc.2.*

### Expected behavior

With AutoMapper 10.0.0 and using ProjectTo the mapping is successful with TestNullableInt being null when the Child navigation property is null and otherwise being set to the value of TestInt property from the child entity.

### Actual behavior

A "InvalidProgramException: Common Language Runtime detected an invalid program." is thrown when calling ToListAsync() on the ProjectTo query like this:

```csharp
var test = await _autoMapper.ProjectTo<DestTest>(sourceQuery).ToListAsync();
```

Here's the stack trace:
```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(RuntimeMethodHandleInternal method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.LambdaExpression.Compile()
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.VisitShapedQuery(ShapedQueryExpression shapedQueryExpression)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.VisitExtension(Expression extensionExpression)
   at System.Linq.Expressions.Expression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Test.Web.Areas.Admin.Controllers.TestController.Index(TestIndex model) in F:\DotNet\Test\Test.Web\Areas\Admin\Controllers\TestController.cs:line 70

```

**Comment by lbargaoanu** [comment]
But this seems to happen in memory, not in SQL.

**Comment by Mephistofeles** [comment]
I have the same problem with nullable strings with in-memory database (EF Core 3.1.9) used in tests, it's weird, because it works on Windows, the problem seems to exist only on Linux (Ubuntu container).

**Comment by davidkarlsson** [comment]
@lbargaoanu the source of the query is from a DbContext for a SQL Server database configured like this:

```csharp
services.AddDbContext<TestDbContext>(a =>
    a.UseSqlServer(_config.GetConnectionString("DefaultConnection"), b =>
        {
            b.MigrationsAssembly("Test.Core");
            b.EnableRetryOnFailure();
            b.MigrationsHistoryTable("__ef_migrations_history");
        }
    )
    .ConfigureWarnings(b =>
        {
            b.Ignore(RelationalEventId.MultipleCollectionIncludeWarning);
            b.Ignore(CoreEventId.FirstWithoutOrderByAndFilterWarning);
        }
    ),
    ServiceLifetime.Scoped,
    ServiceLifetime.Singleton
);
```

The sourceQuery in my example is then simply constructed like this: 
```csharp
var sourceQuery = _dbContext.SourceParentTests;
```

I'm using Windows 10 (Version 2004) if the OS really is a factor as Mephistofeles has noticed.

**Comment by slubowsky** [comment]
Attempting to upgrade existing application from 10.0.0 Im seeing this error all over using EF Core 3.1.8 with SQL server. Its happening in so many cases that I haven't determined that nullable values are involved in all, but its possible.

**Comment by jbogard** [comment]
I just repro'd this with my Contoso project with EF Core.

@lbargaoanu perhaps it's time we moved the tests from EF6 to EF Core...

**Comment by lbargaoanu** [comment]
Yes, I see it too. Why it compiles the expression, I don't know :)

**Comment by lbargaoanu** [comment]
@jbogard So, a quick fix for 10.1.1?

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by lbargaoanu** [comment]
Anybody interested in EF Core is welcome to add a test project similar with AutoMapper.IntegrationTests. All existing integration tests use EF6.

**Comment by lbargaoanu** [comment]
Workaround: `CreateMap<int, int?>().ConvertUsing(s=>s)`.

**Comment by slubowsky** [comment]
@lbargaoanu The MyGet build seems to have other unrelated changes as well. I get a compiler error trying to use it:
`'IMapperConfigurationExpression' does not contain a definition for 'Advanced' and no accessible extension method 'Advanced' accepting a first argument of type 'IMapperConfigurationExpression' could be found (are you missing a using directive or an assembly reference?)`

Commenting out my usage of Advanced - `mapper.Advanced.RecursiveQueriesMaxDepth = 4`
It compiles but then crashes on startup:
```
System.MissingMethodException: Method not found: 'Void AutoMapper.MapperConfiguration..ctor(AutoMapper.Configuration.MapperConfigurationExpression)'.
   at AutoMapper.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__12_2(IServiceProvider sp)
```

So looks like MyGet build not compatible with AutoMapper.Collection 7.0.0 either?

**Comment by lbargaoanu** [comment]
No, [the other MyGet build](https://myget.org/feed/automapperdev/package/nuget/AutoMapper/10.1.1-alpha.0.1) :) Perhaps you need to clear the NuGet cache. Check the date, it's like minutes ago.

**Comment by slubowsky** [comment]
Ok that works and looks like MyGet build fixes the issue. The mapping workaround with released version also seems to work for me. Thanks!
