### ISSUE TITLE
Instance property 'Current' is not defined for type 'System.Collections.IDictionaryEnumerator' (Parameter 'propertyName')

### ISSUE THREAD

**Issue by marchy** [AutoMapper/AutoMapper#3552]
Upon upgrading to AutoMapper 10.x, getting an internal exception without any suggestive details thrown when instantiating a MapperConfiguration()

### Source/destination types
```csharp
config.CreateMap<Exception, APIErrorException>()
	.ForMember( _ => _.ErrorCode, mapping => mapping.Ignore() );
```

### Mapping configuration

```csharp
public class APIErrorException : Exception {
	[JsonProperty]
	public string ErrorCode { get; private set; }

	[JsonProperty]
	public override string Message => base.Message;
}
```

### Expected behavior

Create new MapperConfiguration( .. ) as per v9.0 and before.

### Actual behavior

Throwing following exception:
```
System.ArgumentException: Instance property 'Current' is not defined for type 'System.Collections.IDictionaryEnumerator' (Parameter 'propertyName')
   at System.Linq.Expressions.Expression.Property(Expression expression, String propertyName)
   at AutoMapper.Internal.ExpressionFactory.ForEach(Expression collection, ParameterExpression loopVar, Expression loopContent)
   at AutoMapper.Internal.CollectionMapperExpressionFactory.MapCollectionExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, IMemberMap memberMap, Expression sourceExpression, Expression destExpression, Expression contextExpression, Type ifInterfaceType, MapItem mapItem)
   at AutoMapper.Mappers.EnumerableMapper.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, IMemberMap memberMap, Expression sourceExpression, Expression destExpression, Expression contextExpression)
   at AutoMapper.Execution.ExpressionBuilder.ObjectMapperExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, TypePair typePair, Expression sourceParameter, Expression contextParameter, IMemberMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.ExpressionBuilder.MapExpression(IConfigurationProvider configurationProvider, ProfileMap profileMap, TypePair typePair, Expression sourceParameter, Expression contextParameter, IMemberMap propertyMap, Expression destinationParameter)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(IMemberMap memberMap, Expression destination, MemberInfo destinationMember)
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression destinationFunc)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath)
   at AutoMapper.TypeMap.CreateMapperLambda(IConfigurationProvider configurationProvider, HashSet`1 typeMapsPath)
   at AutoMapper.TypeMap.Seal(IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at Happ.Server.Startup.ConfigureServices(IServiceCollection services) in /Users/.../Startup.cs:line 89
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass15_0.<BuildStartupServicesFilterPipeline>g__RunPipeline|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.StartupLoader.ConfigureServicesDelegateBuilder`1.<>c__DisplayClass14_0.<ConfigureServices>g__ConfigureServicesWithContainerConfiguration|0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Happ.Server.Program.Main(String[] args) in /Users/.../Program.cs:line 23
```

### Steps to reproduce

```csharp
// Startup.cs
public void ConfigureServices( IServiceCollection services ){
	var mapperConfig = new MapperConfiguration( config => {
		DomainObjectMapperConfig.BuildMergeableMapperConfiguration( config );
		APIObjectMapperConfig.BuildUpMapperConfiguration( config );
	}); // NOTE: exception is thrown on this line. Above lambda runs through successfully.
	mapperConfig.AssertConfigurationIsValid();
	IMapper mapper = mapperConfig.CreateMapper();
}

// DomainObjectMapperConfig.cs
public static void BuildMergeableMapperConfiguration( IMapperConfigurationExpression config ){
	MapModelsToDBOs( config );
	MapDBOsToModels( config );
}

// APIObjectMapperConfig.cs
public static void BuildUpMapperConfiguration( IMapperConfigurationExpression config ){
	...

	void MapException<TException, TExceptionDTO>() {
		config.CreateMap<TException, TExceptionDTO>()
			// NOTE: include base properties (ie: 'Message')
			.IncludeBase<Exception, APIErrorException>();
	}

	config.CreateMap<Exception, APIErrorException>()
		.ForMember( _ => _.ErrorCode, mapping => mapping.Ignore() )
		// NOTE: This is needed to prevent exception after AutoMapper 10.x migration
		.ForAllOtherMembers( _ => _.Ignore() );
	MapException<UnsupportedClientVersionException, UnsupportedClientVersionExceptionDTO>();
	MapException<System.ComponentModel.DataAnnotations.ValidationException, ValidationException>();
	MapException<InvalidVerificationCodeException, InvalidVerificationCodeExceptionDTO>();
	MapException<InvalidLinkTokenException, InvalidLinkTokenExceptionDTO>();
	MapException<InvalidPhoneNumberException, InvalidPhoneNumberExceptionDTO>();
}
```

NOTE: If adding the `.ForAllOtherMembers( _ => _.Ignore() )` line above the exception is not thrown.

**Comment by lbargaoanu** [comment]
`ForMember(d=>d.Data, o=>o.Ignore())`. That's typed as the non generic `IDictionary`, not smth we support OOB.

**Comment by lbargaoanu** [comment]
See also https://stackoverflow.com/questions/65829943/automapper-10-error-when-trying-to-map-exceptions#comment116393521_65829943
