### ISSUE TITLE
A null value for a multi-dimensional array results in an empty one-dimensional array, throwing an InvalidCastException.

### ISSUE THREAD

**Issue by burns140** [AutoMapper/AutoMapper#3593]
gist: https://gist.github.com/burns140/53b8c0c571534b7af0192ee329ecec60

### Source/destination types
```csharp
// Put your source/destination types here

//Source
public class ResultSet {
  public string[,] IDMap { get; set; }
}

//Dest
public class DTO {
  public string[,] IDMap { get; set; }
}
```

### Mapping configuration

```csharp
// Mapper.Initialize or just the CreateMap snippet 
var config = new MapperConfiguration(c => {
    c.CreateMap<ResultSet, DTO>().ReverseMap();
});
```

### Version: x.y.z
4.2.1

### Expected behavior
A null result would map to an empty 2d array of string[,]

### Actual behavior
The null mapped to an empty 1d array of string[] then threw an inner System.InvalidCastException trying to map from string[] to string[,]

### Steps to reproduce
Create two classes with one of the fields being a multidimensional array. Set the value of that multidimensional array in the instance of the source class to null, then attempt to map it to the destination class.
```csharp
// Your calls to Mapper.Map or ProjectTo here, with source/destination objects constructed
var source = new ResultSet {
    IDMap = null
};
  
try {
    var dest = mapper.Map<DTO>(source);
 } catch (Exception ex) {
    ex.ToString();
}
```

### Stacktrace: 
```
AutoMapper.AutoMapperMappingException: 

Mapping types:
String[,] -> String[,]
System.String[,] -> System.String[,]

Destination path:
ResultSet.IDMap.IDMap

Source value:
(null) ---> System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.String[,]'.
   at lambda_method(Closure , Object , Object )
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.AssignValue(PropertyMap propertyMap, Object mappedObject, Object propertyValueToAssign)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, Object mappedObject, PropertyMap propertyMap)
   --- End of inner exception stack trace ---
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
