### ISSUE TITLE
Argument Exception configuring ListOfT to its subclass.

### ISSUE THREAD

**Issue by BlaiseD** [AutoMapper/AutoMapper#3597]
Came across this config error which works in 10.1.1.  It's part of one of the expression mapping tests.

### Source/destination types

```csharp
    class ListExtension : List<string>
    {
    }
```

### Mapping configuration

```csharp
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<ListExtension, List<string>>().ReverseMap();
            });

            IMapper mapper = config.CreateMapper();
```

### Expected behavior
Configuration runs without exceptions.

### Actual behavior
Exception upon configuration:
```
Result StackTrace:	
at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreatePropertyMapFunc(MemberMap memberMap, Expression destination, MemberInfo destinationMember) in C:\.github\AutoMapper\AutoMapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 301
   at AutoMapper.Execution.TypeMapPlanBuilder.TryPropertyMap(PropertyMap propertyMap) in C:\.github\AutoMapper\AutoMapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 287
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateAssignmentFunc(Expression createDestination) in C:\.github\AutoMapper\AutoMapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 175
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda(HashSet`1 typeMapsPath) in C:\.github\AutoMapper\AutoMapper\src\AutoMapper\Execution\TypeMapPlanBuilder.cs:line 54
   at AutoMapper.TypeMap.CreateMapperLambda(IGlobalConfiguration configurationProvider, HashSet`1 typeMapsPath) in C:\.github\AutoMapper\AutoMapper\src\AutoMapper\TypeMap.cs:line 325
   at AutoMapper.TypeMap.Seal(IGlobalConfiguration configurationProvider, HashSet`1 typeMapsPath) in C:\.github\AutoMapper\AutoMapper\src\AutoMapper\TypeMap.cs:line 302
   at AutoMapper.MapperConfiguration.Seal() in C:\.github\AutoMapper\AutoMapper\src\AutoMapper\Configuration\MapperConfiguration.cs:line 363
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression) in C:\.github\AutoMapper\AutoMapper\src\AutoMapper\Configuration\MapperConfiguration.cs:line 106
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure) in C:\.github\AutoMapper\AutoMapper\src\AutoMapper\Configuration\MapperConfiguration.cs:line 115
   at AutoMapper.Extensions.ExpressionMapping.UnitTests.ShouldMapListExtensionToListOfT.Issue1() in C:\.github\AutoMapper\AutoMapper.Extensions.ExpressionMapping\tests\AutoMapper.Extensions.ExpressionMapping.UnitTests\ShouldMapListExtensionToListOfT.cs:line 13
Result Message:	
System.ArgumentException : Incorrect number of arguments supplied for call to method 'System.String get_Item(Int32)'
Parameter name: property
```

### Steps to Reproduce
```c#
        [Fact]
        public void Issue1()
        {
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<ListExtension, List<string>>().ReverseMap();
            });

            IMapper mapper = config.CreateMapper();
        }
```

**Comment by lbargaoanu** [comment]
You have to explicitly ignore `Item` . We used to do this by default, but it's expensive. And usually irrelevant.
That being said, deriving from `List` is weird. And I'm not sure what that map actually does.

**Comment by BlaiseD** [comment]
That makes sense.

BTW the following works:
```c#
                cfg.CreateMap<ListExtension, List<string>>()
                    .ForMember("Item", op => op.Ignore());
                cfg.CreateMap<List<string>, ListExtension>()
                    .ForMember("Item", op => op.Ignore());
```

With `ReverseMap()` is blows up before `Ignore()` kicks in:
```c#
            var config = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<ListExtension, List<string>>()
                    .ForMember("Item", op => op.Ignore())
                .ReverseMap()
                    .ForMember("Item", op => op.Ignore());
            });
```

**Comment by lbargaoanu** [comment]
You can also do the ignoring globally, with `ShouldMapProperty` or `GlobalIgnores`. That would work with the initial code.
