### ISSUE TITLE
Automapper.Configuration.MapperConfigurationExpression missing in latest myget build 10.1.2-alpha.0.2

### ISSUE THREAD

**Issue by marcOcram** [AutoMapper/AutoMapper#3706]
### Expected behavior

That no exception is thrown because `AutoMapper.Configuration.MapperConfigurationExpression` should exist.

### Actual behavior

A `System.TypeLoadException' is thrown because `AutoMapper.Configuration.MapperConfigurationExpression` is missing.

```
Could not load type 'AutoMapper.Configuration.MapperConfigurationExpression' from assembly 'AutoMapper, Version=10.0.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005'.
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`2 configAction, IEnumerable`1 assembliesToScan, ServiceLifetime serviceLifetime)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Action`1 configAction)
   at Program.Main(String[] args)
```

### Steps to reproduce

```csharp
public static class Program
{
    public static void Main(string[] args)
    {
        new ServiceCollection().AddAutoMapper(cfg => { });
    }
}
```

I know that it is a alpha build but I wanted to be sure that this issue does not go into live because the class exists in the [upgrade branch](https://github.com/AutoMapper/AutoMapper/blob/upgrade_guide/src/AutoMapper/Configuration/MapperConfigurationExpression.cs).

**Comment by lbargaoanu** [comment]
The DI package does not work with the new code. Once the DI package is built with the new code, it will.

**Comment by lbargaoanu** [comment]
The [DI MyGet](https://myget.org/feed/automapperdev/package/nuget/AutoMapper.Extensions.Microsoft.DependencyInjection) works now with the AM MyGet.
