### ISSUE TITLE
Calling IMapper.Map with an OrderBy causes an AmbiguousMatchException to be thrown

### ISSUE THREAD

**Issue by jonsagara** [AutoMapper/AutoMapper#3817]
### Source/destination types

```csharp
// Source
public class SavedItemSearchEntity
{
    public string? Manufacturer { get; set; }
    public string? Importer { get; set; }
    public string? Model { get; set; }
    public string? Serial { get; set; }
}

// Destination
public class SavedItemSearchModel
{
    public string? Manufacturer { get; set; }
    public string? Importer { get; set; }
    public string? Model { get; set; }
    public string? Serial { get; set; }
}
```

### Mapping configuration

```csharp
public class AdvancedSearchProfile : Profile
{
    public AdvancedSearchProfile()
    {
        CreateMap<SavedItemSearchEntity, SavedItemSearchModel>();
    }
}
```

### Version
 
AutoMapper 11.0.0, with AutoMapper.Extensions.Microsoft.DependencyInjection 11.0.0

### Expected behavior

This line of code should not throw an `AmbiguousMatchException`:

```csharp
var modelsFails = mapper.Map<SavedItemSearchModel[]>(entities.OrderBy(s => s.Manufacturer));
```

### Actual behavior

In AutoMapper 11.0.0, this line of code throws an `AmbiguousMatchException`:

```csharp
var modelsFails = mapper.Map<SavedItemSearchModel[]>(entities.OrderBy(s => s.Manufacturer));
```

### Steps to reproduce

I have a reproduction in a VS2022 console app:

https://github.com/jonsagara/AutoMapper11POC

Branch `main` contains AutoMapper 11.0.0 with the failing code.

Branch `v10` contains AutoMapper 10.1.1, and demonstrates that the code used to work without error.

To see the error:

1. Ensure you're on the `main` branch
2. Open the solution in Visual Studio 2022
3. Run the solution
4. See the exception in the console output

Stack trace:

```
System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at AutoMapper.Internal.TypeExtensions.GetInstanceMethod(Type type, String name)
   at AutoMapper.Internal.TypeExtensions.<>c__DisplayClass8_0.<GetInheritedMethod>b__0(Type t)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.Internal.TypeExtensions.GetInheritedMethod(Type type, String name)
   at AutoMapper.Execution.ExpressionBuilder.ForEach(ParameterExpression loopVar, Expression collection, Expression loopContent)
   at AutoMapper.Internal.Mappers.CollectionMapper.ArrayMapper.MapToArray(IGlobalConfiguration configurationProvider, ProfileMap profileMap, Expression sourceExpression, Type destinationType)
   at AutoMapper.Internal.Mappers.CollectionMapper.MapExpression(IGlobalConfiguration configurationProvider, ProfileMap profileMap, MemberMap memberMap, Expression sourceExpression, Expression destExpression)
   at AutoMapper.MapperConfiguration.GenerateObjectMapperExpression(MapRequest& mapRequest, IObjectMapper mapperToUse)
   at AutoMapper.MapperConfiguration.AutoMapper.Internal.IGlobalConfiguration.BuildExecutionPlan(MapRequest& mapRequest)
   at AutoMapper.MapperConfiguration.CompileExecutionPlan(MapRequest mapRequest)
   at AutoMapper.Internal.LockingConcurrentDictionary`2.<>c__DisplayClass1_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.Internal.LockingConcurrentDictionary`2.GetOrAdd(TKey& key)
   at AutoMapper.MapperConfiguration.GetExecutionPlan(MapRequest& mapRequest)
   at AutoMapper.MapperConfiguration.AutoMapper.Internal.IGlobalConfiguration.GetExecutionPlan[TSource,TDestination](MapRequest& mapRequest)
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, MemberMap memberMap)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination)
   at AutoMapper.Mapper.Map[TDestination](Object source)
   at Program.<Main>$(String[] args) in C:\Dev\SANDBOX\AutoMapper11POC\src\AutoMapper11POC\Program.cs:line 39
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
We'll probably have a bug fix release soon enough.
You can add `ToArray` as a workaround.

**Comment by jonsagara** [comment]
Thank you!

**Comment by jbogard** [comment]
Look for the bug fix release in the next week, I like to batch a few up before pushing out a new one

**Comment by VaclavElias** [comment]
Haha, just came across this bug in my app. Thanks for fixing!

**Comment by robinNode** [comment]
can we have an urgent patch for this?

**Comment by robinNode** [comment]
Hi,
I just installed 11.0.1-alpha.0.9 and I am now getting this error.

---> System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoMapper.MapperConfiguration.CompileExecutionPlan(MapRequest mapRequest)
   at AutoMapper.Internal.LockingConcurrentDictionary`2.<>c__DisplayClass1_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.MapperConfiguration.AutoMapper.Internal.IGlobalConfiguration.GetExecutionPlan[TSource,TDestination](MapRequest& mapRequest)
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, MemberMap memberMap)
   at AutoMapper.Mapper.AutoMapper.IInternalRuntimeMapper.Map[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, MemberMap memberMap)
   at AutoMapper.ResolutionContext.MapInternal[TSource,TDestination](TSource source, TDestination destination, MemberMap memberMap)
   at lambda_method3776(Closure , Object , ApiEntityAspects , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method3776(Closure , Object , ApiEntityAspects , ResolutionContext )
   --- End of inner exception stack trace ---
   at lambda_method3776(Closure , Object , ApiEntityAspects , ResolutionContext )

**Comment by lbargaoanu** [comment]
@robinNode 
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail. If you have that, open a new issue. This is not a support site.
