### ISSUE TITLE
System.Reflection.AmbiguousMatchException: Ambiguous match found error after 11 upgrade

### ISSUE THREAD

**Issue by BobBonser** [AutoMapper/AutoMapper#3829]
After I update to 11.0 at least one of the mappings no longer works.

releaseNotes = mapper.Map<IEnumerable<ReleaseNote>, List<ReleaseNoteViewModel>>(dbReleaseNotes);

Here is the mapping in my profile:              CreateMap<ReleaseNote, ReleaseNoteViewModel>();

The two classes are identical in properties:

    public class ReleaseNote
    {
        public Guid Id { get; set; }
        public Guid GovMaxVersionId { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public int DisplayOrder { get; set; }
    }

    public class ReleaseNoteViewModel
    {
        public Guid Id { get; set; }
        public Guid GovMaxVersionId { get; set; }
        [Required(ErrorMessage = "Note is required")]
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public int DisplayOrder { get; set; }
    }

Here is the full error:
  [2022-01-10T13:07:02.653Z] Error: System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at AutoMapper.Internal.TypeExtensions.GetInstanceMethod(Type type, String name)
   at AutoMapper.Internal.TypeExtensions.<>c__DisplayClass8_0.<GetInheritedMethod>b__0(Type t)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.Internal.TypeExtensions.GetInheritedMethod(Type type, String name)
   at AutoMapper.Execution.ExpressionBuilder.ForEach(ParameterExpression loopVar, Expression collection, Expression loopContent)
   at AutoMapper.Internal.Mappers.CollectionMapper.<MapExpression>g__MapCollectionCore|2_1(Expression destExpression, <>c__DisplayClass2_0& )
   at AutoMapper.Internal.Mappers.CollectionMapper.MapExpression(IGlobalConfiguration configurationProvider, ProfileMap profileMap, MemberMap memberMap, Expression sourceExpression, Expression destExpression)
   at AutoMapper.MapperConfiguration.GenerateObjectMapperExpression(MapRequest& mapRequest, IObjectMapper mapperToUse)
   at AutoMapper.MapperConfiguration.AutoMapper.Internal.IGlobalConfiguration.BuildExecutionPlan(MapRequest& mapRequest)
   at AutoMapper.MapperConfiguration.CompileExecutionPlan(MapRequest mapRequest)
   at AutoMapper.Internal.LockingConcurrentDictionary`2.<>c__DisplayClass1_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.Internal.LockingConcurrentDictionary`2.GetOrAdd(TKey& key)
   at AutoMapper.MapperConfiguration.GetExecutionPlan(MapRequest& mapRequest)
   at AutoMapper.MapperConfiguration.AutoMapper.Internal.IGlobalConfiguration.GetExecutionPlan[TSource,TDestination](MapRequest& mapRequest)
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, MemberMap memberMap)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source)
   at GITS.Pages.GovMax.ReleaseNotes.PopulateNotes(Object ver) in C:\GovMax\GITS\GITS-Dev\GITS\Pages\GovMax\ReleaseNotes.razor:line 183
   at GITS.Pages.GovMax.ReleaseNotes.OnInitializedAsync() in C:\GovMax\GITS\GITS-Dev\GITS\Pages\GovMax\ReleaseNotes.razor:line 94
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper/issues/3817
