### ISSUE TITLE
Ignore attribute causes exception for generic read-only properties

### ISSUE THREAD

**Issue by korser1** [AutoMapper/AutoMapper#3836]
Ignore attribute causes exception when used with generics

### Source/destination types

```csharp
        class Source
        {
            public List<NestedClass> SomeCollection { get; set; }
        }

        class NestedClass
        {
            public bool SomeProperty { get; set; }
        }


        [AutoMap(typeof(Source))]
        class Destination<TNested> where TNested: class
        {
            [Ignore] public TNested FirstInCollection => SomeCollection?.FirstOrDefault();

            public List<TNested> SomeCollection { get; set; }
        }
```
        

### Mapping configuration

```csharp
cfg.AddMaps(typeof(--type in your assembly--));
```

### Expected behavior

types are mapped with respect of ignored attributes

### Actual behavior

Exception thrown

System.InvalidOperationException: Sequence contains no matching element

System.InvalidOperationException
Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.Configuration.MemberConfigurationExpression`3.Configure(TypeMap typeMap) in C:\development\AutoMapper\src\AutoMapper\Configuration\MemberConfigurationExpression.cs:line 324
   at AutoMapper.Configuration.MappingExpressionBase.Configure(TypeMap typeMap) in C:\development\AutoMapper\src\AutoMapper\Configuration\MappingExpressionBase.cs:line 78
   at AutoMapper.ProfileMap.BuildTypeMap(IGlobalConfiguration configurationProvider, ITypeMapConfiguration config) in C:\development\AutoMapper\src\AutoMapper\ProfileMap.cs:line 158
   at AutoMapper.ProfileMap.Register(IGlobalConfiguration configurationProvider) in C:\development\AutoMapper\src\AutoMapper\ProfileMap.cs:line 137
   at AutoMapper.MapperConfiguration.Seal() in C:\development\AutoMapper\src\AutoMapper\Configuration\MapperConfiguration.cs:line 330
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression) in C:\development\AutoMapper\src\AutoMapper\Configuration\MapperConfiguration.cs:line 106
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure) in C:\development\AutoMapper\src\AutoMapper\Configuration\MapperConfiguration.cs:line 115
   at AutoMapper.UnitTests.IgnoreAttributeWithGenericMappers.CreateConfiguration() in C:\development\AutoMapper\src\UnitTests\Projection\IgnoreAttributeWithGenericMappers.cs:line 30
   at AutoMapper.UnitTests.NonValidatingSpecBase.CreateMapper() in C:\development\AutoMapper\src\UnitTests\AutoMapperSpecBase.cs:line 54
   at AutoMapper.UnitTests.NonValidatingSpecBase.get_Mapper() in C:\development\AutoMapper\src\UnitTests\AutoMapperSpecBase.cs:line 51
   at AutoMapper.UnitTests.IgnoreAttributeWithGenericMappers.Should_work_with_map() in C:\development\AutoMapper\src\UnitTests\Projection\IgnoreAttributeWithGenericMappers.cs:line 45

### Steps to reproduce
Please see gist: (https://gist.github.com/korser1/f2cb72c481bcbc5214fb0a786edf2f81)

Fluent syntax CreateMap with Ignore() works.

**Comment by lbargaoanu** [comment]
But if I remove tha attribute everything seems fine. There is no setter, it's ignored by default. Does that work?

**Comment by jbogard** [comment]
Where did the discussion go lol, do we have to unlock?

**Comment by lbargaoanu** [comment]
No. I removed it because I reopened the issue.

**Comment by lbargaoanu** [comment]
But yes, I messed this up. Now it's unlocked too.

**Comment by lbargaoanu** [comment]
@korser1 But if I remove tha attribute everything seems fine. There is no setter, it's ignored by default. Does that work?

**Comment by korser1** [comment]
Thanks for unlocking.

I believe this issue came from IgnoreMap removal.
Previously we used that attribute, and we couldn't skip it for collections, arrays...

Tested on 10.1.1

    [AutoMap(typeof(Source))]
    class Destination<TNested> where TNested: class
    {
        public TNested FirstInCollection => SomeCollection?.FirstOrDefault();
        public List<TNested> AnotherCopyCollection => SomeCollection;

        public List<TNested> SomeCollection { get; set; }
    }

Got error - Unmapped properties: AnotherCopyCollection


v 11.0 shows no error without [Ignore]



Will play more, thanks!

**Comment by lbargaoanu** [comment]
Sorry about messing up your issue :)

**Comment by korser1** [comment]
Please see the case with collection:

### Source/destination types

```csharp
            public class Source
            {
                public int Value { get; set; }
                public List<Nested> Collections { get; set; }
            }

            public class Nested
            {
                public string SomeString { get; set; }
            }

            [AutoMap(typeof(Source))]
            public class Dest
            {
                public int Value { get; set; }
                public List<Nested> Collections { get; set; }
                public List<Nested> FilteredCollection => Collections.Where(x => x.SomeString == "some string").ToList();
            }
```

### Mapping configuration

```csharp
cfg.AddMaps(typeof(--typeinassembly--));
```

### Version: 11.0.0
### Expected behavior

Configuration is valid

### Actual behavior

Unmapped properties: FilteredCollection

### Steps to reproduce

```csharp
typeof(AutoMapperConfigurationException).ShouldNotBeThrownBy(() => AssertConfigurationIsValid<Source, Dest>());
```

This code works:
```csharp
[Ignore] public List<Nested> FilteredCollection => Collections.Where(x => x.SomeString == "some string").ToList();
```

But it should be ignored by default, please see the discussion above.

**Comment by lbargaoanu** [comment]
https://docs.automapper.org/en/latest/10.0-Upgrade-Guide.html#all-collections-are-mapped-by-default-even-if-they-have-no-setter

**Comment by korser1** [comment]
Thanks!

in total:
DO NOT use [Ignore] for non-collection getter with no setter
ALWAYS use [Ignore] for collection getter with no setter
