### ISSUE TITLE
AutoMapper 11.0.1 throws NullReferenceException when using ProjectTo with a sub type

### ISSUE THREAD

**Issue by t00** [AutoMapper/AutoMapper#3921]
### Source/destination types

```csharp
    public class DestinationType
    {
        public string Answer { get; set; }
    }

    public class SourceType
    {
        public ICollection<SourceSubType> Values { get; set; } = new List<SourceSubType>();
    }

    public class SourceSubType
    {
        public string Value { get; set; }
    }
```

### Mapping configuration

```csharp
            config.CreateMap<SourceType, DestinationType>()
                    .ForMember(x => x.Answer, o => o.MapFrom(x => x.Values.Select(c => c.Value).FirstOrDefault()));

```

### Expected behavior
Up until version 10, there were no exception.

### Actual behavior

```
Exception (0) 1
      System.NullReferenceException: Object reference not set to an instance of an object.
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass10_0.<CreateProjectionCore>g__ProjectMemberCore|7(<>c__DisplayClass10_1& )
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass10_0.<CreateProjectionCore>g__TryProjectMember|2(MemberMap memberMap, Nullable`1 explicitExpansion)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass10_0.<CreateProjectionCore>g__ProjectProperties|1()
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjectionCore(ProjectionRequest request, Expression instanceParameter, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.FirstPassLetPropertyMaps.GetSubQueryExpression(ProjectionBuilder builder, Expression projection, TypeMap typeMap, ProjectionRequest& request, ParameterExpression instanceParameter)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjection(ProjectionRequest& request, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.AutoMapper.QueryableExtensions.Impl.IProjectionBuilder.CreateProjection(ProjectionRequest& request, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.Impl.EnumerableProjectionMapper.Project(IGlobalConfiguration configuration, MemberMap memberMap, TypeMap memberTypeMap, ProjectionRequest& request, Expression resolvedSource, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.Impl.EnumerableProjectionMapper.AutoMapper.QueryableExtensions.Impl.IProjectionMapper.Project(IGlobalConfiguration configuration, MemberMap memberMap, TypeMap memberTypeMap, ProjectionRequest& request, Expression resolvedSource, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass10_0.<CreateProjectionCore>g__ProjectMemberCore|7(<>c__DisplayClass10_1& )
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass10_0.<CreateProjectionCore>g__TryProjectMember|2(MemberMap memberMap, Nullable`1 explicitExpansion)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass10_0.<CreateProjectionCore>g__ProjectProperties|1()
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjectionCore(ProjectionRequest request, Expression instanceParameter, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjectionCore(ProjectionRequest& request, Expression instanceParameter, LetPropertyMaps letPropertyMaps, TypeMap& typeMap)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjection(ProjectionRequest& request, LetPropertyMaps letPropertyMaps)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjection(ProjectionRequest request)
         at AutoMapper.Internal.LockingConcurrentDictionary`2.<>c__DisplayClass1_1.<.ctor>b__1()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at System.Lazy`1.get_Value()
         at AutoMapper.Internal.LockingConcurrentDictionary`2.GetOrAdd(TKey& key)
         at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.GetProjection(Type sourceType, Type destinationType, Object parameters, MemberPath[] membersToExpand)
         at AutoMapper.QueryableExtensions.Extensions.ProjectionExpression.ToCore(Type destinationType, Object parameters, IEnumerable`1 memberPathsToExpand)
         at AutoMapper.QueryableExtensions.Extensions.ProjectionExpression.ToCore[TResult](Object parameters, IEnumerable`1 memberPathsToExpand)
         at AutoMapper.QueryableExtensions.Extensions.ProjectionExpression.To[TResult](Object parameters, Expression`1[] membersToExpand)
         at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)
         at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Expression`1[] membersToExpand)


Crash happens in foreach called from GetSubQueryExpression:

void ProjectProperties()
            {
                foreach (var propertyMap in typeMap.PropertyMaps.Where(pm => pm.CanResolveValue && pm.DestinationMember.CanBeSet()).OrderBy(pm => pm.DestinationMember.MetadataToken))
                {
                    var propertyProjection = TryProjectMember(propertyMap, propertyMap.ExplicitExpansion);
                    if (propertyProjection != null)
                    {
                        propertiesProjections.Add(Bind(propertyMap.DestinationMember, propertyProjection));
                    }
                }
            }

```

### Steps to reproduce

```csharp
   var items = new List<SourceType> { new SourceType { Values = new List<SourceSubType> { Value = "test"  } };
   var result = items.AsQueryable().ProjectTo<DestinationType>(mapper.ConfigurationProvider);
```

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.

**Comment by lbargaoanu** [comment]
Workaround in https://github.com/AutoMapper/AutoMapper/issues/3919.

**Comment by t00** [comment]
Indeed latest build does not have this issue - projection is working correctly.
Unfortunately the following workaround is not having any effect:

```
    config.ValueTransformers.Add<string>(val => val ?? "");
```

**Comment by lbargaoanu** [comment]
Maybe your case is different. You didn't provide a proper repro. Your code works for me. But the workaround is the better way. Do you have a `string` converter as in that issue? Did you replace it with the transformer?

**Comment by t00** [comment]
I do not have any converters nor transformers. Unfortunately object structure is too complex. There is also an object initializer in another property, creating a class instance which might have been a cause of sub-projection exception:

.ForMember(x => x.Flags, o => o.MapFrom(s => new FlagsModel { Value = s.Flags }))

Rest is standard.

**Comment by lbargaoanu** [comment]
Usually there is some simple workaround...

**Comment by spooky** [comment]
I have the same exception, but caused by the following line:

```
.ForMember(x => x.Conditions, opts => opts.ConvertUsing<TrackingListValueConverter<MemberConditionResource, MemberCondition>, List<MemberConditionResource>>(x => x.Conditions))
```

on 10.1.1 works fine, on 11.0.2-alpha.0.3 I still get the exception
