### ISSUE TITLE
NullReferenceException in CompileExecutionPlan

### ISSUE THREAD

**Issue by lecamarade** [AutoMapper/AutoMapper#3986]
The error stated to happen after upgrade from 8.1.1 to 11.0.1
https://gist.github.com/lecamarade/99157bfc734b935438eace8eb2c1246b
The gist works with 8.1.1 but doesn't with 11.0.1

### Source/destination types

```csharp
public record Property<T>(T Value = default);

public record Level1Properties
{
    public Level2Properties Level2P { get; set; }
}

public record Level2
{
    public Guid UserStoreId { get; init; }
    public Level3 Level3 { get; init; }
}

public record Level2Properties
{
    public Property<Level3Properties> Level3P { get; init; }
}

public record Level3
{
    public int Id { get; init; }
}

public record Level3Properties
{
    public Property <int> Id { get; init; }
}
```

### Mapping configuration

```csharp
   //needed to map Level2Properties to Level2
     cfg.CreateMap(typeof(Property<>), typeof(Property<>));

    cfg.CreateMap<Level2, Level1Properties>()
        .ForMember(dest => dest.Level2P, opt
            => opt.MapFrom(src => src));
    
    cfg.CreateMap<Level2, Level2Properties>()
        .ForMember(dest => dest.Level3P, opt
            => opt.MapFrom(src => new Property<Level3>(src.Level3)));
    
    cfg.CreateMap<Level3, Level3Properties>()
        .ForMember(dest => dest.Id, opt
            => opt.MapFrom(src => new Property<int>(src.Id)));
```

### Expected behavior

No exception

### Actual behavior

---> System.NullReferenceException: Object reference not set to an instance of an object.
at AutoMapper.MapperConfiguration.CompileExecutionPlan(MapRequest mapRequest)
at AutoMapper.Internal.LockingConcurrentDictionary2.<>c__DisplayClass1_1.<.ctor>b__1() at System.Lazy1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor) at System.Lazy1.CreateValue()
at System.Lazy1.get_Value() at AutoMapper.Internal.LockingConcurrentDictionary2.GetOrAdd(TKey& key)
at AutoMapper.MapperConfiguration.GetExecutionPlan(MapRequest& mapRequest)
at AutoMapper.MapperConfiguration.AutoMapper.Internal.IGlobalConfiguration.GetExecutionPlan[TSource,TDestination](MapRequest& mapRequest)
at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, MemberMap memberMap)
at AutoMapper.Mapper.AutoMapper.IInternalRuntimeMapper.Map[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, MemberMap memberMap)
at AutoMapper.ResolutionContext.MapInternal[TSource,TDestination](TSource source, TDestination destination, MemberMap memberMap)
at lambda_method1(Closure , User , UserPropertiesContainer , ResolutionContext )
--- End of inner exception stack trace ---
at lambda_method1(Closure , User , UserPropertiesContainer , ResolutionContext )
--- End of inner exception stack trace ---
at lambda_method1(Closure , User , UserPropertiesContainer , ResolutionContext )

### Steps to reproduce

Run [gist](https://gist.github.com/lecamarade/99157bfc734b935438eace8eb2c1246b)

**Comment by lbargaoanu** [comment]
A PR is welcome.
