### ISSUE TITLE
Regression in AutoMapper 12.0.0 in conjuction with AutoMapper.Extensions.EnumMapping

### ISSUE THREAD

**Issue by thedmi** [AutoMapper/AutoMapper#4086]
### Source/destination types

```csharp
public enum SomeEnum {
  One,
  Two
}

public enum OtherEnum {
  One,
  Two
}
```

### Mapping configuration

```csharp
CreateMap<SomeEnum, OtherEnum>()
  .ConvertUsingEnumMapping()
  .ReverseMap();    
```

### Expected behavior

Enum mapping with the latest `AutoMapper.Extensions.EnumMapping` (2.0.1) works.

### Actual behavior

Mapping fails with 

```text
System.MissingMethodException
Method not found: 'System.Type AutoMapper.TypeMap.get_DestinationTypeToUse()'.
   at AutoMapper.Extensions.EnumMapping.Internal.EnumMappingFeature`2.Configure(TypeMap typeMap)
   at AutoMapper.Features.FeatureExtensions.Configure(Features`1 features, TypeMap typeMap)
   at AutoMapper.Configuration.TypeMapConfiguration.Configure(TypeMap typeMap, List`1 sourceMembers)
   at AutoMapper.ProfileMap.BuildTypeMap(IGlobalConfiguration configuration, TypeMapConfiguration config)
   at AutoMapper.ProfileMap.Register(IGlobalConfiguration configuration)
   at AutoMapper.MapperConfiguration.<.ctor>g__Seal|20_0()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
```

**Comment by lbargaoanu** [comment]
https://github.com/AutoMapper/AutoMapper.Extensions.EnumMapping/issues/17

**Comment by lbargaoanu** [comment]
Try the [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build.
