### ISSUE TITLE
ProjectTo gives error but Map works

### ISSUE THREAD

**Issue by nealrobben** [AutoMapper/AutoMapper#4239]
I'm on version 12.0.0 of automapper and I have some strange behavior.
My application uses EF 7.0.0 to query a LocalDB database and has the following class (simplified):

```
public class Department
{
	public int DepartmentID { get; set; }
}
```

To experiment with DDD I wanted to start using value objects.
My first step was to change the ID to a value object:

```
public class Department
{
	public DepartmentId DepartmentID { get; set; }
}
```

The definition for DepartmentId is the following:

```
public readonly struct DepartmentId
{
    public int Value { get; }

	public DepartmentId(int value)
	{
		Value = value;
	}
	
	//Other methods/overrides omitted for brevity
}
```

I want to map this entity to a viewmodel which has an integer for the DepartmentId:

```
public class DepartmentDetailVM
{
	public int DepartmentID { get; set; }
}
```

My mapping:
`profile.CreateMap<Department, DepartmentDetailVM>()`

To be able to map the types I created a custom TypeConverter:

```
    public class DepartmentIdToIntConverter : ITypeConverter<DepartmentId, int>
    {
        public int Convert(DepartmentId source, int destination, ResolutionContext context)
        {
            return source.Value;
        }
    }
```
The problem I am having is with ProjectTo.
The following query does **NOT** work:

```
            var department = await _context.Departments
                .Include(i => i.Administrator)
                .AsNoTracking()
                .ProjectTo<DepartmentDetailVM>(_mapper.ConfigurationProvider)
                .FirstOrDefaultAsync(m => m.DepartmentID == request.ID, cancellationToken);
```

However, the following **DOES** work:

```
            var result = await _context.Departments
                .Include(i => i.Administrator)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.DepartmentID == request.ID, cancellationToken);

            var department = _mapper.Map<DepartmentDetailVM>(result);
```
			
I think this is some strange behavior because if I'm doing something wrong in my mapping I would expect both pieces of code to fail.

The error I get with ProjectTo is:

```
Argument types do not match
   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass8_0.<CreateProjectionCore>g__ProjectMemberCore|7(<>c__DisplayClass8_1& )
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass8_0.<CreateProjectionCore>g__TryProjectMember|2(MemberMap memberMap, Nullable`1 explicitExpansion, Expression defaultSource)
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass8_0.<CreateProjectionCore>g__ProjectProperties|1()
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjectionCore(ProjectionRequest request, Expression instanceParameter, TypeMap typeMap, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjection(ProjectionRequest& request, LetPropertyMaps letPropertyMaps)
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjection(ProjectionRequest request)
   at AutoMapper.Internal.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at AutoMapper.Internal.LockingConcurrentDictionary`2.GetOrAdd(TKey& key)
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.GetProjection(Type sourceType, Type destinationType, Object parameters, MemberPath[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ToCore(IQueryable source, Type destinationType, IConfigurationProvider configuration, Object parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ToCore[TResult](IQueryable source, IConfigurationProvider configuration, Object parameters, IEnumerable`1 memberPathsToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression`1[] membersToExpand)
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Expression`1[] membersToExpand)
   at ContosoUniversityBlazor.Application.Departments.Queries.GetDepartmentDetails.GetDepartmentDetailsQueryHandler.<Handle>d__3.MoveNext() in F:\Blazor\ContosoUniversityBlazorAuthenticated\Application\Departments\Queries\GetDepartmentDetails\GetDepartmentDetailsQueryHandler.cs:line 32
```

Am I doing something wrong? The fact that the second piece of code works suggests my mapping is OK.
But why doesn't ProjectTo work then?

Can anyone explain to me what is going wrong here?

Any feedback would be much appreciated.
  Kind regards,
        Neal

**Comment by jbogard** [comment]
That's because that operation is not supported: https://docs.automapper.org/en/stable/Queryable-Extensions.html#supported-mapping-options

And will never be supported by arbitrary LINQ query providers.
