### ISSUE TITLE
System.ArgumentException when making ProjectTo with System.DateTime to System.DateOnly mapping

### ISSUE THREAD

**Issue by Maximys** [AutoMapper/AutoMapper#4274]
### Source/destination types

```csharp
namespace ConsoleApp1.Database.Entities
{
    public class User
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

namespace ConsoleApp1.Dtos
{
    public class UserDto
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateOnly ModifiedAt { get; set; }
    }
}

```

### Mapping configuration

```csharp
protected MapperConfiguration CreateConfiguration()
        {
            MapperConfiguration returnValue;

            returnValue = new MapperConfiguration(cfg =>
            {
                cfg.CreateMap<DateTime, DateOnly>().ConstructUsing(src => new DateOnly(src.Year, src.Month, src.Day));
                cfg.CreateMap<User, UserDto>();
            });

            return returnValue;
        }
```

### Version: 12.0.1
EF Core 7.0.4
EF Core InMemory 7.0.4

### Expected behavior

Successful projection

### Actual behavior

`System.ArgumentException
Message = "Argument types do not match"
StackTrace = "      at System.Linq.Expressions.Expression.Constant(Object value, Type type) in /_/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/ConstantExpression.cs:line 97
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass8_0.<CreateProjectionCore>g__ProjectMemberCore|7(<>c__DisplayClass8_1& ) in /_/src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs:line 126
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass8_0.<CreateProjectionCore>g__TryProjectMember|2(MemberMap memberMap, Expression defaultSource) in /_/src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs:line 104
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.<>c__DisplayClass8_0.<CreateProjectionCore>g__ProjectProperties|1() in /_/src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs:line 93
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjectionCore(ProjectionRequest request, Expression instanceParameter, TypeMap typeMap, LetPropertyMaps letPropertyMaps) in /_/src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs:line 79
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjection(ProjectionRequest& request, LetPropertyMaps letPropertyMaps) in /_/src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs:line 54
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.CreateProjection(ProjectionRequest request) in /_/src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs:line 49
   at AutoMapper.Internal.LockingConcurrentDictionary``2.<>c__DisplayClass2_1.<.ctor>b__1() in /_/src/AutoMapper/Internal/LockingConcurrentDictionary.cs:line 9
   at System.Lazy``1.ViaFactory(LazyThreadSafetyMode mode) in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 321
   at System.Lazy``1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor) in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 348
   at System.Lazy``1.CreateValue() in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 426
   at System.Lazy``1.get_Value() in /_/src/libraries/System.Private.CoreLib/src/System/Lazy.cs:line 505
   at AutoMapper.Internal.LockingConcurrentDictionary``2.GetOrAdd(TKey& key) in /_/src/AutoMapper/Internal/LockingConcurrentDictionary.cs:line 12
   at AutoMapper.QueryableExtensions.Impl.ProjectionBuilder.GetProjection(Type sourceType, Type destinationType, Object parameters, MemberPath[] membersToExpand) in /_/src/AutoMapper/QueryableExtensions/ProjectionBuilder.cs:line 41
   at AutoMapper.QueryableExtensions.Extensions.ToCore(IQueryable source, Type destinationType, IConfigurationProvider configuration, Object parameters, IEnumerable``1 memberPathsToExpand) in /_/src/AutoMapper/QueryableExtensions/Extensions.cs:line 72
   at AutoMapper.QueryableExtensions.Extensions.ToCore[TResult](IQueryable source, IConfigurationProvider configuration, Object parameters, IEnumerable``1 memberPathsToExpand) in /_/src/AutoMapper/QueryableExtensions/Extensions.cs:line 70
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Object parameters, Expression``1[] membersToExpand) in /_/src/AutoMapper/QueryableExtensions/Extensions.cs:line 24
   at AutoMapper.QueryableExtensions.Extensions.ProjectTo[TDestination](IQueryable source, IConfigurationProvider configuration, Expression``1[] membersToExpand) in /_/src/AutoMapper/QueryableExtensions/Extensions.cs:line 36
   at ConsoleApp1.Database.Repositories.UserRepository.GetUsers() in C:\Users\User1\source\repos\ConsoleApp1\ConsoleApp1\Database\Repositories\UserRepository.cs:line 26``

### Steps to reproduce

```csharp
public IEnumerable<UserDto> GetUsers()
        {
            IEnumerable<UserDto> returnValue;

            using (MyDbContext context = new MyDbContext())
            {
                returnValue = context.Users
                    .ProjectTo<UserDto>(Configuration)
                    .ToList();
            }

            return returnValue;
        }
```

**Comment by Maximys** [comment]
My PR which fix this problem: https://github.com/AutoMapper/AutoMapper/pull/4273

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by Maximys** [comment]
My simple gist: https://gist.github.com/Maximys/987f353edc568de83e8923aef7c9c0e9

**Comment by lbargaoanu** [comment]
Obviosly I cannot execute _that_. But I think all you need is `cfg.CreateMap<DateTime, DateOnly>();`.

**Comment by lbargaoanu** [comment]
You need `ConvertUsing`, not `Constructusing`.

**Comment by lbargaoanu** [comment]
The [MyGet](https://docs.automapper.org/en/latest/The-MyGet-build.html) build works without a converter, just the default constructor mapping.
