### ISSUE TITLE
Recursive `record struct` mapped into reference type throws

### ISSUE THREAD

**Issue by gurustron** [AutoMapper/AutoMapper#4293]
### Source/destination types

```csharp
record struct T1(int i, List<T1> List);
record T2(int i, List<T2> List);
```

### Mapping configuration

```csharp
[Test]
public void Test22()
{
    var config = new MapperConfiguration(cfg =>
    {
        cfg.CreateMap<T1, T2>().ReverseMap();
    });
}
```

### Version: x.y.z
**12.0.1**

### Expected behavior

Test passes

### Actual behavior

```
System.InvalidOperationException : Coalesce used with type that cannot be null
   at System.Linq.Expressions.Expression.ValidateCoalesceArgTypes(Type left, Type right)
   at System.Linq.Expressions.Expression.Coalesce(Expression left, Expression right, LambdaExpression conversion)
   at AutoMapper.Execution.TypeMapPlanBuilder.CheckReferencesCache(Expression valueBuilder)
   at AutoMapper.Execution.TypeMapPlanBuilder.ConstructorMapping(ConstructorMap constructorMap)
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateNewDestinationFunc()
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateDestinationFunc()
   at AutoMapper.Execution.TypeMapPlanBuilder.CreateMapperLambda()
   at AutoMapper.TypeMap.CreateMapperLambda(IGlobalConfiguration configuration)
   at AutoMapper.TypeMap.Seal(IGlobalConfiguration configuration)
   at AutoMapper.MapperConfiguration.<.ctor>g__Seal|20_0()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
```

**Comment by gurustron** [comment]
Making both `record` or `record struct`'s fixes the exception.

**Comment by gurustron** [comment]
From [SO question ](https://stackoverflow.com/q/76095321/2501279)

**Comment by lbargaoanu** [comment]
Yeah, maybe not do that? :) Other than that, a PR is welcome.
