### ISSUE TITLE
AutoMapper.AutoMapperMappingException due to disposed IServiceProvider

### ISSUE THREAD

**Issue by whoaskedfrfr** [AutoMapper/AutoMapper#4338]
Any suggestion on how to debug this issue?
```
AutoMapper.AutoMapperMappingException: Error mapping types.

Mapping types:
ServiceModel -> ApiModel
ServiceModels.ServiceModel -> ApiModels.ApiModel

Type Map configuration:
ServiceModel -> ApiModel
ServiceModels.ServiceModel -> ApiModels.ApiModel

Destination Member:
Id
```

```
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'IServiceProvider'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ThrowHelper.ThrowObjectDisposedException()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at AutoMapper.ResolutionContext.CreateInstance(Type type)
   at lambda_method5211(Closure , Object , ServiceModel, ResolutionContext )
   --- End of inner exception stack trace ---

```

It's quite rare and I don't understand why AutoMapper is trying to access the service provider

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
