### ISSUE TITLE
null pointer 

### ISSUE THREAD

**Issue by zhanghaiboshiwo** [AutoMapper/AutoMapper#4343]
### Source/destination types
System.NullReferenceException: Object reference not set to an instance of an object.
at AutoMapper.Internal.TypeDetails.<GetMember>b__7_5(MethodInfo m)
at System.Linq.Utilities.<>c__DisplayClass1_01.<CombinePredicates>b__0(TSource x)    at System.Linq.Enumerable.WhereArrayIterator1.MoveNext()
at System.Linq.Enumerable.ConcatIterator1.MoveNext()    at AutoMapper.Internal.TypeDetails.<GetMember>g__SetNameToMember|7_0()    at AutoMapper.Internal.TypeDetails.GetMember(String name)    at AutoMapper.Configuration.Conventions.MemberConfiguration.GetSourceMember(TypeDetails sourceTypeDetails, Type destType, Type destMemberType, String nameToSearch)    at AutoMapper.TypeMap..ctor(Type sourceType, Type destinationType, ProfileMap profile, TypeMapConfiguration typeMapConfiguration, List1 sourceMembers)
at AutoMapper.ProfileMap.BuildTypeMap(IGlobalConfiguration configuration, TypeMapConfiguration config)
at AutoMapper.ProfileMap.Register(IGlobalConfiguration configuration)
at AutoMapper.MapperConfiguration.<.ctor>g__Seal|20_0()
at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__12_2(IServiceProvider sp)
at AspectCore.DependencyInjection.ServiceCallSiteResolver.<>c__DisplayClass4_0.<ResolveCallback>b__0(ServiceResolver resolver)
at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__12_3(IServiceProvider sp)
at AspectCore.DependencyInjection.ServiceCallSiteResolver.<>c__DisplayClass4_0.<ResolveCallback>b__0(ServiceResolver resolver)
at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
at lambda_method473(Closure , IServiceProvider , Object[] )
at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

### behavior

When I upgraded my project from.netCore 3.1 to.net6, automapper's null pointer will occasionally report an error. Has anyone experienced this problem?

**Comment by lbargaoanu** [comment]
A repro would help. Make a [gist](https://gist.github.com/lbargaoanu/9c7233441c3a3413cc2b9b9ebb5964a9) that we can execute and see fail.

**Comment by zhanghaiboshiwo** [comment]
The problem is difficult to repeat

**Comment by lbargaoanu** [comment]
If you're using `ShouldMapMethod`, remove it and see what happens.

**Comment by zhanghaiboshiwo** [comment]
I'll try
