### ISSUE TITLE
Upgrade from Dotnet 6 to Dotnet 8

### ISSUE THREAD

**Issue by jacodv** [AutoMapper/AutoMapper#4362]
### Background
We are upgrading our projects from `Dotnet 6` to `Dotnet 8`.  Automapper reference is `8.1.1`.  We cannot upgrade Automapper without a huge effort and it has been working, so was not on the roadmap.  We use the static Mapper reference throughout.

Related issue: https://github.com/AutoMapper/AutoMapper/issues/3988

The suggested workaround is not applicable because `.Internal()` does not exist.
```csharp
cfg.Internal().MethodMappingEnabled = false; 
```

### Mapping configuration

```csharp
 public static class AutoMapperSetup
 {
   private static bool _isInitialized;
   private static readonly object _locker = new object();

   public static void Initialize(IMapperConfigurationExpression configurationExpression)
   {
     lock (_locker)
     {
       if (!_isInitialized)
       {
         _isInitialized = true;
         Setup(configurationExpression);
       }
     }
   }

   private static void Setup(IMapperConfigurationExpression configurationExpression)
   {
     SetupModelToDal(configurationExpression);
     SetupModels(configurationExpression);
   }
```

### Expected behavior

The application should startup without errors.

### Actual behavior

The application fails to start with the error below

```
System.ArgumentException: GenericArguments[0], 'System.String', on 'System.Nullable`1[T] MaxInteger[T](System.Collections.Generic.IEnumerable`1[System.Nullable`1[T]])' violates the constraint of type 'T'.
 ---> System.Security.VerificationException: Method System.Linq.Enumerable.MaxInteger: type argument 'System.String' violates the constraint of type parameter 'T'.
   at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at AutoMapper.TypeDetails.<>c__DisplayClass30_1.<BuildPublicNoArgExtensionMethods>b__10(MethodInfo extensionMethod)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.UnionIterator`1.FillSet()
   at System.Linq.Enumerable.UnionIterator`1.ToArray()
   at AutoMapper.TypeDetails.BuildPublicNoArgExtensionMethods(IEnumerable`1 sourceExtensionMethodSearch)
   at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
   at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
   at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.LockingConcurrentDictionary`2.GetOrAdd(TKey key)
   at AutoMapper.ProfileMap.CreateTypeDetails(Type type)
   at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap options)
   at AutoMapper.ProfileMap.BuildTypeMap(IConfigurationProvider configurationProvider, ITypeMapConfiguration config)
   at AutoMapper.ProfileMap.Register(IConfigurationProvider configurationProvider)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at IIAB.Core.Startup.MapperHelper.Initialize(Action`1 action) in C:\Git\IIAB-netcore\src\IIAB.Core\Startup\MapperHelper.cs:line 3

```

**Comment by lbargaoanu** [comment]
I think this is better suited for StackOverflow.
