### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by ceee** [AutoMapper/AutoMapper#442]
This is basically [Issue 411](https://github.com/AutoMapper/AutoMapper/issues/411). As no one's interested in my comment, I created a new issue.

---

Hey.
Ran into the same issue with WP8, and its easy to reproduce:
1. Create a new project with template "Windows Phone App"
2. Select WP8 as target
3. Install AutoMapper via NuGet
4. Create two empty POCOs 
   `public class NItem { }`
   `public class Item { }`
5. Add `Mapper.CreateMap<Item, NItem>();` in the App constructor in App.xaml.cs.
6. Build in Debug mode and run in emulator or on device.

Leads to:

```
An exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.ni.dll and wasn't handled before a managed/native boundary

{System.IO.FileNotFoundException: Could not load file or assembly 'AutoMapper.Net4, Version=3.1.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The system cannot find the file specified.
File name: 'AutoMapper.Net4, Version=3.1.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at AutoMapper.Internal.ProbingAdapterResolver.ProbeForPlatformSpecificAssembly(String platformName)}
```

The exception is thrown **4 times**.
The first 3 occurrences are  

```
Could not load file or assembly 'AutoMapper.Net4' ...
Could not load file or assembly 'AutoMapper.WinRT' ...
Could not load file or assembly 'AutoMapper.SL5' ...
```

The 4th is:

```
An exception of type 'System.IO.FileLoadException' occurred in mscorlib.ni.dll and wasn't handled before a managed/native boundary

+       $exception  {System.IO.FileLoadException: Could not load file or assembly 'AutoMapper.WP8, Version=3.1.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'AutoMapper.WP8, Version=3.1.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at AutoMapper.Internal.ProbingAdapterResolver.ProbeForPlatformSpecificAssembly(String platformName)} System.Exception {System.IO.FileLoadException}
```

**Comment by gcsuk** [comment]
Hi

I have "break on all exceptions" enabled, I am only referencing Automapper and Automapper.Net4, and I got them from NuGet.

If I clean the project and run it there is no issue, but if I change anything and just run it I get the error every time! Cleaning before every build is a workaround, but its annoying.

Happens on any project on my machine.

Additional information: Could not load file or assembly 'AutoMapper.Net4, Version=3.3.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The system cannot find the file specified.

Is there a permanent solution?

**Comment by jbogard** [comment]
The permanent solution is in the 4.0 beta releases. I've collapsed the assemblies down to one per target framework.
