### ISSUE TITLE
Map to ExpandoObject is broken since 11.0.0

### ISSUE THREAD

**Issue by tsvx** [AutoMapper/AutoMapper#4457]
### Source/destination types

```csharp
// Source
public class Config
{
    // whatever props or without any props.
    public string ServerAddress { get; set; }
    public bool Enabled { get; set; }
}

// Destination - ExpandoObject
```

### Mapping configuration

```csharp
    var config = new MapperConfiguration(cfg => {});
    var mapper = config.CreateMapper();
```

### Version: >= 11.0.0

Problem detected on .NET 6.0 on Windows 10 x64.

### Expected behavior

This mapping (to `ExpandoObject`) worked in versions from 8.1.1 to 10.1.1, as [the documentation](https://docs.automapper.org/en/stable/Dynamic-and-ExpandoObject-Mapping.html) states:
> AutoMapper can map to/from dynamic objects without any explicit configuration

BTW, the mapping from `ExpandoObject` still works.

### Actual behavior

Since version 11.0.0 (to the 13.0.1), it gives
```
System.InvalidOperationException: No coercion operator is defined between types 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' and 'System.Dynamic.ExpandoObject'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at AutoMapper.MapperConfiguration.<AutoMapper.Internal.IGlobalConfiguration.BuildExecutionPlan>g__GenerateObjectMapperExpression|28_2(MapRequest& mapRequest, IObjectMapper mapper)
   at AutoMapper.MapperConfiguration.AutoMapper.Internal.IGlobalConfiguration.BuildExecutionPlan(MapRequest& mapRequest)
   at AutoMapper.MapperConfiguration.<.ctor>g__CompileExecutionPlan|20_2(MapRequest mapRequest)
   at AutoMapper.Internal.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.MapperConfiguration.AutoMapper.Internal.IGlobalConfiguration.GetExecutionPlan[TSource,TDestination](MapRequest& mapRequest)
   at AutoMapper.Mapper.MapCore[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context, Type sourceType, Type destinationType, MemberMap memberMap)
   at AutoMapper.Mapper.Map[TSource,TDestination](TSource source, TDestination destination)
   at AutoMapper.Mapper.Map[TDestination](Object source)
```

### Steps to reproduce

```csharp
	cc = new Config();
	var eo = mapper.Map<ExpandoObject>(cc);
```

**Comment by lbargaoanu** [comment]
A PR is welcome.
