### ISSUE TITLE
'Argument types do not match' when selecting off of a projection

### ISSUE THREAD

**Issue by MrZander** [AutoMapper/AutoMapper#4484]
### Source/destination types

```csharp
public class Entity
{
    public int ID { get; set; }
    public EntityType Type { get; set; }
    public IEnumerable<Tag> Tags { get; set; }
}

public class EntityType
{
    public int ID { get; set; }
    public IEnumerable<Tag> Tags { get; set; }
}

public class Tag
{
    public int ID { get; set; }
}

public class DtoEntity
{
    public int ID { get; set; }
    public DtoEntityType Type { get; set; }
    public IEnumerable<DtoTag> Tags { get; set; }
}

public class DtoEntityType
{
    public int ID { get; set; }
    public IEnumerable<DtoTag> Tags { get; set; }
}

public class DtoTag
{
    public int ID { get; set; }
}
```

### Mapping configuration

```csharp
public class Profiles : Profile
{
    public Profiles()
    {
        CreateMap<Entity, DtoEntity>();
        CreateMap<EntityType, DtoEntityType>();
        CreateMap<Tag, DtoTag>();
    }
}

//Usage:

            //Works
            var test = context.Entities
                .ProjectTo<DtoEntity>(cfg)
                .Select(f => new FinalResult
                {
                    Value = f.Tags.Count()
                })
                .Single();
            Console.WriteLine(test.Value);

            //Exception
            var test2 = context.Entities
                .ProjectTo<DtoEntity>(cfg)
                .Select(f => new FinalResult
                {
                    Value = f.Type.Tags.Count()
                })
                .Single();
            Console.WriteLine(test2.Value);

```

### Version: 13.0.1
EF Core 8.0.2

### Expected behavior

Successful execution of the query _after_ `ProjectTo`. 
 
### Actual behavior

An exception is raised
```
System.ArgumentException
  HResult=0x80070057
  Message=Argument types do not match
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse, Type type)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitConditional(ConditionalExpression conditionalExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Program.Main(String[] args) in redacted\ProjectionArgExceptionRepro\ProjectionArgExceptionRepro\Program.cs:line 116
```

### Steps to reproduce

Here is a full repro:
https://github.com/MrZander/ProjectionArgExceptionRepro

**Comment by lbargaoanu** [comment]
That looks like an EF Core issue. Check [the execution plan](https://docs.automapper.org/en/latest/Understanding-your-mapping.html). Run that as a LINQ statement, without AM. You should get the same result.

**Comment by MrZander** [comment]
I tested it without AutoMapper and it works as expected:

I've updated the repro with the below code:
```csharp
            //Works
            var test3 = context.Entities
                .Select(f => new DtoEntity()
                {
                    ID = f.ID,
                    Tags = f.Tags.Select(t => new DtoTag() { ID = t.ID }),
                    Type = new DtoEntityType()
                    {
                        ID = f.Type.ID,
                        Tags = f.Tags.Select(t => new DtoTag() { ID = t.ID })
                    }
                })
                .Select(f => new FinalResult
                {
                    Value = f.Type.Tags.Count()
                })
                .Single();
            Console.WriteLine(test3.Value);
```

And here is the execution plan:
'''
.Call System.Linq.Queryable.Select(
    .Extension<Microsoft.EntityFrameworkCore.Query.EntityQueryRootExpression>,
    '(.Lambda #Lambda1<System.Func`2[Entity,DtoEntity]>))

.Lambda #Lambda1<System.Func`2[Entity,DtoEntity]>(Entity $dtoEntity) {
    .New DtoEntity(){
        ID = $dtoEntity.ID,
        Type = .If ($dtoEntity.Type == .Default(System.Object)) {
            .Default(DtoEntityType)
        } .Else {
            .New DtoEntityType(){
                ID = ($dtoEntity.Type).ID,
                Tags = .Call System.Linq.Enumerable.Select(
                    ($dtoEntity.Type).Tags,
                    .Lambda #Lambda2<System.Func`2[Tag,DtoTag]>)
            }
        },
        Tags = .Call System.Linq.Enumerable.Select(
            $dtoEntity.Tags,
            .Lambda #Lambda3<System.Func`2[Tag,DtoTag]>)
    }
}

.Lambda #Lambda2<System.Func`2[Tag,DtoTag]>(Tag $dtoTag) {
    .New DtoTag(){
        ID = $dtoTag.ID
    }
}

.Lambda #Lambda3<System.Func`2[Tag,DtoTag]>(Tag $dtoTag) {
    .New DtoTag(){
        ID = $dtoTag.ID
    }
}
'''

I believe this is because of the `Type = .If ($dtoEntity.Type == .Default(System.Object))` check.  If I do this:
```csharp
            var test3 = context.Entities
                .Select(f => new DtoEntity()
                {
                    ID = f.ID,
                    Tags = f.Tags.Select(t => new DtoTag() { ID = t.ID }),
                    Type = f.Type == null ? null : new DtoEntityType()
                    {
                        ID = f.Type.ID,
                        Tags = f.Tags.Select(t => new DtoTag() { ID = t.ID })
                    }
                })
                .Select(f => new FinalResult
                {
                    Value = f.Type.Tags.Count()
                })
                .Single();
```
I get the error.

This _seems_ like an unnecessary operation in the mapping? I understand it from a non-EF situation cause you'd get a NullReferenceException, but EF doesn't need this null check right?

**Comment by lbargaoanu** [comment]
You can remove the check with `DoNotAllowNull`.

**Comment by MrZander** [comment]
> You can remove the check with `DoNotAllowNull`.

That's perfect.  I didn't realize that was an option.
Thank you!
