### ISSUE TITLE
Slow Initialization

### ISSUE THREAD

**Issue by toddca** [AutoMapper/AutoMapper#718]
We have a large MVC project with about 1480 ViewModels which are configured via about 150 profiles. This takes about 17 seconds to fully initialize on startup. In an attempt to try to address this performance issue we have looked into calling IConfiguration.AddProfile() within multiple threads and most of the time this appears to work and we can get the initialization down to about 5 seconds however we sometimes we receive some exceptions calling CreateMap(). Unfortunately we did not capture these during the last time came across them earlier today however I will update this thread with a stack once I have the information.

But I did want to put it out there -- is or should AddProfile() be a thread safe operation? Does anyone have any other strategies or ideas on how we can improve the init performance?

We were hoping that we could do a lazy init and only init a model/vm mapping when required however there does not appear to be any built in mechanism. That is, it would be nice if we could AddProfile() and then have the types added/cached and then initialized once they are requested via a Map operation. In our mind this would greatly speed up initialization and allow us to scale as we plan on adding additional models/VMs.

**Comment by toddca** [comment]
Here is an error we receive...note we do not have a solid repro.

Exception adding profile 'Drax.Web.ViewModels.State.Ma.ModelMapper': Destination array was not long enough. Check destIndex and length, and the array's lower bounds.

System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.

   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)

   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at AutoMapper.ThreadSafeList`1.GetEnumeratorImpl() in c:\dev\AutoMapper\src\AutoMapper\ThreadSafeList.cs:line 91

   at AutoMapper.ThreadSafeList`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in c:\dev\AutoMapper\src\AutoMapper\ThreadSafeList.cs:line 78

   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

   at AutoMapper.ConfigurationStore.FindExplicitlyDefinedTypeMap(Type sourceType, Type destinationType) in c:\dev\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 599

   at AutoMapper.ConfigurationStore.CreateTypeMap(Type source, Type destination, String profileName, MemberList memberList) in c:\dev\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 0

   at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination](String profileName, MemberList memberList) in c:\dev\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 197

   at AutoMapper.Profile.CreateMap[TSource,TDestination](MemberList memberList) in c:\dev\AutoMapper\src\AutoMapper\Profile.cs:line 143

   at AutoMapper.Profile.CreateMap[TSource,TDestination]() in c:\dev\AutoMapper\src\AutoMapper\Profile.cs:line 138

   at Drax.Web.ViewModels.State.Ma.ModelMapper.Configure() in c:\Dev\Bond\Drax\Main\src\Drax.Web\ViewModels\State\Ma\ModelMapper.cs:line 305

   at AutoMapper.ConfigurationStore.AddProfile(Profile profile) in c:\dev\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 152

   at Drax.Core.Services.ModelMapper.MapperEngine.<>c__DisplayClassd.<Initialize>b__9(Object t) in c:\Dev\Bond\Drax\Main\src\Drax.Core\Services\ModelMapper\MapperEngine.cs:line 95

System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.

   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)

   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)

   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

   at AutoMapper.ThreadSafeList`1.GetEnumeratorImpl() in c:\dev\AutoMapper\src\AutoMapper\ThreadSafeList.cs:line 91

   at AutoMapper.ThreadSafeList`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in c:\dev\AutoMapper\src\AutoMapper\ThreadSafeList.cs:line 78

   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

   at AutoMapper.ConfigurationStore.FindExplicitlyDefinedTypeMap(Type sourceType, Type destinationType) in c:\dev\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 599

   at AutoMapper.ConfigurationStore.CreateTypeMap(Type source, Type destination, String profileName, MemberList memberList) in c:\dev\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 0

   at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination](String profileName, MemberList memberList) in c:\dev\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 197

   at AutoMapper.Profile.CreateMap[TSource,TDestination](MemberList memberList) in c:\dev\AutoMapper\src\AutoMapper\Profile.cs:line 143

   at AutoMapper.Profile.CreateMap[TSource,TDestination]() in c:\dev\AutoMapper\src\AutoMapper\Profile.cs:line 138

   at Drax.Web.ViewModels.State.Ma.ModelMapper.Configure() in c:\Dev\Bond\Drax\Main\src\Drax.Web\ViewModels\State\Ma\ModelMapper.cs:line 305

   at AutoMapper.ConfigurationStore.AddProfile(Profile profile) in c:\dev\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 152

   at Drax.Core.Services.ModelMapper.MapperEngine.<>c__DisplayClassd.<Initialize>b__9(Object t) in c:\Dev\Bond\Drax\Main\src\Drax.Core\Services\ModelMapper\MapperEngine.cs:line 95

**Comment by jbogard** [comment]
So you have around 1500 TypeMap objects? Are you using LINQ projection?

**Comment by toddca** [comment]
No we are not (we use Dapper ORM) 95% of what we are mapping is model<->ViewModel and a total of 2,200 TypeMap objects.

**Comment by jbogard** [comment]
AddProfile is *supposed* to be thread sage - you can see I'm using a ThreadSafeList underneath the covers.

The problem here is that AutoMapper performs some runtime optimizations during config time. With 2200 TypeMap objects, you've likely got 10s of thousands of properties to map. For each property map I create compiled expressions to make it fast to access them. You trade off slow mapping for slow configuration.

Currently, I haven't found a great way to address this. I've tried switching to Reflection.Emit, for marginal gains (~10% faster), but since reflection compilation just uses Reflection.Emit underneath the covers, there's not much I can do there.

Another option would be to lazily add the mappings. You would need to add the profiles to the configuration on an as-needed basis as requests come in.

In the future, I'm examining Roslyn as a means to make the init faster, but for now, you'll need to manage the configuration a little more closely yourself.

As a reference, the biggest app we've had that uses AutoMapper has about 325, and it's a pretty big app (~100 controllers, 6-700 controller actions). Yours is 5 times bigger than that, this may sound weird, is your app too big?

**Comment by jbogard** [comment]
Oh! I have an idea. I'm going to try and lazily build out those accessors.

**Comment by toddca** [comment]
We have almost 200 controllers with just over 3000 views. The site is TaxPoint.com - specifically https://secure.taxpoint.com it is a US based tax preparation application - our app grows proportionally to the tax law. :-)

**Comment by toddca** [comment]
Just saw your comment -- I would think it acceptable to have a first map be a little slower (if this is your plan). or the first map within the scope of a profile. I have done quite a bit of testing and none of our profiles take more than a second to load. I have also written a test which loads all of our profiles in a multi-threaded fashion and it ran all night last week and I could not reproduce the issue.

**Comment by jbogard** [comment]
It is *really* hard to reproduce these issues - I have tests too that run config in a multi-threaded manner.

**Comment by jbogard** [comment]
So I made a change, to lazily build out accessors. Profiling the initialization, the bottleneck is now just traversing thousands of properties to find matches, not expression compilation. This dropped the time pretty considerably on my app, can you give this a shot?

http://www.nuget.org/packages/AutoMapper/4.0.0-ci1050

**Comment by toddca** [comment]
Jimmy, So good news / bad news.

Baseline
-----------------------
Version: 3.3.1
Loading 149 profiles concurrently with 8 threads: 5.5 – 6.2 seconds
Loading 149 profiles with 1 thread: 15.5 – 17 seconds


New Build
-----------------------
Version: 4.0.0-ci1050
Loading 149 profiles concurrently with 8 threads: FAILED
Loading 149 profiles with 1 thread: 7.7 – 9 seconds

So about a 50% improvement when using a single thread but it fails when multi-threaded.

I normally test with 8 threads however whenever I do that now it consistently fails with the following stack. If my test harness uses 2 threads I can get it to work but 4 threads or more tend to always fail.

Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at AutoMapper.ThreadSafeList`1.GetEnumeratorImpl()
   at AutoMapper.ThreadSafeList`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.ConfigurationStore.FindExplicitlyDefinedTypeMap(Type sourceType, Type destinationType)
   at AutoMapper.ConfigurationStore.CreateTypeMap(Type source, Type destination, String profileName, MemberList memberList)
   at AutoMapper.ConfigurationStore.CreateMap[TSource,TDestination](String profileName, MemberList memberList)
   at AutoMapper.Profile.CreateMap[TSource,TDestination](MemberList memberList)
   at AutoMapper.Profile.CreateMap[TSource,TDestination]()
   at Drax.Web.ViewModels.Federal.Income.InstallmentSales.ModelMapper.Configure() in c:\Dev\Bond\Drax\Main\src\Drax.Web\ViewModels\Federal\Income\InstallmentSales\ModelMapper.cs:line 48
   at AutoMapper.ConfigurationStore.AddProfile(Profile profile)
   at DraxTestCmd.Commands.MapperEngineCommandsCommand.<>c__DisplayClassa.<>c__DisplayClassf.<InitMapperEngineTest>b__8(Object t) in
c:\Dev\Bond\Drax\Main\src\DraxTestCmd\Commands\MapperEngineCommands.cs:line 147

**Comment by toddca** [comment]
OK I found the issue -- for the implementation of your reader/writer lock you are using NoOpReaderWriterLockFactory.cs which basically does not do any locking.

**Comment by jbogard** [comment]
Haaaaa are you serious? What DLL is actually getting referenced from the
package? (There are a ton of different ones there).

**Comment by toddca** [comment]
\packages\AutoMapper.4.0.0-ci1050\lib\net45\AutoMapper.dll
![readerwriter](https://cloud.githubusercontent.com/assets/1266854/7691217/5fc4c11c-fd7e-11e4-99c5-33f4c5f349b8.jpg)

**Comment by toddca** [comment]
So this is exactly the stack which has failed previously which leads me to believe we might have been using the NoOpReaderWriterLock in 3.3.1 too. I will test and confirm/deny...

**Comment by toddca** [comment]
In 3.3.1 it appears to be using the correct RW lock type - ReaderWriterLockSlimProxy

**Comment by jbogard** [comment]
Well that's odd, what does `PlatformAdapter.Resolve<IReaderWriterLockSlimFactory>().GetType()` return?

**Comment by jbogard** [comment]
OK I fixed the issue, just saw I needed to include a compiler directive - the latest fixes the issue.

**Comment by jbogard** [comment]
I found other threading issues , the next drop should help with that c467767

**Comment by toddca** [comment]
I got the new build and can confirm the threading issue is no more.

With the new build init takes 7-8 seconds for a single thread and 3-4 using multiple threads. FWIW there does not appear to be any perf benefit to using more than 4 threads. 

So for single threaded perf seems to have increased by ~50% and on multi-threaded ~25-30%.

Our init process uses a type finder to locate the mapper profiles and then spins up x threads to add them into the mapper configuration. With your latest fix we are in better shape, at about 3-4 seconds down from 5. 

We greatly appreciate your effort here. Thanks!

**Comment by jbogard** [comment]
So 17 seconds originally (which was thread unsafe) down to 3-4 seconds?

**Comment by toddca** [comment]
Single Thread: 
Before: 17 seconds
After: 7-8 seconds

Multi-Thread: 
Before: 5 seconds
After: 3-4 seconds
