### ISSUE TITLE
Automapper random error crash the whole IIS process?

### ISSUE THREAD

**Issue by jwu-au** [AutoMapper/AutoMapper#757]
Hi,

I am stuck on this for more than a day, trying to figure out what the problem is but no luck.

Background:
We have mapping correct setup, and have unit/integration tests to ensure they are correctly functioning. A day ago we setup a loading test to hit our staging server. And we found the IIS crash for roughly every 20 mins. I then used Debug Diagnostic tool to dump the crash process which leads me to ask the question here.

The error reports show the unhandled System.AccessViolationException exception crashed IIS process.

Crash captured by Debug Diagnositic tool:
```
In w3wp__BrandscreenWebApi__PID__4428__Date__06_29_2015__Time_05_51_11PM__789__Second_Chance_Exception_E0434352.dmp an unhandled .net exception happened on 28 and has caused the process to crash. 

When an unhandled exception is thrown in a Microsoft ASP.NET-based application that is built on the Microsoft .NET Framework 2.0, the application unexpectedly quits because the default policy for unhandled exceptions has changed in the .NET Framework 2.0. By default, the policy for unhandled exceptions is to end the worker process. 

Exception Details
System.AccessViolationException
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```
```
Thread 28 - System ID 1856

Entry point   clr!Thread::intermediateThreadProc 
Create time   6/29/2015 5:23:21 PM 
Time spent in user mode   0 Days 00:09:41.296 
Time spent in kernel mode   0 Days 00:01:24.406 


This thread is not fully resolved and may or may not be a problem. Further analysis of these threads may be required.

The thread has evidence of .net exceptions on the stack. Check the Previous .NET Exceptions Report (Exceptions in all .NET Thread Stacks) to view more details of the associated exception  

.NET Call Stack



Function

[[GCFrame]] 
[[GCFrame]] 

Full Call Stack



Function

KERNELBASE!RaiseException+68 
clr!RaiseTheExceptionInternalOnly+2fe 
clr!RaiseTheException+a4 
clr!RealCOMPlusThrow+69 
[[GCFrame]] 
clr!Thread::RaiseCrossContextException+338 
[[GCFrame]] 
clr!Thread::DoADCallBack+327166 
clr!UM2MDoADCallBack+91 
clr!UMThunkStub+26d 
webengine4!W3_MGD_HANDLER::ProcessNotification+78 
webengine4!ProcessNotificationCallback+42 
clr!UnManagedPerAppDomainTPCount::DispatchWorkItem+122 
clr!ThreadpoolMgr::ExecuteWorkRequest+46 
clr!ThreadpoolMgr::WorkerThreadStart+f4 
clr!Thread::intermediateThreadProc+7d 
kernel32!BaseThreadInitThunk+22 
ntdll!RtlUserThreadStart+34 

```

Stack where AccessViolationException happened
```
 AutoMapper.DelegateBasedResolver`2[[System.__Canon, mscorlib],[System.Nullable`1[[System.DateTime, mscorlib]], mscorlib]].Resolve(AutoMapper.ResolutionResult) 
   AutoMapper.NullReferenceExceptionSwallowingResolver.Resolve(AutoMapper.ResolutionResult) 
   System.Linq.Enumerable.Aggregate[[System.__Canon, mscorlib],[System.__Canon, mscorlib]](System.Collections.Generic.IEnumerable`1, System.__Canon, System.Func`3) 
   AutoMapper.Mappers.TypeMapObjectMapperRegistry+PropertyMapMappingStrategy.MapPropertyValue(AutoMapper.ResolutionContext, AutoMapper.IMappingEngineRunner, System.Object, AutoMapper.PropertyMap) 
   AutoMapper.Mappers.TypeMapObjectMapperRegistry+PropertyMapMappingStrategy.Map(AutoMapper.ResolutionContext, AutoMapper.IMappingEngineRunner) 
   AutoMapper.Mappers.TypeMapMapper.Map(AutoMapper.ResolutionContext, AutoMapper.IMappingEngineRunner) 
   AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(AutoMapper.ResolutionContext) 
   AutoMapper.MappingEngine.Map[[System.__Canon, mscorlib]](System.Object, System.Action`1) 
   Brandscreen.WebApi.Controllers.ReportsController+d__0.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Brandscreen.WebApi.Controllers.ReportsController+d__0, Brandscreen.WebApi]](d__0 ByRef) 
   Brandscreen.WebApi.Controllers.ReportsController.GetAdvertiserReport(Brandscreen.WebApi.Models.ReportCriteriaViewModel) 
   DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, System.Object, System.Object[]) 
   System.Web.Http.Controllers.ReflectedHttpActionDescriptor+ActionExecutor+<>c__DisplayClass12.b__8(System.Object, System.Object[]) 
   System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(System.Web.Http.Controllers.HttpControllerContext, System.Collections.Generic.IDictionary`2, System.Threading.CancellationToken) 
   System.Web.Http.Controllers.ApiControllerActionInvoker+d__0.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Controllers.ApiControllerActionInvoker+d__0, System.Web.Http]](d__0 ByRef) 
   System.Web.Http.Controllers.ApiControllerActionInvoker.InvokeActionAsyncCore(System.Web.Http.Controllers.HttpActionContext, System.Threading.CancellationToken) 
   System.Web.Http.Controllers.ActionFilterResult+ActionInvoker.InvokeActionAsync() 
   System.Web.Http.Controllers.ActionFilterResult.b__0(ActionInvoker) 
   System.Web.Http.Controllers.ActionFilterResult+<>c__DisplayClass10`1[[System.Web.Http.Controllers.ActionFilterResult+ActionInvoker, System.Web.Http]].b__f() 
   System.Web.Http.Filters.ActionFilterAttribute+d__5.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Filters.ActionFilterAttribute+d__5, System.Web.Http]](d__5 ByRef) 
   System.Web.Http.Filters.ActionFilterAttribute.CallOnActionExecutedAsync(System.Web.Http.Controllers.HttpActionContext, System.Threading.CancellationToken, System.Func`1>) 
   System.Web.Http.Filters.ActionFilterAttribute+d__0.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Filters.ActionFilterAttribute+d__0, System.Web.Http]](d__0 ByRef) 
   System.Web.Http.Filters.ActionFilterAttribute.ExecuteActionFilterAsyncCore(System.Web.Http.Controllers.HttpActionContext, System.Threading.CancellationToken, System.Func`1>) 
   System.Web.Http.Controllers.ActionFilterResult+<>c__DisplayClassb+<>c__DisplayClassd.b__9() 
   System.Web.Http.Controllers.ActionFilterResult+d__2.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Controllers.ActionFilterResult+d__2, System.Web.Http]](d__2 ByRef) 
   System.Web.Http.Controllers.ActionFilterResult.ExecuteAsync(System.Threading.CancellationToken) 
   System.Web.Http.Controllers.AuthorizationFilterResult+<>c__DisplayClass4.b__0() 
   System.Web.Http.Filters.AuthorizationFilterAttribute+d__2.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Filters.AuthorizationFilterAttribute+d__2, System.Web.Http]](d__2 ByRef) 
   System.Web.Http.Filters.AuthorizationFilterAttribute.ExecuteAuthorizationFilterAsyncCore(System.Web.Http.Controllers.HttpActionContext, System.Threading.CancellationToken, System.Func`1>) 
   System.Web.Http.Controllers.AuthorizationFilterResult+<>c__DisplayClass4+<>c__DisplayClass6.b__2() 
   System.Web.Http.Controllers.AuthorizationFilterResult.ExecuteAsync(System.Threading.CancellationToken) 
   System.Web.Http.Controllers.AuthenticationFilterResult+d__0.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Controllers.AuthenticationFilterResult+d__0, System.Web.Http]](d__0 ByRef) 
   System.Web.Http.Controllers.AuthenticationFilterResult.ExecuteAsync(System.Threading.CancellationToken) 
   Castle.Proxies.Invocations.ApiController_ExecuteAsync_3.InvokeMethodOnTarget() 
   Castle.DynamicProxy.AbstractInvocation.Proceed() 
   Brandscreen.Core.Interceptors.ProfilingInterceptor.Intercept(Castle.DynamicProxy.IInvocation) 
   Castle.DynamicProxy.AbstractInvocation.Proceed() 
   Castle.Proxies.ReportsControllerProxy.ExecuteAsync(System.Web.Http.Controllers.HttpControllerContext, System.Threading.CancellationToken) 
   System.Web.Http.Dispatcher.HttpControllerDispatcher+d__1.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Dispatcher.HttpControllerDispatcher+d__1, System.Web.Http]](d__1 ByRef) 
   System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken) 
   System.Net.Http.HttpMessageInvoker.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken) 
   System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken) 
   System.Web.Http.Owin.PassiveAuthenticationMessageHandler+d__0.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Owin.PassiveAuthenticationMessageHandler+d__0, System.Web.Http.Owin]](d__0 ByRef) 
   System.Web.Http.Owin.PassiveAuthenticationMessageHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken) 
   System.Web.Http.Owin.PassiveAuthenticationMessageHandler+d__0.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Owin.PassiveAuthenticationMessageHandler+d__0, System.Web.Http.Owin]](d__0 ByRef) 
   System.Web.Http.Owin.PassiveAuthenticationMessageHandler.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken) 
   System.Web.Http.HttpServer+d__0.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.HttpServer+d__0, System.Web.Http]](d__0 ByRef) 
   System.Web.Http.HttpServer.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken) 
   System.Net.Http.HttpMessageInvoker.SendAsync(System.Net.Http.HttpRequestMessage, System.Threading.CancellationToken) 
   System.Web.Http.Owin.HttpMessageHandlerAdapter+d__0.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.Web.Http.Owin.HttpMessageHandlerAdapter+d__0, System.Web.Http.Owin]](d__0 ByRef) 
   System.Web.Http.Owin.HttpMessageHandlerAdapter.InvokeCore(Microsoft.Owin.IOwinContext, Microsoft.Owin.IOwinRequest, Microsoft.Owin.IOwinResponse) 
   Microsoft.Owin.Extensions.UseHandlerMiddleware+<>c__DisplayClass3+<>c__DisplayClass5.<.ctor>b__1() 
   Owin.AutofacMvcAppBuilderExtensions+<b__0>d__2.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Owin.AutofacMvcAppBuilderExtensions+<b__0>d__2, Autofac.Integration.Mvc.Owin]](<b__0>d__2 ByRef) 
   Owin.AutofacMvcAppBuilderExtensions.b__0(Microsoft.Owin.IOwinContext, System.Func`1) 
   Microsoft.Owin.Extensions.UseHandlerMiddleware+<>c__DisplayClass3.<.ctor>b__0(Microsoft.Owin.IOwinContext) 
   Microsoft.Owin.Extensions.UseHandlerMiddleware.Invoke(System.Collections.Generic.IDictionary`2) 
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage+d__5.MoveNext() 
   System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage+d__5, Microsoft.Owin.Host.SystemWeb]](d__5 ByRef) 
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.RunApp(System.Func`2,System.Threading.Tasks.Task>, System.Collections.Generic.IDictionary`2, System.Threading.Tasks.TaskCompletionSource`1, Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult) 
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.BeginEvent(System.Object, System.EventArgs, System.AsyncCallback, System.Object) 
   System.Web.HttpApplication+AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() 
   System.Web.HttpApplication.ExecuteStep(IExecutionStep, Boolean ByRef) 
   System.Web.HttpApplication+PipelineStepManager.ResumeSteps(System.Exception) 
   System.Web.HttpApplication.BeginProcessRequestNotification(System.Web.HttpContext, System.AsyncCallback) 
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(System.Web.Hosting.IIS7WorkerRequest, System.Web.HttpContext) 
   System.Web.Hosting.PipelineRuntime.ProcessRequestNotificationHelper(IntPtr, IntPtr, IntPtr, Int32) 
   System.Web.Hosting.PipelineRuntime.ProcessRequestNotification(IntPtr, IntPtr, IntPtr, Int32) 
```

Below shows an error captured by NLog (this is random error, why it is trying to cast from "System.Runtime.CompilerServices.Closure", and why it is trying to cast the whole object to nullable DateTime? And the destination path having double "LocalToDateTime". so wired. Please see the mapping profile below.):
```
Mapping types:
ReportCriteriaViewModel -> Nullable`1
Brandscreen.WebApi.Models.ReportCriteriaViewModel -> System.Nullable`1[[System.DateTime, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]

Destination path:
ReportCriteria.LocalToDateTime.LocalToDateTime

Source value:
Brandscreen.WebApi.Models.ReportCriteriaViewModel ---> System.InvalidCastException: Unable to cast object of type 'System.Runtime.CompilerServices.Closure' to type 'Brandscreen.WebApi.Models.AdGroupViewModel'.
   at lambda_method(Closure , Object )
   at AutoMapper.DelegateBasedResolver`2.Resolve(ResolutionResult source) in c:\dev\AutoMapper\src\AutoMapper\Internal\DelegateBasedResolver2.cs:line 24
   at AutoMapper.NullReferenceExceptionSwallowingResolver.Resolve(ResolutionResult source) in c:\dev\AutoMapper\src\AutoMapper\Internal\NullReferenceExceptionSwallowingResolver.cs:line 18
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap) in c:\dev\AutoMapper\src\AutoMapper\Mappers\TypeMapObjectMapperRegistry.cs:line 116
   --- End of inner exception stack trace ---
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap) in c:\dev\AutoMapper\src\AutoMapper\Mappers\TypeMapObjectMapperRegistry.cs:line 153
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper) in c:\dev\AutoMapper\src\AutoMapper\Mappers\TypeMapObjectMapperRegistry.cs:line 89
   at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper) in c:\dev\AutoMapper\src\AutoMapper\Mappers\TypeMapMapper.cs:line 22
   at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in c:\dev\AutoMapper\src\AutoMapper\MappingEngine.cs:line 250
   at AutoMapper.MappingEngine.Map[TDestination](Object source, Action`1 opts) in c:\dev\AutoMapper\src\AutoMapper\MappingEngine.cs:line 69
   at Brandscreen.WebApi.Controllers.ReportsController.<GetAdvertiserReport>d__0.MoveNext() in c:\TeamCity\buildAgent\work\65fbcfe5a1f4e35d\src\Brandscreen.WebApi\Controllers\ReportsController.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

We setup automapper using Autofac and have http request scope injected into the service locator in Automapper, so that we can use service dependency in the mapping:
```c#
public class AutoMapperModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            // warming up the mapper to trigger PlatformAdapter loads extra things
            Mapper.Initialize(configuration => { });

            // assemblies
            var assemblies = AutofacAssemblyStore.GetAssemblies();

            // depend by ConfigurationStore
            builder.RegisterAssemblyTypes(assemblies)
                .Where(type => type.IsSubclassOf(typeof (Profile)))
                .As<Profile>()
                .InstancePerLifetimeScope();

            // depend by ConfigurationStore
            builder.RegisterInstance(new TypeMapFactory())
                .As<ITypeMapFactory>()
                .SingleInstance();

            // depend by ConfigurationStore
            MapperRegistry.Mappers.Add(new PagedListMapper());
            builder.RegisterInstance(MapperRegistry.Mappers)
                .As<IEnumerable<IObjectMapper>>();

            // depend by MappingEngine
            builder.RegisterType<ConfigurationStore>()
                .AsImplementedInterfaces()
                .InstancePerLifetimeScope()
                .OnActivating(args =>
                {
                    // set current lifetime scope for constructing services
                    var container = args.Context.Resolve<ILifetimeScope>();
                    args.Instance.ConstructServicesUsing(type => container.Resolve(type));

                    // add profiles
                    foreach (var profile in args.Context.Resolve<IEnumerable<Profile>>())
                    {
                        args.Instance.AddProfile(profile);
                    }
                });

            // depend by MappingEngine
            builder.Register(context => PlatformAdapter.Resolve<IDictionaryFactory>())
                .As<IDictionaryFactory>()
                .SingleInstance();
            builder.Register(context => context.Resolve<IDictionaryFactory>().CreateDictionary<TypePair, IObjectMapper>())
                .As<AutoMapper.Internal.IDictionary<TypePair, IObjectMapper>>()
                .SingleInstance();
            builder.Register(context =>
            {
                var container = context.Resolve<ILifetimeScope>();
                var serviceCtor = new Func<Type, object>(type => container.Resolve(type));
                return serviceCtor;
            })
                .As<Func<Type, object>>()
                .InstancePerLifetimeScope();

            // MappingEngine
            builder.RegisterType<MappingEngine>()
                .As<IMappingEngine>()
                .InstancePerLifetimeScope();
        }
    }
```

Below are the mapping profiles:
```
    public class ReportViewModel : PagedListMetaData
    {
        public string ReportType { get; set; }
        public string ReportLevel { get; set; }
        public IEnumerable<object> Data { get; set; }
    }

    public class ReportViewModelMapper : Profile
    {
        protected override void Configure()
        {
            CreateMap<IReport, ReportViewModel>()
                .ConstructUsing(ctx =>
                {
                    var dictionaryAdapterFactory = (IDictionaryAdapterFactory) ctx.Engine.ConfigurationProvider.ServiceCtor(typeof (IDictionaryAdapterFactory));
                    var pagination = dictionaryAdapterFactory.GetAdapter<IPagination>(ctx.Options.Items as IDictionary);
                    var source = (IReport) ctx.SourceValue;
                    var data = source.Data.ToPagedList(pagination.PageNumber, pagination.PageSize);

                    var model = new ReportViewModel {Data = data}; // mapping paged data
                    ctx.Engine.Map((PagedListMetaData) data, (PagedListMetaData) model); // mapping PagedListMetaData
                    return model;
                })
                .ForMember(dst => dst.Data, opt => opt.Ignore()); // as it is mapped in ConstructUsing
        }
    }
```

And

```c#
public class ReportCriteriaViewModel : Pagination
    {
        public ReportLevel ReportLevel { get; set; }
        public ReportScope? ReportScope { get; set; }
        public Guid? ReportScopeId { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
    }

    public class ReportCriteriaViewModelMapper : Profile
    {
        private readonly IUnitOfWorkAsync _unitOfWork;
        private readonly IOwinContext _owinContext;

        public ReportCriteriaViewModelMapper(IIndex<Type, IUnitOfWorkAsync> unitOfWorkIndex, IOwinContext owinContext)
        {
            _unitOfWork = unitOfWorkIndex[typeof (IBrandscreenContext)];
            _owinContext = owinContext;
        }

        protected override void Configure()
        {
            CreateMap<ReportCriteriaViewModel, ReportCriteria>()
                .ForMember(dst => dst.Type, opt => opt.Ignore())
                .ForMember(dst => dst.Level, opt => opt.MapFrom(src => src.ReportLevel))
                .ForMember(dst => dst.BuyerAccounts, opt =>
                {
                    opt.Condition(src => src.ReportScope == ReportScope.Buyer || !src.ReportScope.HasValue);
                    opt.ResolveUsing(src =>
                    {
                        // using specified: Buyer
                        if (src.ReportScope == ReportScope.Buyer && src.ReportScopeId.HasValue)
                        {
                            var buyerAccounts = _unitOfWork.RepositoryAsync<BuyerAccount>().Queryable().Where(x => x.BuyerAccountUuid == src.ReportScopeId.Value).ToList();
                            if (buyerAccounts.Count > 0) return buyerAccounts;
                        }

                        // using default
                        var buyerRoles = _owinContext.GetCurrentUserBuyerRoles();
                        var buyerAccountRepository = _unitOfWork.RepositoryAsync<BuyerAccount>();
                        return buyerRoles.Select(x => buyerAccountRepository.Find(x.BuyerId)).ToList();
                    });
                })
                .ForMember(dst => dst.Advertiser, opt =>
                {
                    opt.Condition(src => src.ReportScope == ReportScope.Advertiser && src.ReportScopeId.HasValue);
                    opt.MapFrom(src => _unitOfWork.RepositoryAsync<Advertiser>().Queryable().First(x => x.AdvertiserUuid == src.ReportScopeId));
                })
                .ForMember(dst => dst.AdvertiserProduct, opt =>
                {
                    opt.Condition(src => src.ReportScope == ReportScope.Brand && src.ReportScopeId.HasValue);
                    opt.MapFrom(src => _unitOfWork.RepositoryAsync<AdvertiserProduct>().Queryable().First(x => x.AdvertiserProductUuid == src.ReportScopeId));
                })
                .ForMember(dst => dst.Campaign, opt =>
                {
                    opt.Condition(src => src.ReportScope == ReportScope.Campaign && src.ReportScopeId.HasValue);
                    opt.MapFrom(src => _unitOfWork.RepositoryAsync<Campaign>().Queryable().First(x => x.CampaignUuid == src.ReportScopeId));
                })
                .ForMember(dst => dst.AdGroup, opt =>
                {
                    opt.Condition(src => src.ReportScope == ReportScope.Strategy && src.ReportScopeId.HasValue);
                    opt.MapFrom(src => _unitOfWork.RepositoryAsync<AdGroup>().Queryable().First(x => x.AdGroupUuid == src.ReportScopeId));
                })
                .ForMember(dst => dst.LocalFromDateTime, opt => opt.MapFrom(src => src.StartDate))
                .ForMember(dst => dst.LocalToDateTime, opt => opt.MapFrom(src => src.EndDate));
        }
    }
```

I can give more detail information if you need.
Thank you guys, wish me have some luck here.

**Comment by lbargaoanu** [comment]
Can you please zip and upload the dump somewhere?

**Comment by jwu-au** [comment]
Hi lbargaoanu,

The dump is quite big, 1.2G something. But I have good news here, it looks like I figure out what the problem is.

If you seen my above AutoMapperModule, I updated to below:
```c#
    public class AutoMapperModule : Module
    {
        protected override void Load(ContainerBuilder builder)
        {
            // warming up the mapper to trigger PlatformAdapter loads extra things
            Mapper.Initialize(configuration => { });

            // assemblies
            var assemblies = AutofacAssemblyStore.GetAssemblies();

            // depend by ConfigurationStore
            builder.RegisterAssemblyTypes(assemblies)
                .Where(type => type.IsSubclassOf(typeof (Profile)))
                .As<Profile>()
                .SingleInstance();

            // depend by ConfigurationStore
            builder.RegisterInstance(new TypeMapFactory())
                .As<ITypeMapFactory>()
                .SingleInstance();

            // depend by ConfigurationStore
            MapperRegistry.Mappers.Add(new PagedListMapper());
            builder.RegisterInstance(MapperRegistry.Mappers)
                .As<IEnumerable<IObjectMapper>>();

            // depend by MappingEngine
            builder.RegisterType<ConfigurationStore>()
                .AsImplementedInterfaces()
                .SingleInstance()
                .OnActivating(args =>
                {
                    // add profiles
                    foreach (var profile in args.Context.Resolve<IEnumerable<Profile>>())
                    {
                        args.Instance.AddProfile(profile);
                    }
                });

            // depend by MappingEngine
            builder.Register(context => PlatformAdapter.Resolve<IDictionaryFactory>())
                .As<IDictionaryFactory>()
                .SingleInstance();
            builder.Register(context => context.Resolve<IDictionaryFactory>().CreateDictionary<TypePair, IObjectMapper>())
                .As<AutoMapper.Internal.IDictionary<TypePair, IObjectMapper>>()
                .SingleInstance();
            builder.Register(context =>
            {
                var container = context.Resolve<ILifetimeScope>();
                var serviceCtor = new Func<Type, object>(type => container.Resolve(type));
                return serviceCtor;
            })
                .As<Func<Type, object>>()
                .InstancePerLifetimeScope();

            // MappingEngine
            builder.RegisterType<MappingEngine>()
                .As<IMappingEngine>()
                .InstancePerLifetimeScope();
        }
    }
```
The difference is I changed from InstancePerLifetimeScope to SingleInstance for Profile and ConfigurationStore. The reason I marked them InstancePerLifetimeScope previously is I want to use dependency injection while doing mapping (Check out the ReportCriteriaViewModelMapper in my first post). So for every http request, a new ConfigurationStore instance and all profile are created. This is WRONG, and needs lots of CPU. So I changed them to SingleInstance but still leaving MappingEngine InstancePerLifetimeScope, because I still need to supply the new service contructor Func to it for every http request. In this way, it seems the error is gone, and cpu usage drops dramatically.

So back to the problem domain, why IIS crashes roughly 20 mins if they are marked as InstancePerLifetimeScope. I can make a guess here, profile instances or ConfigurationStore or MappingEngine may not be disposed correctly for each http request??? or type caches conflicts??? or thread-safe issue???

For dependency injection during mapping, I'm having below extension to help me resolve dependent service object: Resolving from ResolutionContext wherever it is available. e.g. when using ResolveUsing or ConstructUsing.
```c#
public static class AutoMapperExtensions
    {
        public static T Resolve<T>(this ResolutionContext resolutionContext)
        {
            var type = typeof (T);
            return (T) resolutionContext.Options.ServiceCtor(type);
        }
    }
```

But If I pass my own options, the ServiceCtor won't be set. So I have below hack to set ServiceCtor to the value of current MapEngine.
```C#
    public static class PaginationExtensions
    {
        public static T Map<T>(this IMappingEngine mapping, object source, IPagination pagination)
        {
            return mapping.Map<T>(source, opts =>
            {
                // hack: AutoMapper won't set current service constructor when using custom IMappingOperationOptions
                // so set the current IMappingOperationOptions's service constructor with a value from map engine's private field
                opts.ConstructServicesUsing(ServiceCtorAccessor.Value(mapping));

                opts.Items.Add("PageNumber", pagination.PageNumber);
                opts.Items.Add("PageSize", pagination.PageSize);
            });
        }

        /// <summary>
        /// Accesses MappingEngine's service constructor(private field)
        /// </summary>
        public static Lazy<Func<object, Func<Type, object>>> ServiceCtorAccessor =
            new Lazy<Func<object, Func<Type, object>>>(() => GetFieldAccessor<MappingEngine, Func<Type, object>>("_serviceCtor"));

        /// <summary>
        /// Gives a function to access public/private field of an object
        /// </summary>
        public static Func<object, TReturn> GetFieldAccessor<TObject, TReturn>(string fieldName)
        {
            var param = Expression.Parameter(typeof (object), "obj");
            var convert = Expression.Convert(param, typeof (TObject));
            var field = Expression.Field(convert, fieldName);
            return Expression.Lambda<Func<object, TReturn>>(field, param).Compile();
        }
    }
```

My question is can we make MapEngine._serviceCtor public? or make mapping.Map<T>(source, opts => opts_is_using_the_default_one_with_serviceCtor)?

**Comment by jbogard** [comment]
Yeah that already exists https://github.com/AutoMapper/AutoMapper/blob/32959279d8b81087d1c84903f56755cc57d35740/src/AutoMapper/IMappingOperationOptions.cs#L15:

```
Mapper.Map<Foo, FooDto>(foo, opt => opt.ConstructServicesUsing(t => container.Resolve(t));
```

**Comment by jwu-au** [comment]
Hi Jbogard,

The correct ``` Func<Type, object> ``` have been set in IMappingEngine since it is created by Autofac for every http request. See my AutoMapperModule above in my second post.

In my case, below is an **extension** method
```
public static T Map<T>(this IMappingEngine mapping, object source, IPagination pagination)
        {
            return mapping.Map<T>(source, opts =>
            {
                // hack: AutoMapper won't set current service constructor when using custom IMappingOperationOptions
                // so set the current IMappingOperationOptions's service constructor with a value from map engine's private field
                opts.ConstructServicesUsing(ServiceCtorAccessor.Value(mapping));

                opts.Items.Add("PageNumber", pagination.PageNumber);
                opts.Items.Add("PageSize", pagination.PageSize);
            });
        }
```
I need to get the service constructor from ```this IMappingEngine mapping``` and set it to my customized option. So if MapEngine._serviceCtor is public, I don't need do the reflection/expression hack.

**Comment by lbargaoanu** [comment]
You can get the service constructor from your container (not from the mapping engine) and set it in the mapping options.

**Comment by jbogard** [comment]
^ this

MappingEngine should be singleton. The way to do nested containers in AutoMapper is to use the options, not create a new mapping engine with the new service ctor.
