### ISSUE TITLE
Could not load file or assembly (Version=3.3.1.0, PublicKeyToken=be96cd2c38ef1005)

### ISSUE THREAD

**Issue by gabrielius** [AutoMapper/AutoMapper#760]
Hey,

When deployed on my Client's PC, we get this error:
```
System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'AutoMapper, Version=3.3.1.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515) ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at ImageProcessor.Common.Helpers.TypeFinder.GetAllAssemblies()
   at ImageProcessor.Common.Helpers.TypeFinder.GetFilteredAssemblies(IEnumerable`1 excludeFromResults, String[] exclusionFilter)
   at ImageProcessor.Common.Helpers.TypeFinder.GetAssembliesWithKnownExclusions(IEnumerable`1 excludeFromResults)
   at ImageProcessor.Configuration.ImageProcessorBootstrapper.LoadSupportedImageFormats()
   at ImageProcessor.Configuration.ImageProcessorBootstrapper..ctor()
   at ImageProcessor.Configuration.ImageProcessorBootstrapper.<.cctor>b__8()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at ImageProcessor.Imaging.Formats.FormatUtilities.GetFormat(Stream stream)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MyClass.ImageManipulation.Rotate(Byte[] imageData, Single degrees) in C:\Source\ImageManipulation.cs:line 31
```
I am using AutoMapper 3.3.1.0 together with .NET 4 Framework. Works without a glitch locally. It seems that ImageProcessor library for some particular reason tries to load all the assemblies (I guess it's looking for plugins) and fails to do that with AutoMapper.

Please, advise :)

**Comment by jbogard** [comment]
Swallow the exception? This is a bug in the image processor library, no?

**Comment by gabrielius** [comment]
I was unsure at first, since when viewing with ILSpy/. NET Reflector, it seems AutoMapper is missing some libraries (I guess for use together with .NET 2.0?) and that's supposedly why ImageProcessor failed. Care to enlighten me?

![ilspy](https://cloud.githubusercontent.com/assets/7396135/8543786/48addd50-24a8-11e5-8ae4-4c603090861d.png)

**Comment by jbogard** [comment]
Portable Class Libraries, that's what you're seeing. AutoMapper isn't
missing anything, those types are forwarded over to the real thing at
runtime.

**Comment by gabrielius** [comment]
Oh I see, thanks :)
