### ISSUE TITLE
Support of Projected Filtering in Nested DTO with ExplicitExpansion

### ISSUE THREAD

**Issue by jvitor83** [AutoMapper/AutoMapper#773]
Consider the following scenario:

```csharp
void Main()
{
	var mappingFather = AutoMapper.Mapper.CreateMap<Father, FatherDTO>();
	mappingFather.ForAllMembers(r => r.Ignore());
	mappingFather.ForMember(dest => dest.IdDTO, opt => opt.MapFrom(src => src.Id));
	mappingFather.ForMember(dest => dest.NameDTO, opt => opt.MapFrom(src => src.Name));
	mappingFather.ForMember(dest => dest.ChildrenDTO, opt => {
		opt.MapFrom(src => src.Children);
		opt.ExplicitExpansion();
	});
	
	var mappingSon = AutoMapper.Mapper.CreateMap<Son, SonDTO>();
	mappingSon.ForAllMembers(r => r.Ignore());
	mappingSon.ForMember(dest => dest.IdDTO, opt => opt.MapFrom(src => src.Id));
	mappingSon.ForMember(dest => dest.NameDTO, opt => opt.MapFrom(src => src.Name));

	
	TestContext context = new TestContext();
	
	IQueryable<Father> fathers = context.Fathers;
	
	IQueryable<FatherDTO> fathersDTO = fathers.Project().To<FatherDTO>(membersToExpand: "Children");
	
	IQueryable<FatherDTO> fathersWithSonsNameAsJohnQueryable = fathersDTO.Where(f => f.ChildrenDTO.Any(c => c.NameDTO == "John"));
	
	List<FatherDTO> fathersWithSonsNameAsJohnExecuted = fathersWithSonsNameAsJohnQueryable.ToList(); //NotSupportedException
	
}

public class TestContext : System.Data.Entity.DbContext
{
	public TestContext() : base(@"Server=(localdb)\v11.0;Integrated Security=true;AttachDbFileName=C:\Windows\temp\Temp.mdf;")
	{
		Database.SetInitializer<TestContext>(new System.Data.Entity.DropCreateDatabaseAlways<TestContext>());
	}
	public DbSet<Father> Fathers { get; set; }
	public DbSet<Son> Children { get; set; }
}

public class FatherDTO
{
	public FatherDTO()
	{
		this.ChildrenDTO = (ICollection<SonDTO>)new HashSet<SonDTO>();
	}
	public int IdDTO { get; set; }
	public string NameDTO { get; set; }
	
	public ICollection<SonDTO> ChildrenDTO { get; set; }
}

public class SonDTO
{
	public int IdDTO { get; set; }
	public string NameDTO { get; set; }
}

public class Father
{
	public Father()
	{
		this.Children = (ICollection<Son>)new HashSet<Son>();
	}
	public int Id { get; set; }
	public string Name { get; set; }
	
	public ICollection<Son> Children { get; set; }
}

public class Son
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

With ExplicitExpansion the Where filter in the Children is not supported.
Once you remove the ExplictExpansion it works.

**Comment by jbogard** [comment]
What's the full exception?

**Comment by jvitor83** [comment]
Here is the full exception:


NotSupportedException
Message: The specified type member 'ChildrenDTO' is not supported in LINQ to Entities. Only initializers, entity members, and entity navigation properties are supported.
CallStack:
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MemberAccessTranslator.TypedTranslate(ExpressionConverter parent, MemberExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at UserQuery.Main() na c:\Users\23571\AppData\Local\Temp\LINQPad\_eblsfxln\query_dddenk.cs:line 55
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
   at LINQPad.ExecutionModel.Server.StartQuery(QueryRunner runner)
   at LINQPad.ExecutionModel.Server.<>c__DisplayClass36.<ExecuteClrQuery>b__35()
   at LINQPad.ExecutionModel.Server.SingleThreadExecuter.Work()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

InnerException: null

**Comment by jvitor83** [comment]
In the working sample, if you comment the line "opt.ExplicitExpansion();"  it work.

**Comment by lbargaoanu** [comment]
It works with To<FatherDTO>(membersToExpand: "ChildrenDTO"). I believe this is by design, but @jbogard knows best.

**Comment by jbogard** [comment]
Yep, it needs to be ChildrenDTO. The members to expand are *destination* members, not *source* members.

**Comment by jvitor83** [comment]
Got it! It worked. Thank you.
