### ISSUE TITLE
AfterMap incorrectly tries to map T to a List<T>

### ISSUE THREAD

**Issue by ChrisMissal** [AutoMapper/AutoMapper#802]
The following fails because of an attempt to map `T` to a `List<T>`:

    System.InvalidCastException: Unable to cast object of type 'ConsoleApplication1.ItemOne'
    to type 'System.Collections.Generic.List`1[ConsoleApplication1.ItemOne]'.

**Code**

```csharp
namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    using AutoMapper;

    class Program
    {
        static void Main(string[] args)
        {
            Mapper.AddProfile<TestProfile>();
            var mappingEngine = Mapper.Engine;

            var order = new Order
            {
                Items = new List<ItemOne>
                {
                    new ItemOne(),
                    new ItemOne(),
                }
            };

            var result = mappingEngine.Map<List<ItemOne>, List<ItemTwo>>(order.Items, opt =>
            {
                opt.AfterMap((src, dest) =>
                {
                    var i = 0;
                    foreach (var item in dest)
                    {
                        i++;
                        item.Number = i * 2;
                    }
                });
            });

            Console.WriteLine(result);
        }
    }

    class Order
    {
        public List<ItemOne> Items { get; set; }
    }

    class ItemTwo
    {
        public int Number { get; set; }
    }

    class ItemOne
    {
        public int Number { get; set; }
    }

    class TestProfile : Profile
    {
        protected override void Configure()
        {
            CreateMap<ItemOne, ItemTwo>();
        }
    }
}
```

**Stack trace**

```
Mapping types:
ItemOne -> ItemTwo
ConsoleApplication1.ItemOne -> ConsoleApplication1.ItemTwo

Destination path:
List`1[0]

Source value:
ConsoleApplication1.ItemOne
	AutoMapper.AutoMapperMappingException:
	
	Mapping types:
	ItemOne -> ItemTwo
	ConsoleApplication1.ItemOne -> ConsoleApplication1.ItemTwo
	
	Destination path:
	List`1[0]
	
	Source value:
	ConsoleApplication1.ItemOne ---> System.InvalidCastException: Unable to cast object of type 'ConsoleApplication1.ItemOne' to type 'System.Collections.Generic.List`1[ConsoleApplication1.ItemOne]'.
	at AutoMapper.MappingOperationOptions`2.<>c__DisplayClass4.<AfterMap>b__3(Object src, Object dest)
	at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.Map(ResolutionContext context, IMappingEngineRunner mapper)
	at AutoMapper.Mappers.TypeMapMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
	at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
	   --- End of inner exception stack trace ---
	at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
	at AutoMapper.Mappers.EnumerableMapperBase`1.Map(ResolutionContext context, IMappingEngineRunner mapper)
	at AutoMapper.Mappers.CollectionMapper.Map(ResolutionContext context, IMappingEngineRunner mapper)
	at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context)
	at AutoMapper.MappingEngine.MapCore(Object source, Type sourceType, Type destinationType, MappingOperationOptions options)
	at AutoMapper.MappingEngine.Map[TSource,TDestination](TSource source, Action`1 opts)
	Program.cs(25,0): at ConsoleApplication1.Program.Main(String[] args)
```

**Comment by lbargaoanu** [comment]
Did you try this on develop? Because I believe it should work now.

**Comment by lbargaoanu** [comment]
@ChrisMissal Can you close this?

**Comment by lbargaoanu** [comment]
No longer happens because of #1019.
