### ISSUE TITLE
Mapper.Initialize() throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [AutoMapper/AutoMapper#826]
So I'm making a webApi and I have my services layer which make things like:

        private readonly MyDbContext _context;
        private readonly IEventService _eventService;
        private readonly IProjectService _projectService;

        public CalendarController()
        {
            _context = new MyDbContext();
            _eventService = new EventService(_context);
            _projectService = new ProjectService(_context);
        }

which instantiates classes which extend my `BaseConfiguration` which is used to initialize AutoMapper

    public class CustomerService : BaseConfiguration, ICustomerService
    {
        CustomerRepository _customerRepository;
        // constructor
        public CustomerService(MyDbContext context)
        {
            _customerRepository = new CustomerRepository(context);
        }

>>>>>

    public class BaseConfiguration
    {
        public BaseConfiguration()
        {
            AutoMapperConfig.Configure();
        }
    }

..>>>>>>

    public static class AutoMapperConfig
    {
        public static void Configure()
        {
            Mapper.Initialize(cfg =>
            {
                cfg.AddProfile(new EventProfile());
                cfg.AddProfile(new GroupProfile());
                cfg.AddProfile(new ProjectProfile());
                cfg.AddProfile(new UserGroupProfile());
                cfg.AddProfile(new UserProfile());
                cfg.AddProfile(new ViewProfile());
                cfg.AddProfile(new CustomerProfile());
                cfg.AddProfile(new LoccoProfile());
                cfg.AddProfile(new JobTypeProfile());
                cfg.AddProfile(new TaskProfile());
                cfg.AddProfile(new TicketProfile());
                cfg.AddProfile(new HourProfile());
                cfg.AddProfile(new OvertimeProfile());
                
            });
        }
    }

The issue is that at: **AutoMapper/src/AutoMapper/Mappers/MapperRegistry.cs**
at:

        public static void Reset()
        {
            _mappers.Clear();
            _mappers.AddRange(_initialMappers);
        }

calling `_mappers.Clear()` is not thread-safe so I get **IndexOutOfBoundsException** 
I suppose it is my error that I call this at the same time so many times that I cause the race conditioning bug. What I'd like to suggest is that you document a bit better that this is possible if not handled (that the function is thread unsafe) or maybe if youd mutex it.

**Comment by DominikDitoIvosevic** [comment]
Call stack:

   at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.Clear()
   at AutoMapper.Mappers.MapperRegistry.Reset()
   at AutoMapper.Mapper.Reset()
   at AutoMapper.Mapper.Initialize(Action`1 action)
   at Services.Configuration.AutoMapperConfig.Configure() in C:\Users\Divosevic\Desktop\SPAN.Dev\SPAN.TimeSheet\TSWebAPI\Services\Configuration\AutoMapperConfig.cs:line 14
   at Services.Configuration.BaseConfiguration..ctor() in C:\Users\Divosevic\Desktop\SPAN.Dev\SPAN.TimeSheet\TSWebAPI\Services\Configuration\BaseConfiguration.cs:line 13
   at Services.Implementations.JobTypeService..ctor(MyDbContext context) in C:\Users\Divosevic\Desktop\SPAN.Dev\SPAN.TimeSheet\TSWebAPI\Services\Implementations\JobTypeService.cs:line 25
   at WebApi.Controllers.CalendarController..ctor() in C:\Users\Divosevic\Desktop\SPAN.Dev\SPAN.TimeSheet\TSWebAPI\WebAPI\Controllers\CalendarController.cs:line 37
   at lambda_method(Closure )
   at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)

**Comment by lbargaoanu** [comment]
You should be calling Initialize only one time.

**Comment by jbogard** [comment]
Yes, you should only be calling Initialize once. It's not thread-safe - nor was ever intentioned to be.
