### ISSUE TITLE
System.ArgumentException: Argument types do not match

### ISSUE THREAD

**Issue by sickboy** [AutoMapper/AutoMapper#848]
~~~
System.ArgumentException: Argument types do not match at System.Linq.Expressions.Expression.Condition(Expression test, Expression ifTrue, Expression ifFalse) 
at AutoMapper.QueryableExtensions.Impl.MappedTypeExpressionBinder.BindMappedTypeExpression(IMappingEngine mappingEngine, PropertyMap propertyMap, ExpressionRequest request, ExpressionResolutionResult result, IDictionary`2 typePairCount)
at AutoMapper.MappingEngine.CreateMemberBindings(ExpressionRequest request, TypeMap typeMap, Expression instanceParameter, IDictionary`2 typePairCount)
at AutoMapper.MappingEngine.CreateMapExpression(ExpressionRequest request, Expression instanceParameter, IDictionary`2 typePairCount)
at AutoMapper.MappingEngine.CreateMapExpression(ExpressionRequest request, IDictionary`2 typePairCount)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at AutoMapper.MappingEngine.CreateMapExpression(Type sourceType, Type destinationType, IDictionary`2 parameters, String[] membersToExpand)
at AutoMapper.QueryableExtensions.ProjectionExpression.To[TResult](IDictionary`2 parameters, String[] membersToExpand)
~~~

Code:
~~~
            cfg.CreateMap<Collection, CollectionStreamContentItem>()

    public abstract class StreamContentItem
    {
// properties
    }
    public class CollectionStreamContentItem : StreamContentItem
    {
// properties
    }
        static Task<List<CollectionStreamContentItem>> Convert(IQueryable<Collection> collections) {
            return collections.Take(ContentCount)
                .Project()
                .To<CollectionStreamContentItem>()
                .ToListAsync();
        }
~~~

**Comment by jbogard** [comment]
Does the projection work without using AutoMapper? Replacing Project().To() with Select?

**Comment by sickboy** [comment]
I believe it did work in AM3, but I will double check

**Comment by lbargaoanu** [comment]
This works for me on develop. It's true that I had to fill in the blanks. A complete repro can be executed, like #831 or, better yet, as in the integration tests project.

**Comment by jbogard** [comment]
Cool I'll close this one then
