### ISSUE TITLE
IndexOutOfRangeException in Mapper.Initialize()

### ISSUE THREAD

**Issue by abatishchev** [AutoMapper/AutoMapper#862]
I'm getting my unit tests sporadically failed due a weird exception:

```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.Clear()
   at AutoMapper.Mappers.MapperRegistry.Reset()
   at AutoMapper.Mapper.Reset()
   at AutoMapper.Mapper.Initialize(Action`1 action)
   at ContainerConfig.CreateContainer() in ContainerConfig.cs:line 55
```

at line that looks like this:

```csharp
container.RegisterSingleton<IMappingEngine>(() => new MappingEngine(container.GetInstance<IConfigurationProvider>()));
```

Full snippet:

```csharp
var container = new Container(); // Simple Injector

container.RegisterSingleton<ITypeMapFactory, TypeMapFactory>();
container.RegisterCollection<IObjectMapper>(MapperRegistry.Mappers);

container.RegisterSingleton<ConfigurationStore>();
container.Register<IConfiguration>(container.GetInstance<ConfigurationStore>);
container.RegisterSingleton<IConfigurationProvider>(container.GetInstance<ConfigurationStore>);

container.RegisterSingleton<IMappingEngine>(() => new MappingEngine(container.GetInstance<IConfigurationProvider>()));
```

**Comment by lbargaoanu** [comment]
Probably it's caused by concurrency. Initialize is not thread safe.

**Comment by lbargaoanu** [comment]
@abatishchev Can you close your issue?
