### ISSUE TITLE
Strange issue with "doubling up" of destination paths

### ISSUE THREAD

**Issue by dplaskon** [AutoMapper/AutoMapper#892]
I'm having a strange issue with Automapper 4.0.4 that did not occur with Automapper 3.3.1

I'm still trying to isolate a minimal repro (unfortunately this is part of a large/complex solution) to demonstrate the issue, but figured I would post what I have so far, in case anyone has any ideas.

Under certain circumstances, I'm getting exceptions like this:
```
System.Exception: 

Mapping types:
String -> String
System.String -> System.String

Destination path:
CreateCompletedTimelogEntryRequest.RecordedOutputs.RecordedOutputs.RecordedOutputs0[0].OutputValue.OutputValue

Source value:
This is my test value.
   at VolunteerSquared.Core.Extensions.AutoMapperExtensions.MapTo[TDest](Object source) in T:\TeamCity\buildAgent\work\5a9310d77d5a6d38\src\VolunteerSquared.Core\Extensions\AutoMapperExtensions.vb:line 16
   at VolunteerSquared.Web.Areas.Organization.Controllers.HoursController.CreateEntry(CreateEntryModel model) in T:\TeamCity\buildAgent\work\5a9310d77d5a6d38\src\VolunteerSquared.Web\Areas\Organization\Controllers\HoursController.vb:line 275
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at VolunteerSquared.Init.Adapters.WindsorActionInvoker.InvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters) in T:\TeamCity\buildAgent\work\5a9310d77d5a6d38\src\VolunteerSquared.Init\Adapters\WindsorActionInvoker.vb:line 22
   at System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName)
```

Note the destination path, which is like this:
```
CreateCompletedTimelogEntryRequest.RecordedOutputs.RecordedOutputs.RecordedOutputs0[0].OutputValue.OutputValue
```
And should actually be like this:
```
CreateCompletedTimelogEntryRequest.RecordedOutputs.RecordedOutputs0[0].OutputValue
```

Any thoughts on this?

**Comment by lbargaoanu** [comment]
A simple failing test would help.

**Comment by dplaskon** [comment]
I'm still trying to isolate a (simple) test case -- but it's proved difficult. Any idea how something like this could even happen in the first place?

**Comment by jbogard** [comment]
Does this happen every time, or only occassionally?

**Comment by dplaskon** [comment]
Every time a particular mapping is executed -- but it only occurs for a few mappings out of hundreds in the project...I'm having a hard time isolating what makes those mappings unique.

**Comment by jbogard** [comment]
Would it be possible to post those mappings? Anonymized if need be

**Comment by dplaskon** [comment]
I'm working on that Jimmy...is there any run-time/debug info that would be helpful?

**Comment by jbogard** [comment]
Not really, the source/destination types plus config are the best things to go on for me.

**Comment by dplaskon** [comment]
hrmmm...alright....

The issue is that I can't really determine *which* map (or combination of maps) is causing the issue -- it's not the one from the error message itself, as it works fine in isolation. Some of these classes have dozens of mappings to other classes, making it really hard to narrow down the issue.

A few guesses:

1) Issue with mapping classes with the same name in different namespaces?
2) Issue with having several source classes mapped against a single destination one?

I'm honestly at a loss.
