### ISSUE TITLE
4.1.0 sets destination property to `null` when source property have multiple upper case letters

### ISSUE THREAD

**Issue by pedroreys** [AutoMapper/AutoMapper#952]
When the source property has multiple upper case letters, like `BaseUOM` in the example below, `4.0.4` is able to project that as expected. `4.1.0` on the other hand projects a `null` value in the destination property.

## Repro
````csharp
namespace AutoMapperBugRepro
{
    using AutoMapper;

    using Shouldly;

    public class AutoMapperTests
    {
        public AutoMapperTests()
        {
            Mapper.CreateMap<Material, Destination>();
        }

        public void Should_project_using_Mapper_when_source_has_capital_letters_in_property_name()
        {
            var material = new Material { BaseUOM = new UOM { UOMCode = "sqft" } };

            var destination = Mapper.Map<Destination>(material);

            destination.BaseUomUomCode.ShouldBe(material.BaseUOM.UOMCode);
        }
    }

    public class Material
    {
        public UOM BaseUOM { get; set; }
    }

    public class UOM
    {
        public string UOMCode { get; set; }
    }

    public class Destination
    {
        public string BaseUomUomCode { get; set; }
    }
}
````

### Test Results
Here are the output of running the test above with 4.0.4 and 4.1.0

#### AutoMapper 4.0.4
````
------ Test started: Assembly: AutoMapperBugRepro.dll ------

1 passed, 0 failed, 0 skipped, took 0,53 seconds (Fixie 1.0.0.33).
````

#### AutoMapper 4.1.0
````
------ Test started: Assembly: AutoMapperBugRepro.dll ------

Test 'AutoMapperBugRepro.AutoMapperTests.Should_project_using_Mapper_when_source_has_capital_letters_in_property_name' failed:
	Shouldly.ShouldAssertException
	
	    destination.BaseUomUomCode
	        should be
	    "sqft"
	        but was
	    null
	at Shouldly.ShouldlyCoreExtensions.AssertAwesomelyWithCaseSensitivity[T](T actual, Func`2 specifiedConstraint, Object originalActual, Object originalExpected, Case caseSensitivity, Func`1 customMessage)
	at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected, Case caseSensitivity, Func`1 customMessage)
	at Shouldly.ShouldBeStringTestExtensions.ShouldBe(String actual, String expected)
	Class1.cs(20,0): at AutoMapperBugRepro.AutoMapperTests.Should_project_using_Mapper_when_source_has_capital_letters_in_property_name()

0 passed, 1 failed, 0 skipped, took 0,64 seconds (Fixie 1.0.0.33).
````

**Comment by pedroreys** [comment]
I believe this is a duplicate of #950. Closing it.

**Comment by TylerCarlson1** [comment]
Beat me to the punch
