### ISSUE TITLE
Multithreading issue

### ISSUE THREAD

**Issue by lbargaoanu** [AutoMapper/AutoMapper#961]
Test Name:	AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues.Should_not_fail
Test FullName:	AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues.Should_not_fail
Test Source:	D:\Projects\AutoMapper\src\UnitTests\Bug\MultiThreadingIssues.cs : line 199
Test Outcome:	Failed
Test Duration:	0:00:00.0434194

Result StackTrace:	
Assert.Null() Failure
Expected: (null)
Actual:   System.AggregateException: One or more errors occurred. ---> AutoMapper.AutoMapperMappingException: 
          
          Mapping types:
          SomeDtoA -> SomeDtoB
          AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues+SomeDtoA -> AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues+SomeDtoB
          
          Destination path:
          SomeDtoB
          
          Source value:
          AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues+SomeDtoA ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
             at System.Collections.Generic.List`1.Add(T item)
             at AutoMapper.Profile.get_DefaultMemberConfig() in D:\Projects\AutoMapper\src\AutoMapper\Profile.cs:line 165
             at AutoMapper.ConfigurationStore.GetProfile(String profileName) in D:\Projects\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 642
             at AutoMapper.ConfigurationStore.<>c__DisplayClass80_0.<CreateTypeMap>b__0(TypePair tp) in D:\Projects\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 322
             at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
             at AutoMapper.Internal.DictionaryFactoryOverride.ConcurrentDictionaryImpl`2.GetOrAdd(TKey key, Func`2 valueFactory) in D:\Projects\AutoMapper\src\AutoMapper\Internal\ConcurrentDictionaryFactory.cs:line 37
             at AutoMapper.ConfigurationStore.CreateTypeMap(Type source, Type destination, String profileName, MemberList memberList) in D:\Projects\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 320
             at AutoMapper.ConfigurationStore.CreateTypeMap(Type source, Type destination, String profileName) in D:\Projects\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 314
             at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in D:\Projects\AutoMapper\src\AutoMapper\MappingEngine.cs:line 420
             --- End of inner exception stack trace ---
             at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in D:\Projects\AutoMapper\src\AutoMapper\MappingEngine.cs:line 447
             at AutoMapper.MappingEngine.DynamicMap(Object source, Type sourceType, Type destinationType) in D:\Projects\AutoMapper\src\AutoMapper\MappingEngine.cs:line 226
             at AutoMapper.MappingEngine.DynamicMap[TSource,TDestination](TSource source) in D:\Projects\AutoMapper\src\AutoMapper\MappingEngine.cs:line 197
             at AutoMapper.Mapper.DynamicMap[TSource,TDestination](TSource source) in D:\Projects\AutoMapper\src\AutoMapper\Mapper.cs:line 176
             at AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues.<>c.<Should_not_fail>b__4_1() in D:\Projects\AutoMapper\src\UnitTests\Bug\MultiThreadingIssues.cs:line 207
             at System.Threading.Tasks.Task.Execute()
             --- End of inner exception stack trace ---
             at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
             at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
             at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
             at AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues.Should_not_fail() in D:\Projects\AutoMapper\src\UnitTests\Bug\MultiThreadingIssues.cs:line 216
          ---> (Inner Exception #0) AutoMapper.AutoMapperMappingException: 
          
          Mapping types:
          SomeDtoA -> SomeDtoB
          AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues+SomeDtoA -> AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues+SomeDtoB
          
          Destination path:
          SomeDtoB
          
          Source value:
          AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues+SomeDtoA ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
             at System.Collections.Generic.List`1.Add(T item)
             at AutoMapper.Profile.get_DefaultMemberConfig() in D:\Projects\AutoMapper\src\AutoMapper\Profile.cs:line 165
             at AutoMapper.ConfigurationStore.GetProfile(String profileName) in D:\Projects\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 642
             at AutoMapper.ConfigurationStore.<>c__DisplayClass80_0.<CreateTypeMap>b__0(TypePair tp) in D:\Projects\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 322
             at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
             at AutoMapper.Internal.DictionaryFactoryOverride.ConcurrentDictionaryImpl`2.GetOrAdd(TKey key, Func`2 valueFactory) in D:\Projects\AutoMapper\src\AutoMapper\Internal\ConcurrentDictionaryFactory.cs:line 37
             at AutoMapper.ConfigurationStore.CreateTypeMap(Type source, Type destination, String profileName, MemberList memberList) in D:\Projects\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 320
             at AutoMapper.ConfigurationStore.CreateTypeMap(Type source, Type destination, String profileName) in D:\Projects\AutoMapper\src\AutoMapper\ConfigurationStore.cs:line 314
             at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in D:\Projects\AutoMapper\src\AutoMapper\MappingEngine.cs:line 420
             --- End of inner exception stack trace ---
             at AutoMapper.MappingEngine.AutoMapper.IMappingEngineRunner.Map(ResolutionContext context) in D:\Projects\AutoMapper\src\AutoMapper\MappingEngine.cs:line 447
             at AutoMapper.MappingEngine.DynamicMap(Object source, Type sourceType, Type destinationType) in D:\Projects\AutoMapper\src\AutoMapper\MappingEngine.cs:line 226
             at AutoMapper.MappingEngine.DynamicMap[TSource,TDestination](TSource source) in D:\Projects\AutoMapper\src\AutoMapper\MappingEngine.cs:line 197
             at AutoMapper.Mapper.DynamicMap[TSource,TDestination](TSource source) in D:\Projects\AutoMapper\src\AutoMapper\Mapper.cs:line 176
             at AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues.<>c.<Should_not_fail>b__4_1() in D:\Projects\AutoMapper\src\UnitTests\Bug\MultiThreadingIssues.cs:line 207
             at System.Threading.Tasks.Task.Execute()<---
          
   at AutoMapper.UnitTests.Bug.DynamicMapThreadingIssues.Should_not_fail() in D:\Projects\AutoMapper\src\UnitTests\Bug\MultiThreadingIssues.cs:line 222
Result Message:	Should.Core.Exceptions.NullException

**Comment by jbogard** [comment]
Tests are passing now.

**Comment by lbargaoanu** [comment]
Yes, despite my efforts to make it fail, but I have no idea why :) GetOrAdd can still be called concurrently and call List.Add outside any lock.
